<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bastián Martin Gerdes">
<meta name="author" content="Isidora Valencia Almendras">
<meta name="author" content="Maite Jullian Corral">
<meta name="author" content="Manuela Chateau Vives">
<meta name="author" content="Marta Bascuñán Soto">
<meta name="description" content="Profesor: Juan Carlos CastilloApoyos Docentes: Andreas Laffert y Martín Venegas">

<title>Impacto de la percepción de seguridad en la aprobación de Bukele y confianza en el gobierno: Un análisis bivariado con datos de LAPOP 2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/clipboard/clipboard.min.js"></script>
<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/quarto-html/quarto.js"></script>
<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/quarto-html/popper.min.js"></script>
<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/quarto-html/anchor.min.js"></script>
<link href="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/quarto-html/quarto-syntax-highlighting-07ba0ad10f5680c660e360ac31d2f3b6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/bootstrap/bootstrap-deac6fc017450e3fa9f333c488460ad6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



<link rel="stylesheet" href="estilos.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul class="collapse">
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">2</span> Metodología</a></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">3</span> Análisis</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">4</span> Conclusiones</a></li>
  <li><a href="#bibliografia" id="toc-bibliografia" class="nav-link" data-scroll-target="#bibliografia"><span class="header-section-number">5</span> Bibliografía</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Impacto de la percepción de seguridad en la aprobación de Bukele y confianza en el gobierno: Un análisis bivariado con datos de LAPOP 2023</h1>
<p class="subtitle lead">Estadística Correlacional 2024, Carrera de Sociología - Universidad de Chile</p>
</div>

<div>
  <div class="description">
    <ul>
    <li>Profesor: Juan Carlos Castillo</li>
    <li>Apoyos Docentes: Andreas Laffert y Martín Venegas</li>
    </ul>
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Bastián Martin Gerdes </p>
             <p>Isidora Valencia Almendras </p>
             <p>Maite Jullian Corral </p>
             <p>Manuela Chateau Vives </p>
             <p>Marta Bascuñán Soto </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">1 de diciembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    El Salvador ha desarrollado una política represiva y ha limitado derechos constitucionales de su ciudadanía en razón de mejorar la seguridad de dicho país. Se realizaron 3 asociaciones entre variables de la base de datos en la Encuesta Latin American Political Opinion Project (LAPOP), del año 2023. Este estudio tiene por objetivo contrastar tres hipótesis, primero, se espera que a mayor percepción de seguridad en la actualidad, mayor aprobación de Bukele (H1), segundo, se espera que a mayor noción de que mejoró la seguridad, mayor aprobación de Bukele (H2), y por último, se espera que exista una asociación entre la sensación de seguridad en la actualidad y la confianza en que el gobierno nacional está haciendo lo correcto (H3). Se utilizó el estadístico de prueba de hipótesis Spearman para las primeras dos asociaciones, y para la última se usó Chi cuadrado a a través del software Rstudio. Al hacer el análisis bivariado se puede mencionar que existe evidencia a favor de las hipótesis H1; (r =0.224, p&lt;0.001), H2; (r =0.4165, p&lt;0.001) y H3; (X2 = 151.94, df = 9, V = 0.185, p&lt;0.001).
  </div>
</div>


</header>


<section id="introducción" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">1</span> Introducción</h2>
<p>Las fallidas políticas de seguridad de los gobiernos predecesores han aumentado la escalada de la violencia y con esto la desconfianza en instituciones y la clase política tradicional. El descontento con problemáticas sociales y políticas contribuyeron al triunfo de Nayib Bukele en el año 2019, imponiendo un régimen de excepción para combatir a las pandillas, una deriva autoritaria que lo ha convertido en uno de los presidentes salvadoreños mejor evaluados (Sanchez, 2024).</p>
<p>Tras esto, El Salvador ha desarrollado un enfoque multifacético de medidas preventivas y represivas para combatir el crimen y la violencia para la recomposición de la paz dentro de sus límites territoriales, esto debido al aumento de crímenes y la violencia por parte de las pandillas desde finales de marzo del año 2022 (Milena &amp; Sabykira, 2024).</p>
<p>La relevancia de la investigación radica en el alto impacto mediático que ha tenido el gobierno de Bukele. En este mismo sentido, sus políticas con respecto a la seguridad en El Salvador, han sido de gran inspiración a la ultraderecha Latinoamericana, sobre cómo afrontar los niveles de delincuencia y violencia que el continente arrastra los últimos años.</p>
<p>El Salvador se sumaba a los países en los que se había degradado notablemente la democracia (Martí &amp; Rodriguez, 2024). Sabido es la disminución de la calidad democrática en dicho país, por las fuertes políticas impuestas. Es por eso, que es importante visualizar el impacto de dichas políticas en la percepción de seguridad y los niveles de aprobación del gobierno de Nayib Bukele.</p>
<p>La percepción de seguridad, constituye un problema social real, que evidencia las consecuencias personales y sociales. Esto puede traer un problema por modificación de conductas hacia la violencia, aislamiento, abandono y degradación de espacios públicos, estigmatización de grupos considerados peligrosos y una demanda social de mayor seguridad que recae en el poder político (Fuentealba et al., 2016).</p>
<p>Por seguridad se entiende como un estado o condición socio institucional subjetivo, influenciado por experiencias previas, factores sociales, culturales, en el cual se puede hacer libre ejercicio de derechos individuales y colectivos (Guerrero &amp; Ramírez, 2017).</p>
<p>La aprobación del poder ejecutivo actual, centrada en la confianza depositada en Nayib Bukele, puede entenderse como: la confianza se convierte en una condición necesaria para la formación de instituciones, pues su ausencia promueve el conflicto social, ya que las instituciones tienen la función de reducir el grado de incertidumbre que genera la complejidad social (Luhmann, 1996 citado por Beramendi, 2016). La confianza institucional depende de la percepción de buen desempeño y capacidad para satisfacer las demandas ciudadanas. El respaldo a Bukele refleja la percepción de eficacia en su gestión y atención a las expectativas de la población.</p>
<p>Para esta investigación se desarrollaron tres hipótesis, en primer lugar, se espera que a mayor percepción de seguridad en la actualidad, mayor aprobación de Bukele (H1). En segundo lugar, se espera que a mayor noción de que mejoró la seguridad, mayor aprobación de Bukele (H2). Y por último, se espera que exista una asociación entre la sensación de seguridad en la actualidad y la confianza en que el gobierno nacional está haciendo lo correcto (H3).</p>
</section>
<section id="metodología" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="metodología"><span class="header-section-number">2</span> Metodología</h2>
<section id="datos" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="datos"><span class="header-section-number">2.1</span> Datos</h3>
<p>Para este trabajo, se utilizaron los datos de Latin American Political Opinion Project (LAPOP) [Proyecto de Opinión Pública Latinoamericano] de AmericasBarometer del año 2023, una encuesta que mida las actitudes, evaluaciones, experiencias y comportamientos en adultos en distintos países de América Latina, en temas como la economía, la capacidad estatal, confianza en instituciones, valores individuales, corrupción, seguridad, y más (Vanderbilt University, s.f). Se utilizaron los datos específicos de El Salvador, del año 2023. La encuesta se llevó a cabo entre Julio y Agosto 2023, en modalidad presencial, y tiene un tamaño muestral de 1.516 personas.</p>
</section>
<section id="variables" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="variables"><span class="header-section-number">2.2</span> Variables</h3>
<p>La variable “m1”, renombrada “aprob_gob” en el procesamiento de los datos, mide la evaluación del encuestado del trabajo realizado por el presidente Nayib Bukele. Es una variable ordinal tipo Likert de 1 al 5, que fue recodificada, para que valores mayores indiquen una mejor evaluación. En la escala recodificada, 1 es “Muy malo (pésimo)” y 5 es “Muy bueno”.</p>
<p>La variable “anestg”, renombrada “gob_correct”, mide el nivel de confianza en que el gobierno nacional hace lo correcto. Es una variable categórica ordinal que va de 1 a 4, que fue recodificada, para que valores mayores indiquen mayor confianza. En la variable recodificada, 1 es “Nada” y 4 es “Mucho”. La variable b21a, renombrada “conf_pres”, mide el nivel de confianza en el presidente. Es una escala ordinal que va de 1 a 7, donde 1 es “Nada” y 7 es “Mucho”.</p>
<p>La variable “aoj11”, renombrada “sensa_seg”, mide la percepción de seguridad en la comunidad/colonia frente a la posibilidad de ser víctima de asalto o robo. Es una variable categórica ordinal que va de 1 a 4, que fue recodificada, para que valores mayores indiquen mayor percepción de seguridad. En la variable recodificada, 1 es “Muy inseguro(a)”, y 4 es “Muy seguro(a)”.</p>
<p>La variable “soe1”, renombrada “seg_pais”, evalúa si, según el/la encuestado/a, la situación actual de seguridad del país está mejor, igual, o peor que antes del régimen de excepción. Es una variable ordinal que va de 1 a 3, donde 1 es “Mejor”, 2 es “Igual”, y 3 es “Peor”. Fue recodificada para que un valor más alto indique una apreciación positiva. En la variable recodificada, 1 es “Peor” y 3 es “Mejor”.</p>
<p>La variable “soe2”, renombrada “seg_com”, evalúa si, según el/la encuestado/a, la situación actual de seguridad en su comunidad o colonia está mejor, igual, o peor que antes del régimen de excepción. Es una variable ordinal que va de 1 a 3, con los mismos valores que “soe1”. Fue recodificada para que un valor más alto indique una apreciación positiva. En la variable recodificada, 1 es “Peor” y 3 es “Mejor”.</p>
<p>La variable “soe3”, renombrada “seg_fam”, evalúa si, según el/la encuestado/a, la situación actual de seguridad en su familia está mejor, igual, o peor que antes del régimen de excepción. Es una variable ordinal que va de 1 a 3, con los mismos valores que “soe1”. Fue recodificada para que un valor más alto indique una apreciación positiva. En la variable recodificada, 1 es “Peor” y 3 es “Mejor”.</p>
<p>Se crearon dos variables nuevas. Primero, un índice de aprobación del poder ejecutivo actual, de Nayib Bukele, (“indice_gob”), reuniendo las variables “aprob_gob”, “gob_correct”, y “conf_pres”; considerando que las variables miden distintas dimensiones de la aprobación del poder ejecutivo. Dado que las variables tienen todas niveles de medición distintos, se recodificaron de modo que todas quedaron con 3 niveles, donde 1 indica menor presencia del atributo o una apreciación negativa, y 3 indica mayor presencia del atributo o una apreciación positiva. Se promediaron las 3 variables (con igual ponderación), creando un índice (continuo) que va de 1 a 3, donde valores más cercanos a 1 indican menor aprobación del poder ejecutivo, y más cercanos a 3 indican mayor aprobación.</p>
<p>Además, se creó una escala con las variables “seg_pais”, ” seg_com”, y “seg_fam”, a modo de unir las tres variables que preguntan sobre la percepción de mejoría de la situación de seguridad después del régimen de excepción (“escala_seg”). Se promediaron las tres variables, generando una escala continua que va del 1 al 3, donde 1 es “Peor” y 3 es “Mejor”, y los valores intermedios indican mayor proximidad a una u otra apreciación.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>descriptivos <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(aprob_gob, gob_correct, conf_pres, sensa_seg, seg_pais, seg_com, seg_fam, indice_gob, escala_seg)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>tab1<span class="ot">&lt;-</span>psych<span class="sc">::</span><span class="fu">describe</span>(descriptivos) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>tab1</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-1" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
aprob_gob
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
4.141208
</td>
<td style="text-align:right;">
0.9106214
</td>
<td style="text-align:right;">
4.000000
</td>
<td style="text-align:right;">
4.240034
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
-0.9990568
</td>
<td style="text-align:right;">
0.9719199
</td>
<td style="text-align:right;">
0.0237267
</td>
</tr>
<tr>
<td style="text-align:left;">
gob_correct
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
3.197556
</td>
<td style="text-align:right;">
0.8689665
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
3.296014
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
-0.7522998
</td>
<td style="text-align:right;">
-0.4078810
</td>
<td style="text-align:right;">
0.0226413
</td>
</tr>
<tr>
<td style="text-align:left;">
conf_pres
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
5.608282
</td>
<td style="text-align:right;">
1.7521297
</td>
<td style="text-align:right;">
6.000000
</td>
<td style="text-align:right;">
5.940628
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
-1.2868478
</td>
<td style="text-align:right;">
0.7043844
</td>
<td style="text-align:right;">
0.0456525
</td>
</tr>
<tr>
<td style="text-align:left;">
sensa_seg
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
3.261371
</td>
<td style="text-align:right;">
0.8606636
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
3.399491
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
-1.0779445
</td>
<td style="text-align:right;">
0.4983904
</td>
<td style="text-align:right;">
0.0224250
</td>
</tr>
<tr>
<td style="text-align:left;">
seg_pais
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.880516
</td>
<td style="text-align:right;">
0.4129122
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-3.5827272
</td>
<td style="text-align:right;">
12.1484279
</td>
<td style="text-align:right;">
0.0107586
</td>
</tr>
<tr>
<td style="text-align:left;">
seg_com
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.832315
</td>
<td style="text-align:right;">
0.4183152
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
2.937235
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-2.4714162
</td>
<td style="text-align:right;">
5.5943585
</td>
<td style="text-align:right;">
0.0108994
</td>
</tr>
<tr>
<td style="text-align:left;">
seg_fam
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.803123
</td>
<td style="text-align:right;">
0.4506228
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
2.906701
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-2.2273692
</td>
<td style="text-align:right;">
4.3076943
</td>
<td style="text-align:right;">
0.0117412
</td>
</tr>
<tr>
<td style="text-align:left;">
indice_gob
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.514370
</td>
<td style="text-align:right;">
0.5405865
</td>
<td style="text-align:right;">
2.666667
</td>
<td style="text-align:right;">
2.595985
</td>
<td style="text-align:right;">
0.4942
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-0.9992058
</td>
<td style="text-align:right;">
0.1546949
</td>
<td style="text-align:right;">
0.0140852
</td>
</tr>
<tr>
<td style="text-align:left;">
escala_seg
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.838651
</td>
<td style="text-align:right;">
0.3531128
</td>
<td style="text-align:right;">
3.000000
</td>
<td style="text-align:right;">
2.928188
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-2.6664590
</td>
<td style="text-align:right;">
7.7113826
</td>
<td style="text-align:right;">
0.0092005
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Tabla: Resumen de descriptivos de todas las variables
</figcaption>
</figure>
</div>
</div>
</section>
<section id="métodos" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="métodos"><span class="header-section-number">2.3</span> Métodos</h3>
<p>Para evaluar Hipótesis 1, se calculó el coeficiente de correlación de Spearman entre las variables “sensa_seg” e “indice_gob”, para evaluar si existe una correlación estadísticamente significativa entre percepción de seguridad actual y aprobación al poder ejecutivo.</p>
<p>Para la Hipótesis 2, se calculó el coeficiente de correlación de Spearman entre las variables “escala_seg” e “indice_gob”, para evaluar si existe una asociación estadísticamente significativa entre la percepción de mejoría de la seguridad y aprobación al poder ejecutivo.</p>
<p>En el caso de Hipótesis 3, se usó la prueba de Chi-Cuadrado (X2) entre las variables “sensa_seg” y “gob_correct”, para evaluar si existe una asociación estadísticamente significativa entre la percepción de seguridad actual y el nivel de confianza en que el gobierno nacional está haciendo lo correcto.</p>
<p>Los análisis estadísticos para contraste de hipótesis, y análisis descriptivo se realizaron en el software RStudio.</p>
</section>
</section>
<section id="análisis" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="análisis"><span class="header-section-number">3</span> Análisis</h2>
<section id="análisis-descriptivo" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="análisis-descriptivo"><span class="header-section-number">3.1</span> Análisis descriptivo</h3>
<section id="escala-de-percepción-de-mejoría-de-la-seguridad" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="escala-de-percepción-de-mejoría-de-la-seguridad"><span class="header-section-number">3.1.1</span> Escala de percepción de mejoría de la seguridad</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tab2<span class="ot">&lt;-</span>psych<span class="sc">::</span><span class="fu">describe</span>(data<span class="sc">$</span>escala_seg) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>tab2</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-2" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.838651
</td>
<td style="text-align:right;">
0.3531128
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2.928188
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-2.666459
</td>
<td style="text-align:right;">
7.711383
</td>
<td style="text-align:right;">
0.0092005
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Tabla de descriptivos: de escala de seguridad
</figcaption>
</figure>
</div>
</div>
<p>Como se presenta la <a href="#fig-2" class="quarto-xref">Figura&nbsp;2</a>, en la escala de percepción de mejoría de la seguridad (después del régimen de excepción) el promedio es de 2.838651. Dado que el mínimo es 1, y el máximo es 3, se deduce de la media que mayoritariamente las personas consideran que la situación de seguridad ha mejorado. La mediana es 3, lo que indica que al menos el 50% de las personas encuestadas opinan que la seguridad ha mejorado.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>diagrama3<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data =</span> data, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> escala_seg)) <span class="sc">+</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"darkred"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>)  <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Diagrama de densidad: Escala de seguridad"</span>, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Seguridad"</span>, </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia en base a LAPOP 2023."</span>) </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>diagrama3</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/figure-html/fig-3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Diagrama de densidad: Escala de seguridad
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="índice-de-aprobación-del-poder-ejecutivo" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="índice-de-aprobación-del-poder-ejecutivo"><span class="header-section-number">3.1.2</span> Índice de aprobación del poder ejecutivo</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tab4<span class="ot">&lt;-</span>psych<span class="sc">::</span><span class="fu">describe</span>(data<span class="sc">$</span>indice_gob) <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>tab4</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-4" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
2.51437
</td>
<td style="text-align:right;">
0.5405865
</td>
<td style="text-align:right;">
2.666667
</td>
<td style="text-align:right;">
2.595985
</td>
<td style="text-align:right;">
0.4942
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
-0.9992058
</td>
<td style="text-align:right;">
0.1546949
</td>
<td style="text-align:right;">
0.0140852
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Tabla de descriptivos: índice de gobierno
</figcaption>
</figure>
</div>
</div>
<p>En el índice de aprobación del poder ejecutivo la <a href="#fig-4" class="quarto-xref">Figura&nbsp;4</a> presenta que el promedio es 2.51437, y la mediana es 2.66. Dado que el mínimo es 1 y el máximo 3, se deduce de la media y la mediana que hay una alta aprobación del poder ejecutivo, pero menos transversal que la percepción de mejoría de la seguridad.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>diagrama5<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data =</span> data, </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> indice_gob)) <span class="sc">+</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"darkred"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>)  <span class="sc">+</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Diagrama de densidad: Índice de aprobación del poder ejecutivo actual"</span>, </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Aprobación del poder ejecutivo actual"</span>, </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente:  Elaboración propia en base a LAPOP 2023."</span>) </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>diagrama5</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-5" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/figure-html/fig-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Diagrama de densidad: Índice de aprobación del poder ejecutivo actual
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="percepción-de-seguridad-actual" class="level4" data-number="3.1.3">
<h4 data-number="3.1.3" class="anchored" data-anchor-id="percepción-de-seguridad-actual"><span class="header-section-number">3.1.3</span> Percepción de seguridad actual:</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tab6<span class="ot">&lt;-</span>psych<span class="sc">::</span><span class="fu">describe</span>(data<span class="sc">$</span>sensa_seg) <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>tab6</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="fig-6" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
vars
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
median
</th>
<th style="text-align:right;">
trimmed
</th>
<th style="text-align:right;">
mad
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
range
</th>
<th style="text-align:right;">
skew
</th>
<th style="text-align:right;">
kurtosis
</th>
<th style="text-align:right;">
se
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1473
</td>
<td style="text-align:right;">
3.261371
</td>
<td style="text-align:right;">
0.8606636
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3.399491
</td>
<td style="text-align:right;">
1.4826
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
-1.077945
</td>
<td style="text-align:right;">
0.4983904
</td>
<td style="text-align:right;">
0.022425
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Tabla de descriptivos: Percepción de seguridad
</figcaption>
</figure>
</div>
</div>
<p>La variable de percepción de seguridad actual “sensa_seg”, como se muestra en la <a href="#fig-6" class="quarto-xref">Figura&nbsp;6</a>, tiene un total de 1473 de observaciones válidas, que varían entre el 1 y el 4. La media es 3.2614, con una mediana de 3, lo que sugiere una distribución centrada cerca de este valor, y una percepción de seguridad actual mediana-alta.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>grafico7<span class="ot">&lt;-</span><span class="fu">ggplot</span>(<span class="at">data =</span> data, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> sensa_seg)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"#5D3766"</span>) <span class="sc">+</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">750</span>)) <span class="sc">+</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> ..count..), <span class="at">stat =</span> <span class="st">"count"</span>, <span class="at">vjust =</span> <span class="dv">2</span>, <span class="at">colour =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Grafico de barras: Percepción de seguridad actual"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Cantidad"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de seguridad actual (Siendo 1 'Muy inseguro' y 4 'Muy seguro)'"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Fuente:  Elaboración propia en base a LAPOP 2023."</span>) </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>grafico7</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-7" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/figure-html/fig-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Grafico de barras: Percepción de seguridad
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análisis-estadístico-bivariado" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="análisis-estadístico-bivariado"><span class="header-section-number">3.2</span> Análisis estadístico bivariado</h3>
<section id="hipótesis-1" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="hipótesis-1"><span class="header-section-number">3.2.1</span> Hipótesis 1</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>grafico8 <span class="ot">&lt;-</span> sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> sensa_seg,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> indice_gob, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.line =</span> <span class="st">"lm"</span>,      </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.ci =</span> <span class="cn">FALSE</span>,     </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">dot.size =</span> <span class="dv">1</span> </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Asociación entre percepción de seguridad actual, y nivel de aprobación del poder ejecutivo"</span>, </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Aprobación del poder ejecutivo"</span>, </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de seguridad actual"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia en base a LAPOP 2023."</span>) <span class="sc">+</span>  </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>grafico8</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-8" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/figure-html/fig-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-8-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Asociación entre percepción de seguridad actual, y nivel de aprobación del poder ejecutivo
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="fig-9" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Correlación
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:left;">
p-value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
Método
</th>
<th style="text-align:left;">
Alternativa
</th>
<th style="text-align:left;">
95% IC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.2238
</td>
<td style="text-align:right;">
8.8086
</td>
<td style="text-align:left;">
&lt; 0.001***
</td>
<td style="text-align:right;">
1471
</td>
<td style="text-align:left;">
Pearson’s product-moment correlation
</td>
<td style="text-align:left;">
two.sided
</td>
<td style="text-align:left;">
[0.17,0.27]
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-9-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Resultados del cálculo de la correlación de Spearman para H1
</figcaption>
</figure>
</div>
</div>
<p>H0 : La relación entre la percepción de seguridad actual (“sensa_seg”) y el nivel aprobación al poder ejecutivo (indice_gob) es nula o negativa.</p>
<p>HA: En medida en que la percepción de seguridad actual (“sensa_seg”) es mayor, el nivel aprobación al poder ejecutivo (indice_gob) es mayor.</p>
<p>En la <a href="#fig-8" class="quarto-xref">Figura&nbsp;8</a> se muestra la correlación de las variables “sensa_seg” y “indice_gob”. Se observa que la concentración de casos aumenta hacia los valores mayores de percepción de seguridad; y al mismo tiempo hacia más altos de aprobación del poder ejecutivo, pero con menor intensidad. Además, la línea de regresión muestra una correlación ascendente y de moderada pendiente. Para calcular la correlación, se calculó el coeficiente de correlación de Spearman. Se puede apreciar en la <a href="#fig-9" class="quarto-xref">Figura&nbsp;9</a> que según los criterios de Cohen la correlación es pequeña, y es positiva, y estadísticamente significativa (<em>r</em> =0.224, p&lt;0.001), lo que permite rechazar la hipótesis nula H0. Con un 99.9% de confianza se rechaza la hipótesis nula H0 y podemos decir que existe evidencia a favor de la hipótesis alternativa HA, de que a mayor percepción de seguridad en la actualidad, mayor la aprobación del poder ejecutivo. &nbsp;</p>
</section>
<section id="hipótesis-2" class="level4" data-number="3.2.2">
<h4 data-number="3.2.2" class="anchored" data-anchor-id="hipótesis-2"><span class="header-section-number">3.2.2</span> Hipótesis 2</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>grafico9 <span class="ot">&lt;-</span> sjPlot<span class="sc">::</span><span class="fu">plot_scatter</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> escala_seg,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> indice_gob, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.line =</span> <span class="st">"lm"</span>,     </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.ci =</span> <span class="cn">FALSE</span>,       </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">dot.size =</span> <span class="dv">2</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span><span class="st">"Asociación entre percepcion de mejoría de la seguridad y nivel de aprobación al poder ejecutivo"</span>, </span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Nivel de aprobación al poder ejecutivo"</span>, </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Percepción de mejoría de la seguridad"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia en base a LAPOP 2023."</span>) <span class="sc">+</span> </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>grafico9</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-10" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/figure-html/fig-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;10: Asociación entre percepción de mejoría de seguridad después del estado de excepción y nivel de aprobación al poder ejecutivo
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="fig-11" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Correlación
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:left;">
p-value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
Método
</th>
<th style="text-align:left;">
Alternativa
</th>
<th style="text-align:left;">
95% IC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.4165
</td>
<td style="text-align:right;">
17.57
</td>
<td style="text-align:left;">
&lt; 0.001***
</td>
<td style="text-align:right;">
1471
</td>
<td style="text-align:left;">
Pearson’s product-moment correlation
</td>
<td style="text-align:left;">
two.sided
</td>
<td style="text-align:left;">
[0.37,0.46]
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-11-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11: Resultados del cálculo de la correlación de Spearman para H2
</figcaption>
</figure>
</div>
</div>
<p>H0 : La relación entre percepción de mejoría de la seguridad después del régimen de excepción (“escala_seg”) y la aprobación al poder ejecutivo (indice_gob) es nula o negativa.</p>
<p>HA: En medida en que la sensación de mejoría de la seguridad después del régimen de excepción (“escala_seg”) es mayor, la aprobación al poder ejecutivo (indice_gob) es mayor.</p>
<p>En la <a href="#fig-10" class="quarto-xref">Figura&nbsp;10</a> se muestra la correlación entre las variable “escala_seg” e “indice_gob”. Se observa que una concentración de casos que aumenta fuertemente hacia los valores mayores de percepción de mejoría de la seguridad; y en menor medida, también aumenta hacia valores mayores de aprobación al poder ejecutivo. Además, la línea negra muestra una correlación ascendente y de fuerte pendiente. Para calcular la correlación, se calculó el coeficiente de correlación de Spearman. Se puede apreciar en la <a href="#fig-11" class="quarto-xref">Figura&nbsp;11</a> que según los criterios de Cohen la correlación es moderada, y es positiva y estadísticamente significativa (<em>r</em> =0.4165, p&lt;0.001), lo que permite rechazar la hipótesis nula H0. Con un 99.9 de confianza se rechaza la hipótesis nula H0, con evidencia a favor de la hipótesis alternativa HA, de que a mayor percepción de mejoría de la seguridad, mayor es la aprobación al poder ejecutivo.</p>
</section>
<section id="hipótesis-3" class="level4" data-number="3.2.3">
<h4 data-number="3.2.3" class="anchored" data-anchor-id="hipótesis-3"><span class="header-section-number">3.2.3</span> Hipótesis 3</h4>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">table</span>(data<span class="sc">$</span>sensa_seg, data<span class="sc">$</span>gob_correct)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>tabla_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">as.table</span>(tabla))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Heatmap</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>grafico10<span class="ot">&lt;-</span><span class="fu">ggplot</span>(tabla_df, <span class="fu">aes</span>(Var1, Var2, <span class="at">fill =</span> Freq)) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"pink"</span>, <span class="at">high =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Sensación de Seguridad"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Confianza en el Gobierno"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Frecuencia"</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>grafico10</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-12" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="LAPOP_quarto_TRABAJO_CORRELACIONAL_files/figure-html/fig-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;12: Asociación entre percepción de mejoría de seguridad después del estado de excepción y la confianza en que el gobierno hace lo correcto
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="fig-13" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Prueba de Chi-cuadrado entre la sensación de seguridad actual y la confianza en que el gobierno nacional hace lo correcto
</caption>
<thead>
<tr>
<th style="text-align:right;">
X2
</th>
<th style="text-align:left;">
p-value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
Método
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
151.94
</td>
<td style="text-align:left;">
&lt; 0.001***
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;width: 8cm; ">
Pearson’s Chi-squared test
</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;13: Resultados de la prueba de Chi-cuadrado (X2) para H3
</figcaption>
</figure>
</div>
</div>
<p>H0: No existe asociación entre la sensación de seguridad actual (“sensa_seg”) y el nivel de confianza en que el gobierno nacional hace lo correcto (“conf_gob”).</p>
<p>HA: Existe una asociación entre la sensación de seguridad actual (“sensa_seg”) y el nivel de confianza en que el gobierno nacional hace lo correcto(“conf_gob”).&nbsp;</p>
<p>En la <a href="#fig-12" class="quarto-xref">Figura&nbsp;12</a> se muestra la asociación de las variables “sensa_seg” y “conf_gob”. Se observa que la frecuencia de casos aumenta significativamente hacia mayores valores en la sensación de seguridad actual, y en menor medida, hacia mayores niveles de confianza en que el gobierno nacional hace lo correcto. Se aplicó la prueba de Chi-cuadrado (X2), como se puede apreciar en la <a href="#fig-13" class="quarto-xref">Figura&nbsp;13</a> nos entregó un valor X2 = 151.94, para 9 grados de libertad, y un valor <em>p</em>&lt;0.001. Además, se calculó el V de Cramer, que señala el tamaño del efecto; el cual sería pequeño en este caso, con <em>V</em> = 0.185. Con 9 grados de libertad, se observa que el X2 empírico es mayor al X2, crítico. Por lo tanto, tenemos una asociación pequeña y estadísticamente significativa. Con un 99.9% de confianza, se rechaza la hipótesis nula H0 de no asociación entre las variables (X2 = 151.94, <em>df</em> = 9, <em>V</em> = 0.185, <em>p</em>&lt;0.001).</p>
</section>
</section>
</section>
<section id="conclusiones" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">4</span> Conclusiones</h2>
<p>El análisis exploró la relación entre la sensación de seguridad actual, la percepción de mejora de seguridad y la aprobación del poder ejecutivo en las personas de El Salvador. El análisis fue producido a base de la encuesta LAPOP del 2023 desarrollada en El Salvador. Las correlaciones entre las variables resultaron ser moderadas, positivas y significativas estadísticamente, por lo que se observa que efectivamente existe una relación entre la seguridad y la confianza en el poder ejecutivo en El Salvador, aunque esta pareciera no ser tan fuerte. Como limitaciones dentro del presente trabajo, se observa el hecho de que la legitimidad en el gobierno no se relaciona exclusivamente con la sensación y percepción de seguridad, por lo que el análisis producido no resulta suficiente para comprender la compleja situación en El Salvador. Otra limitación se encuentra en el tipo de datos utilizados, ya que al ser una encuesta de opinión pública, la información obtenida de esta puede estar sesgada, resultando en datos que tal vez no representan de la forma más adecuada la realidad en El Salvador. Por otro lado, resultaría interesante analizar qué otros factores se relacionan con la legitimidad de Nayib Bukele, si es que los hay. Además de esto, podrían realizarse comparaciones con otros años y con otros países de la región en los que se haya realizado la encuesta LAPOP.</p>
</section>
<section id="bibliografia" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="bibliografia"><span class="header-section-number">5</span> Bibliografía</h2>
<p>Beramendi, M., Delfino G. &amp; Zubieta E. (2016) Confianza Institucional y Social: Una Relación Insoslayable. <em>Acta de investigación psicológica, 6</em>(1), 2289 - 2301. <a href="https://www.redalyc.org/articulo.oa?id=358945983005" class="uri">https://www.redalyc.org/articulo.oa?id=358945983005</a></p>
<p>Duque y Moreno (2024). <em>Análisis de la efectividad de las estrategias de seguridad en la reducción de la violencia en el Salvador: Administración de Najib Bukele (2022-2023)</em> [Universidad Tecnológica ECOTEC]. <a href="https://repositorio.ecotec.edu.ec/handle/123456789/1157" class="uri">https://repositorio.ecotec.edu.ec/handle/123456789/1157</a></p>
<p>Fuentealba, P. Rojas, J. y Barriga, O. (2016). Diferencias en la percepción de inseguridad a nivel cognitivo y emocional de acuerdo al perfil sociodemográfico y político: Estudio del Gran Concepción, Chile. <em>Política criminal, 11</em>(22), 620-655. <a href="https://dx.doi.org/10.4067/S0718-33992016000200008" class="uri">https://dx.doi.org/10.4067/S0718-33992016000200008</a></p>
<p>Guerrero, B. M., y Ramírez, I. S. (2017). <em>Informe final de proyecto de título para optar al grado académico de licenciado en trabajo social y el título profesional de trabajador social.</em> [Tesis de pregrado, Universidad de Valparaíso] <a href="http://repositoriobibliotecas.uv.cl/handle/uvscl/5507" class="uri">http://repositoriobibliotecas.uv.cl/handle/uvscl/5507</a></p>
<p>Martí Puig, S., y Rodríguez Suárez, D. (2024). Nayib Bukele, seguridad a cambio de democracia. <em>Más Poder Local</em>, (56), 141-154. <a href="https://doi.org/10.56151/maspoderlocal.231" class="uri">https://doi.org/10.56151/maspoderlocal.231</a></p>
<p>Sanchez, M. (2024). De las políticas de mano dura a la política del estado de excepción en El Salvador. <em>ECA: Estudios Centroamericanos, 79</em>(776), 13-46. <a href="https://doi.org/10.51378/eca.v79i776.8198" class="uri">https://doi.org/10.51378/eca.v79i776.8198</a></p>
<p>Vanderbilt University (s.f.) <em>AmericasBarometer</em>. <a href="https://www.vanderbilt.edu/lapop/about-americasbarometer.php" class="uri">https://www.vanderbilt.edu/lapop/about-americasbarometer.php</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>