<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Pablo Guzmán, Antonia Hernández, Valeria Reyes, Carla Roa y Daniel Thumala.">
<meta name="description" content="Estadística Correlacional - Inferencia, asociación y reporte">

<title>Estudio de la financiarización de los hogares a través del uso de criptomonedas por estrato de ingreso y valor total de activos financieros – Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../">
<link href="../../../..//files/logo-correlacional-transp.png" rel="icon" type="image/png">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="Estudio de la financiarización de los hogares a través del uso de criptomonedas por estrato de ingreso y valor total de activos financieros – Estadística Correlacional">
<meta property="og:description" content="">
<meta property="og:image" content="https://correlacional.netlify.app/files/logo-correlacional.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
<meta property="og:image:height" content="533">
<meta property="og:image:width" content="466">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../assignment/index.html"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../trabajos.html"> 
<span class="menu-text">Trabajos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#resumen" id="toc-resumen" class="nav-link active" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología">Metodología</a>
  <ul class="collapse">
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  <li><a href="#contraste-de-hipótesis" id="toc-contraste-de-hipótesis" class="nav-link" data-scroll-target="#contraste-de-hipótesis">Contraste de hipótesis</a></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis">Análisis</a></li>
  <li><a href="#análisis-bivariado" id="toc-análisis-bivariado" class="nav-link" data-scroll-target="#análisis-bivariado">Análisis Bivariado</a></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión">Discusión</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">Conclusiones</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía">Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estudio de la financiarización de los hogares a través del uso de criptomonedas por estrato de ingreso y valor total de activos financieros</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Pablo Guzmán, Antonia Hernández, Valeria Reyes, Carla Roa y Daniel Thumala. </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="resumen" class="level1">
<h1>Resumen</h1>
<p>El presente informe se enmarca en el estudio de la financiarización del comportamiento económico en los hogares de Chile, un fenómeno que implica una creciente influencia de los mercados financieros en las decisiones económicas de los agentes. Concretamente, mediante análisis bivariado a partir de los datos de la Encuesta Financiera de Hogares de 2021, se busca una relación entre el uso de criptomonedas con dos variables: el estrato de ingresos de los hogares y el valor de los activos financieros. De esta forma, se ahonda en la relación entre características socioeconómicas y el uso de tecnologías financieras digitales. Los resultados muestran que existen asociaciones estadísticamente significativas entre el uso de criptomonedas y los factores socioeconómicos, pese a la débil magnitud de la fuerza de estas asociaciones, lo cual describe un escenario débilmente financiarizado en entornos digitales. A su vez se observa una asociación positiva y moderada entre el valor total de activos financieros y el estrato de nivel de ingreso, que indica que los hogares de mayor estrato de nivel de ingreso tienden a tener un mayor valor total de activos financieros y por ende en estos hogares podría haber una prevalencia de conductas financiarizadas más “tradicionales” en contraste con las nuevas prácticas digitales de financiarización.</p>
</section>
<section id="introducción" class="level1">
<h1>Introducción</h1>
<p>La financiarización puede ser entendida como un proceso de cambio en la estructura económico social en donde el sistema financiero se hace cada vez más autónomo, separándose de la economía productiva y pasando a tener como fin la producción de dinero, de manera que los mercados, actores y valores financieros van adquiriendo una creciente importancia para los distintos agentes económicos y sociales (Zwan, 2014). Este fenómeno afecta tanto a las economías de las sociedades, como a las empresas, hogares e individuos, los cuales pueden mostrar comportamientos financiarizados que indican una determinada percepción del riesgo, y valores en consonancia con la inversión, el endeudamiento y las finanzas. Dentro de la literatura sobre financiarización, los hogares se consideran en el nivel “micro” de análisis, también denominado “financiarización de la vida cotidiana”, pues la lógica financiera se integra en la vida cotidiana de los individuos de distintas formas, incorporando valores financieros dentro del hogar (Abalde, et al., 2024).</p>
<p>Como indica Marambio (2018), en Chile, la relación de gran parte de la población con los mercados financieros tuvo un punto de inflexión en la década de los 80, donde se desregula el sistema financiero, surgiendo nuevos prestamistas institucionales y una expansión crediticia. Para la década de los 90 esto derivó en una “democratización del crédito”, lo que implica la inclusión financiera y bancarización de las clases populares, esto es catalogado por el autor como una financiarización del consumo que persiste hasta hoy, donde se valoriza la imagen del ciudadano consumidor que se endeuda responsablemente. Dentro de este marco general de financiarización, la vida cotidiana ha sido fuertemente afectada, pues el ámbito doméstico se expande al financiero y las acciones económicas cotidianas están impregnadas de redes financieras (Langley, 2008).</p>
<p>Como señalan Abalde et. al.&nbsp;(2024), existe diversa literatura sobre este fenómeno pero escasos estudios que midan la conducta financiarizada. Las variables a utilizar se relacionan con el comportamiento financiero, el manejo de dinero, y la actitud o percepción hacia el riesgo. El presente estudio, busca medir la conducta financiarizada en los hogares mediante el uso de criptomonedas.</p>
<p>Las criptomonedas son activos digitales que, al constituirse como tecnologías financieras emergentes, plantean una nueva forma de relacionarse con los mercados financieros, permitiendo a los individuos participar directamente en mercados digitales sin bancos como intermediarios (Nakamoto, 2008). En el presente trabajo se entiende el uso de criptomonedas como una innovadora forma de conducta financiarizada a través de medios digitales, la cual permite inversiones minoristas, pues las criptomonedas han permitido a más personas involucrarse en actividades financieras que antes estaban reservadas a grandes inversionistas, lo que puede profundizar la financiarización en los hogares. (Pereira 2024; Jagati, 2023; Financieras, sf).</p>
<p>De esta forma, enmarcado en el estudio de la financiarización de los hogares, se pretende analizar los factores que afectan el uso de tarjetas con criptomonedas, lo cual se entiende como una manifestación de la financiarización de la vida cotidiana en entornos digitales, para lo cual se presenta como objetivo principal: identificar factores socioeconómicos que se relacionan con el uso de criptomonedas, considerando estrato de nivel de ingresos, y valor total de los activos financieros por hogar.</p>
<p>Como primera hipótesis (H1) se plantea que existiría asociación positiva entre el uso de tarjetas con criptomonedas en el hogar y los hogares de estratos de nivel de ingresos más altos. Por ende como hipótesis nula (H0) se considera que existiría una asociación negativa entre el uso de tarjetas con criptomonedas y los hogares de estratos de nivel de ingresos más altos.</p>
<p>La segunda hipótesis (H2) consiste en que existe una asociación positiva entre el uso de tarjetas con criptomonedas en el hogar y el valor total de activos financieros. Como hipótesis nula (H0) se plantea que existiría asociación negativa entre el uso de tarjetas con criptomonedas en el hogar y el valor total de activos financieros.</p>
<p>Finalmente, como tercera hipótesis (H3) se sostiene que existe una asociación positiva entre los hogares de estratos de nivel de ingreso más altos y el valor total de activos financieros. La hipótesis nula (H0) es que existiría asociación negativa entre los estratos de nivel de ingreso y el valor total de activos financieros.</p>
</section>
<section id="metodología" class="level1">
<h1>Metodología</h1>
<p>La base de datos utilizada en esta investigación corresponde a la base imputada de la Encuesta Financiera de Hogares (EFH), realizada por el Banco Central de Chile el año 2021, la cual proporciona información sobre ingresos, gastos y situación financiera de los hogares, junto con características demográficas y socioeconómicas (EFH, 2022). Dicha encuesta define “hogar” como: (1) un grupo de personas que viven en una misma vivienda y comparten un presupuesto de alimentación, o (2) una persona que vive en una vivienda y se provee de su propia alimentación. La encuesta recoge información a través de 114 variables, de las cuales se seleccionaron tres.</p>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables">Variables</h2>
<p>Como variable dependiente se consideró el uso de tarjetas con criptomonedas (u_tcripto). Esta variable mide si algún miembro del hogar utiliza tarjetas con criptomonedas (por ejemplo, bitcoin o chaucha) como medio de pago. Es una variable dicotómica que adopta los valores: 1 = Sí; 0 = No.&nbsp;En cuanto a las variables independientes, se seleccionan dos, las cuales corresponden al valor total de los activos financieros (act_fin) y al estrato de ingreso efectivo del hogar (estrato). La variable referente al valor total de activos financieros corresponde a una variable continua, la cual representa la suma de los montos totales invertidos por el hogar en instrumentos de renta fija y variable. Por otro lado, la variable de estrato de ingreso efectivo del hogar, corresponde a una variable categórica ordinal, la cual identifica el estrato de ingreso al que pertenece el hogar, designados en tres categorías según los deciles del ingreso total. La categoría “1” comprende los deciles del 1 al 5, la categoría “2” comprende los deciles 6 al 8 y la categoría “3” comprende los deciles 9 y 10. Mediante estas variables se pretende analizar las relaciones entre el uso de tarjetas con criptomonedas en los hogares y sus características financieras y económicas, de manera que se pueda caracterizar qué tipo de hogares en Chile son los que más utilizan tarjetas con criptomonedas –según las variables mencionadas–, presentando un comportamiento financiarizado a través de medios digitales.</p>
</section>
<section id="contraste-de-hipótesis" class="level2">
<h2 class="anchored" data-anchor-id="contraste-de-hipótesis">Contraste de hipótesis</h2>
<p>Para el contraste de hipótesis se realizó un análisis entre la variable dependiente “Uso de tarjetas con criptomonedas” (u_tcripto), la cual es de tipo categórica dicotómica, y las variables independientes, siendo “Estrato de ingreso efectivo del hogar” (estrato) una de tipo categórica y la variable “Valor total de los activos financieros” una de tipo continua (act_fin).</p>
<p>Para la primera hipótesis, que consiste en la existencia de una asociación positiva entre el uso de de tarjetas con criptomonedas en el hogar y los estratos altos de ingreso efectivo del hogar, se aplica la prueba Chi cuadrado, técnica estadística que permite identificar si existe una relación significativa entre el estrato de nivel de ingreso (estrato) y el uso de tarjetas con criptomonedas (u_tcripto), dos variables categóricas. Esto se realiza a partir de la comparación de una tabla de contingencia y una tabla que representa la hipótesis nula, la cual asume independencia entre las variables. El propósito de este cálculo es poder rechazar la hipótesis nula al analizar e interpretar el resultado: si el valor p es menor al p crítico con un nivel de significancia de 0.05, se puede rechazar la hipótesis nula. De lo contrario, si el valor p es mayor a 0.05, no es posible rechazar la hipótesis nula, indicando que no hay evidencia suficiente para afirmar que existe una asociación estadísticamente significativa.</p>
<p>En la segunda hipótesis, que consiste en la existencia de una asociación positiva entre el uso de tarjetas con criptomonedas en el hogar (u_tcripto) y el valor total de los activos financieros (act_fin), se utiliza la correlación punto biserial, la cual es una técnica estadística que mide la fuerza y dirección de la relación entre una variable dicotómica y otra continua. Dicho estadístico permite establecer si la asociación es positiva o negativa, pudiendo tomar cualquier valor que se encuentre entre el intervalo [-1, +1]. Significando así que los valores cercanos a +1 indican una asociación positiva fuerte, los valores cercanos a -1 indican una asociación negativa fuerte, y los valores cercanos a 0 indican una relación débil. Para rechazar la hipótesis nula, se debe determinar si el coeficiente de correlación es significativo según su valor p, el cual debe ser menor al nivel de significancia de 0.05, de manera que si el valor p es significativo y el coeficiente de correlación es positivo, es posible rechazar la hipótesis nula y respaldar la la hipótesis alternativa. Para el último contraste de hipótesis, se analiza la asociación entre el valor total de activos financieros (act_fin) y el estrato de nivel de ingresos (estrato), siendo estas las variables independientes. Para esto, considerando que una variable es continua y la otra ordinal, se utiliza el método de cálculo de correlación de Spearman, cuyo coeficiente de correlación rho indica la fuerza y dirección de la asociación, pudiendo asumir valores entre -1 y +1. Para interpretar este coeficiente, se deben seguir los criterios de Cohen, en donde un valor de rho mayor o igual a o.50 es considerado una asociación fuerte. Así, si el resultado de la correlación de Spearman es positivo y significativo, se puede rechazar la hipótesis nula y respaldar la hipótesis alternativa, indicando una relación positiva entre el valor total de activos financieros y el estrato de nivel de ingresos.</p>
</section>
</section>
<section id="análisis" class="level1">
<h1>Análisis</h1>
<p>Para un mejor entendimiento de los estadísticos bivariados presentes en la investigación, se efectúa un análisis descriptivo de las variables utilizadas (0 = No usa; 1 = Si usa)</p>
<p>TABLA DE FRECUENCIAS SOBRE USO DE TARJETAS CON CRIPTOMONEDAS</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
135222   1178 </code></pre>
</div>
</div>
<p>Respecto a la variable uso de tarjetas con criptomonedas en el hogar, se muestra que la gran mayoría, equivalente al 99.14% (135,222 hogares), no utiliza criptomonedas, mientras que solo el 0.86% (1,178 hogares) sí las utiliza. La moda por lo tanto, es decir, la categoría con mayor frecuencia, es “no usa criptomonedas”.</p>
<p>TABLA DESCRIPTIVA ACTIVOS FINANCIEROS:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      Min.    1st Qu.     Median       Mean    3rd Qu.       Max.       NA's 
         0          0          0    7286706    1000000 1280000000        454 </code></pre>
</div>
</div>
<p>La segunda variable, valor total de los activos financieros, presenta una distribución altamente desigual. La media es de 7.286.706, lo que indica un promedio elevado que se ve influenciado por algunos hogares con altos valores de activos. La mediana, por otro lado, es de 0, lo cual significa que al menos el 50% de los hogares no poseen activos financieros. El primer cuartil (Q1) también es 0, es decir que al menos el 25% de los hogares carece de activos, mientras que el tercer cuartil (Q3) es de 1.000.000, indicando que el 75% de los hogares tiene activos financieros por debajo de este valor. Hay una desviación estándar de 44.299.725, lo que refleja una gran variabilidad de activos financieros en los hogares, y ya en relación al rango este oscila entre un valor mínimo de 0 y un máximo de 1.280.000.000. Estos indicadores de la variable mostrarían una distribución muy desproporcionada con una marcada concentración de hogares sin activos financieros y una pequeña proporción con valores de activos financieros muy altos.</p>
<p>TABLA DE FRECUENCIAS SOBRE VARIABLE ESTRATO DE NIVEL DE INGRESO</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribución del Estrato de Ingreso Efectivo del Hogar</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estrato</th>
<th style="text-align: left;">Frecuencia.Var1</th>
<th style="text-align: right;">Frecuencia.Freq</th>
<th style="text-align: left;">Porcentaje.Var1</th>
<th style="text-align: right;">Porcentaje.Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">61938</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">45.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">40424</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">29.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">34038</td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">24.95</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Como última variable se encuentra el estrato de ingreso efectivo del hogar. Sus medidas de tendencia central indican que la moda es 1 (deciles de 1 a 5), lo que refleja que el estrato de ingreso más frecuente es el estrato 1, mientras que la mediana es 2 (deciles de 6 a 8), señalando que la mitad de los hogares se encuentran en el estrato 2 o menos, lo que significa que al menos el 50% de los hogares encuestados pertenecen a los deciles 1 a 8. Según la distribución del ingreso, el estrato 1 tiene una frecuencia absoluta de 61.938, representando el 45.41% del total; el estrato 2 cuenta con 40.424, equivalente al 29.64%; y el estrato 3 incluye 34.038 hogares, que constituyen el 24.95%. Esto quiere decir que el estrato 1 no solo es el más frecuente, es decir, la moda, sino que también es aquel que concentra casi la mitad de la distribución, mientras que el estrato 3, con un 24.95%, tiene la menor representación.</p>
</section>
<section id="análisis-bivariado" class="level1">
<h1>Análisis Bivariado</h1>
<p>Tabla de contingencia Chi Cuadrado</p>
<div class="cell">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Estrato de ingreso<br>total del hogar</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">Uso de tarjeta con<br>criptomonedas</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">No</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Si</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Deciles 1 al 5</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">61659</span><br><span style="color:#333399;">99.5&nbsp;%</span><br><span style="color:#339933;">45.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">279</span><br><span style="color:#333399;">0.5&nbsp;%</span><br><span style="color:#339933;">23.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">61938</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">45.4&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Deciles 6 al 8</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">40176</span><br><span style="color:#333399;">99.4&nbsp;%</span><br><span style="color:#339933;">29.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">248</span><br><span style="color:#333399;">0.6&nbsp;%</span><br><span style="color:#339933;">21.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">40424</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">29.6&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Deciles 9 al 10</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">33387</span><br><span style="color:#333399;">98.1&nbsp;%</span><br><span style="color:#339933;">24.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">651</span><br><span style="color:#333399;">1.9&nbsp;%</span><br><span style="color:#339933;">55.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">34038</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">25&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">135222</span><br><span style="color:#333399;">99.1&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1178</span><br><span style="color:#333399;">0.9&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">136400</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=590.463 · df=2 · Cramer's V=0.066 · p=0.000</td> 
</tr>
 
</tbody></table>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  EFH2021$estrato and EFH2021$u_tcripto
X-squared = 590.46, df = 2, p-value &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>TABLA DE CONTINGENCIA OBSERVADA CHI CUADRADO:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   
        0     1
  1 61659   279
  2 40176   248
  3 33387   651</code></pre>
</div>
</div>
<p>Como primer cruce de variables para el contraste de hipótesis, se opera entre las variables uso de tarjetas con criptomonedas en el hogar y estrato de ingreso total, ambas variables categóricas, es por esto que se decide usar el test de hipótesis chi cuadrado. Los resultados indican un valor chi cuadrado de 590.40 con dos grados de libertad y un valor p de 2.2e-16, lo cual es un valor extremadamente pequeño, menor a 0.05. Esto indica, con un 95% de confianza, una diferencia significativa entre las frecuencias esperadas y las frecuencias observadas, de manera que es muy improbable que los resultados sean debido al azar, por lo que existe evidencia sólida para rechazar la hipótesis nula, la cual sostenía que habría una asociación negativa entre el uso de tarjetas con criptomonedas y los estratos de ingreso total, y se concluye que hay evidencia que respalda la hipótesis alternativa que indica que existe una asociación positiva y estadísticamente significativa entre el estrato de nivel de ingreso y el uso de criptomonedas, aunque cabe recalcar que en general hay poco uso de criptomonedas. No obstante, se efectuó el cálculo del estadístico V de Cramer para medir la fuerza de la asociación, lo que dio como resultado 0.0658, indicando una fuerza muy débil en la asociación, de manera que si bien la evidencia estadística respalda la hipótesis alternativa, la fuerza de la asociación entre las el Uso de tarjetas con criptomonedas y los Estratos de nivel de ingreso es muy débil, lo que podría deberse al bajo uso de tarjetas con criptomonedas en general. Por lo tanto, al ser tan débil la asociación entre las variables, no se puede sostener que el estrato de nivel ingreso tiene un impacto relevante en el uso de tarjetas con criptomonedas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  EFH2021$u_tcripto and EFH2021$act_fin
t = 2.8733, df = 135944, p-value = 0.004062
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.002477128 0.013108007
sample estimates:
        cor 
0.007792788 </code></pre>
</div>
</div>
<p>En segundo lugar, para cruzar las variables valor total de los activos financieros y uso de tarjetas con criptomonedas se utiliza la correlación punto biserial debido a que una variable es continua y la otra dicotómica. Respecto a los resultados, el coeficiente de correlación fue de 0.0078, lo que indica una asociación positiva y en extremo pequeña según los criterios de Cohen. Por otra parte, el valor p dio como resultado 0.0041, de manera que, con un 95% se rechaza la hipótesis nula, indicando que la relación es estadísticamente significativa. Por lo tanto, se puede sostener que si bien existe evidencia para rechazar la hipótesis nula, la cual indica que existe asociación negativa entre uso de tarjetas con criptomonedas y valor total de activos financieros. Como la fuerza de la relación es demasiado pequeña, se puede plantear que el valor total de activos financieros tiene una relevancia práctica muy limitada en el uso de tarjetas con criptomonedas. Al igual que en la correlación anterior entre uso de tarjetas con criptomonedas y estrato de nivel de ingreso, esto puede deberse al bajo uso de tarjetas con criptomonedas en la población encuestada.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  EFH2021$estrato and EFH2021$act_fin
S = 246247023817678, p-value &lt; 0.00000000000000022
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.4119382 </code></pre>
</div>
</div>
<p>Por último, al cruzar la variable estrato de nivel de ingreso con el valor total de los activos financieros, se utiliza el estadístico de correlación de Spearman, pues una variable es ordinal y la otra continua. Los resultados muestran una asociación positiva y moderada –según los criterios de Cohen– entre ambas variables (rho = 0.411, p &lt; 0.05), de manera que, debido al valor p menor a 0.05, rechazamos la hipótesis nula con un nivel de confianza de 95%, la cual indica que existiría asociación negativa entre los estratos de nivel de ingreso y el valor total de activos financieros, esto implica rechazar la hipótesis nula, sugiriendo que los hogares de mayor estrato de nivel de ingresos tienden a tener un mayor valor total de activos financieros.</p>
</section>
<section id="discusión" class="level1">
<h1>Discusión</h1>
<p>Recapitulando los resultados en relación a las hipótesis planteadas, se puede apreciar que a pesar de que existe evidencia que respalda que las variables uso de tarjetas con criptomonedas y estrato de nivel de ingreso están asociadas positivamente a través de la prueba Chi Cuadrado (590.40, p &lt; 0,05), la prueba V de Cramer indica que dicha relación en tan débil (0.0658), que sugiere que el estrato de nivel de ingreso no es un factor relevante en el uso de tarjetas con criptomonedas en los hogares. Lo mismo ocurre con la segunda asociación entre el uso de tarjetas con criptomonedas y el valor total de los activos financieros, en donde, a través de la prueba Punto Biserial, también existe evidencia para rechazar la hipótesis nula y respaldar la hipótesis alternativa que indicaría una asociación positiva entre las variables (0,0078, p &lt; 0,05), pero como la magnitud de la asociación es tan débil, la relevancia práctica de dicha asociación parece ser muy limitada en términos prácticos. En ambos casos, la debilidad de la asociación poca relevancia práctica podría deberse al bajo uso de tarjetas con criptomonedas en la población en general (0,86% de la población encuestada), lo cual limita la capacidad de detectar relaciones fuertes. En el caso de la segunda asociación, se suma el hecho de que la variable valor total de activos financieros presenta una distribución muy asimétrica, con más del 50% de los hogares sin activos financieros.</p>
<p>Por otro lado, la tercera asociación muestra resultados más consistentes, pues la asociación entre el valor total de activos financieros y el estrato de nivel de ingresos a través del estadístico de correlación de Spearman dio como resultado un rho = 0.411, y un valor p &lt; 0.05 lo que indica una asociación positiva y moderada según los criterios de Cohen, y permite rechazar la hipótesis nula con un 95% de confianza. Por lo tanto, se rechaza la hipótesis nula de que existiría una asociación negativa entre los estratos de nivel de ingreso y el valor total de activos financieros, por lo que se sostiene la existencia de evidencia estadística que respalda la asociación entre el valor de activos con el estrato de nivel de ingreso de los hogares.</p>
<p>El contraste tan marcado entre las asociaciones podría deberse a que para 2021, el uso de tarjetas con criptomonedas en hogares chilenos era una práctica incipiente, de manera que su bajo uso podría relacionarse con una débil conducta financiarizada en entornos digitales, mientras que la robustez de los datos y la asociación entre el valor total de activos financieros y el estrato de nivel de ingreso indicaría una prevalencia de conductas financiarizadas que podríamos denominar “tradicionales” en contraposición a uso de tarjetas con criptomonedas que es una práctica emergente.</p>
</section>
<section id="conclusiones" class="level1">
<h1>Conclusiones</h1>
<p>El presente estudio se centró en buscar una relación entre el uso de tarjetas con criptomonedas, entendido como una forma de financiarización de los hogares chilenos en entornos digitales con dos factores socioeconómicos: estrato de nivel de ingresos y valor total de activos financieros. Los resultados muestran que si bien existen asociaciones estadísticamente significativas entre el uso de tarjetas con criptomonedas y los factores socioeconómicos mencionados, la magnitud de la fuerza de estas asociaciones es tan débil que su relevancia práctica es muy limitada, lo cual describe un escenario débilmente financiarizado en entornos digitales en la generalidad de los hogares encuestados.</p>
<p>En contraposición a esto, se encontró una asociación positiva y moderada entre el valor total de activos financieros y el estrato de nivel de ingreso, lo cual indica que los hogares de mayor estrato de nivel de ingreso tienden a tener un mayor valor total de activos financieros. Esto indica que en los hogares de mayores ingresos podría haber una prevalencia de conductas financiarizadas que se pueden denominar como “tradicionales” en contraste a las nuevas prácticas digitales de financiarización.</p>
<p>En cuanto a las limitaciones que se presentaron, la principal se relaciona con las características de la variable uso de tarjetas con criptomonedas y la baja concentración de respuestas “sí” (0.86%), lo que limitó la capacidad para encontrar asociaciones fuertes. Por otra parte, la distribución fuertemente asimétrica de la variable valor total de activos financieros, en donde más del 50% de los hogares reportó no tener activos financieros, y muy pocos reportaron valores extremadamente altos, surgen dificultades al interpretar el coeficiente de correlación como representativo de toda la población.</p>
<p>A modo de cierre y como sugerencia para futuros análisis, se recomienda utilizar el glosario de la Encuesta Financiera de Hogares de 2021 en conjunto con el presente informe, con la finalidad de comprender a cabalidad las tendencias financieras recolectadas por dicha encuesta, las cuales no logran ser analizadas en su totalidad debido a la acotada extensión de este análisis. A su vez, se sugiere recodificar la variable continua “valor total de activos financieros” a una variable ordinal debido a que los datos de esta variable son altamente asimétricos, donde al menos el 50% de los hogares registrados reportan no poseer activos financieros.</p>
</section>
<section id="bibliografía" class="level1">
<h1>Bibliografía</h1>
<p>Abalde, N., López-Roldán, P., &amp; Massó M. (2024). Financialisation of everyday life: exploring socio economic behavior in Southern European Countries. EMPIRIA: Revista de Metodología de Ciencias Sociales, 61, 41-67. https://doi.org/61.2024.41282</p>
<p>Encuesta financiera de Hogares (2022). Informe Metodológico. Banco Central de Chile, disponible en: https://www.bcentral.cl/documents/33528/3660586/Documento+Metodológico+EFH+2021.pdf/76935084-9482-a170-04ec-fa5593f6c920?t=1669222656176</p>
<p>Jagati, S. (2024). Cómo creció la adopción de criptomonedas en 2023. https://es.cointelegraph.com/news/crypto-adoption-2023-investing-ventures Langley, P. (2008). Financialization and the consumer credit boom. Competition &amp; Change, 12(2), 133-147.</p>
<p>Marambio, A. (2018). El peso de la financiarización de la vida diaria del nuevo proletariado de servicios en Chile. Revista Central de Sociología, N°8, 2019 pp.&nbsp;82 - 101. Disponible en: http://200.9.234.120/bitstream/handle/ucm/2650/marambio_a_peso.pdf?sequence=1&amp;isAllowed=y</p>
<p>Nakamoto, S. (2008). Bitcoin: A Peer-to-Peer Electronic Cash System. Disponible en: https://bitcoin.org/bitcoin.pdf</p>
<p>Pereira, A. (2024). ¿Qué impacto tiene la Criptomoneda en la Economía Global?. https://fundacioneveris.com/economia-criptomonedas/que-impacto-tiene-la-criptomoneda/</p>
<p>Van der Zwan, N. (2014). Making sense of financialization. Socio-Economic Review, 12(1): 99 - 129. https://doi.org/10.1093/ser/mwt020 Financieras (sf) Las criptomonedas y su impacto en el mercado financiero. https://financieras.org/blog/las-criptomonedas-y-su-impacto-en-el-mercado-financiero</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/correlacional\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>