<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martina Soto, Violeta Mansilla, Carolina Gatica, Francisca Osorio.">

<title>Salud mental</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="borrador_files/libs/clipboard/clipboard.min.js"></script>
<script src="borrador_files/libs/quarto-html/quarto.js"></script>
<script src="borrador_files/libs/quarto-html/popper.min.js"></script>
<script src="borrador_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="borrador_files/libs/quarto-html/anchor.min.js"></script>
<link href="borrador_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="borrador_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="borrador_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="borrador_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="borrador_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="borrador_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="borrador_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="borrador_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="borrador_files/libs/tabwid-1.1.3/tabwid.js"></script>



</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Salud mental</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Martina Soto, Violeta Mansilla, Carolina Gatica, Francisca Osorio. </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Invalid Date</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>La comunicación emocional, la cual es esencial para las relaciones y el bienestar individual, puede estar influenciada por diversos factores. Este estudio analiza si variables como el género, ingresos y el tratamiento por depresión influyen en la frecuencia con que las personas conversan sobre sus problemas con familiares o amigos.</p>
<p>Utilizando datos del Estudio Longitudinal Social de Chile 2021, se exploran relaciones entre la frecuencia de conversación sobre problemas (variable dependiente), y el sexo, el ingreso líquido al hogar y el tratamiento por depresión (variables independientes).</p>
<p>A través de análisis estadísticos bivariados, no se identificaron asociaciones significativas entre las variables escogidas, lo que sugiere que las diferencias en género, nivel de ingresos y tratamiento por depresión no impactan de manera suficiente en la frecuencia con que las personas comunican sus problemas.</p>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>La comunicación expresiva, entendida por Rafael Bizquerra y Nuria Pérez como la capacidad de expresar y gestionar emociones para fortalecer las relaciones sociales (2007), tiene un impacto directo en el bienestar personal y social de los individuos. En este sentido, se ha demostrado que las personas que poseen habilidades emocionales desarrolladas suelen tener mejores interacciones sociales, repercutiendo positivamente esto en su salud mental y en relaciones interpersonales (Bizquerra &amp; Pérez, 2007).</p>
<p>La comunicación emocional se encuentra influenciada por diversos factores socioculturales como el género y el nivel socioeconómico. En primer lugar, la expresión emocional ha sido históricamente asociada al género femenino, presentándose a la mujer como un ser sensible y emocional, que con facilidad demuestra públicamente sus sentimientos, “con tendencia a pensar demasiado sobre éstos y los de los demás y con dificultad para controlar sus emociones y no dejarse llevar por ellas.” (Carretero &amp; Nolasco, 2017, p.35). En contraste, la imagen social del hombre se ha presentado como aquel que “no muestra sentimientos o emociones en público y al que le cuesta hablar de emociones, que no da importancia a estas emociones y que es capaz de controlarlas y no dejarse llevar por ellas.” (Carretero &amp; Nolasco, 2017, p.35). Estas diferencias de género pueden influir significativamente en la frecuencia con qué hombres y mujeres hablan de sus problemas con amigos y familiares.</p>
<p>Desde el ámbito socioeconómico, este también juega un rol importante en cómo las personas comunican sus emociones. Estudios demuestran que el estatus socioeconómico influye significativamente en la felicidad y en la inteligencia emocional (Pulido &amp; Herrera, 2018). Asimismo, se destaca que las personas que pertenecen a niveles socioeconómicos altos presentan mayores niveles de felicidad y bienestar, mientras que aquellos con menor estatus enfrentan mayores barreras para gestionar de mejor manera sus emociones y construir redes de apoyo (Pulido &amp; Herrera, 2018).</p>
<p>Por último, el tratamiento por depresión aparece como otra variable relevante para analizar la comunicación emocional. Según López (2007), la depresión implica tristeza persistente y baja autoestima, lo que afecta en la interacción social y en la construcción de redes de apoyo. Respecto a su tratamiento, Ortega (2010) indica que el acceso a este favorece la gestión emocional, esencial para el bienestar personal. Quienes reciben tratamiento podrían mostrar patrones diferentes de comunicación emocional en comparación con quienes no lo reciben.</p>
<p>Este informe se centra en analizar cómo las variables de género, ingresos en el hogar y tratamiento por depresión afectan la frecuencia con la que las personas hablan de sus problemas con amigos o familiares. De este modo, se plantean las siguientes hipótesis:</p>
<p>H1: A mayor nivel socioeconómico, las personas hablan más de sus problemas con amigos y/o familiares.</p>
<p>H2: Existen diferencias en la frecuencia con la que hombres y mujeres hablan de sus problemas con sus amigos/familiares</p>
<p>H3: Existen diferencias en el nivel socioeconómico entre quienes reciben tratamiento por depresión y aquellos que no lo reciben</p>
<p>Estas hipótesis buscan aportar una perspectiva integral respecto a los factores que inciden en la comunicación emocional, contribuyendo al entendimiento de cómo las condiciones sociales y personales afectan a esta dimensión del bienestar individual.</p>
</section>
<section id="metodología" class="level2">
<h2 class="anchored" data-anchor-id="metodología">Metodología</h2>
<p>Para este estudio se utilizará la base de datos del Estudio Longitudinal Social de Chile (ELSOC) del año 2021. ELSOC es un estudio realizado en Chile y América Latina en el que se busca analizar el comportamiento de una muestra urbana de la población, frente a temas relacionados con el conflicto y la cohesión social.</p>
<p>En ese sentido, de este estudio se extraerán cuatro variables con el fin de analizar la relación entre la salud mental y factores sociodemográficos. De este modo, la variable dependiente abarca la frecuencia de conversación sobre problemas con familia o amigos, y las variables independientes incluyen sexo, ingresos en el hogar y si la persona ha recibido tratamiento por depresión.</p>
<p>La selección de variables esenciales para este estudio serán presentadas a continuación.</p>
<p>Frecuencia en la que se puede hablar sobre problemas con familia o amigos (S12) [Módulo S: Salud y Bienestar]</p>
<p>La variable S12 pertenece al módulo S de “Salud y Bienestar” y mide la frecuencia con la que la persona encuestada puede comunicar sus problemas a familiares o amigos. Esta puede reflejar el apoyo social con el que cuenta la persona para expresar sus problemas emocionales, lo cual está estrechamente relacionado con la salud mental y el bienestar personal. Su nivel de medición es ordinal, basado en una escala Likert, en ese sentido, las opciones de respuesta son: “Nunca” (1), “Pocas veces” (2), “Algunas veces” (3), “Muchas veces” (4) y “Siempre” (5).</p>
<p>Ha recibido tratamiento por depresión (S14) [Módulo S: Salud y Bienestar]</p>
<p>La variable S14 pertenece al módulo S de “Salud y Bienestar” y mide si la persona encuestada ha recibido tratamiento para la depresión. Este tratamiento puede influir en cómo una persona enfrenta sus problemas y cómo los expresa, impactando directamente con la salud mental y bienestar de esta. Su nivel de medición es nominal, donde 1 corresponde a la opción “Sí”, y la opción 2 “No”.</p>
<p>Sexo (M0_sexo) [Módulo M: Caracterización Sociodemografica]</p>
<p>La variable M0_sexo pertenece al módulo M de “Caracterización Sociodemografica” y busca identificar el sexo del entrevistado. Esta puede influir en la forma en que se gestionan y expresan los problemas emocionales. Las imágenes sociales relacionadas con el género pueden lograr influir en la expresión emocional de una persona. Su nivel de medición es nominal, donde 1 corresponde a la opción “Hombre”, y la opción 2 “Mujer”.</p>
<p>Ingreso hogar (M29) [Módulo M: Caracterización Sociodemográfica]</p>
<p>La variable M29 pertenece al módulo M de “Caracterización Sociodemográfica”, y busca registrar en pesos chilenos el valor del ingreso total del hogar de la persona entrevistada en relación al mes pasado; considera solo ingresos líquidos de los integrantes del hogar. El nivel socioeconómico de un hogar representa el acceso a diferentes recursos, entre ellos emocionales, lo que puede influir en cómo una persona gestiona y expresa sus problemas. Un mayor nivel socioeconómico puede asociarse con un mayor acceso a servicios de salud mental y redes de apoyo.</p>
<p>Su nivel de medición es de razón, donde la respuesta es abierta con el fin de que la persona encuestada proporcione un valor numérico exacto correspondiente al ingreso total líquido de su hogar.</p>
<p>A continuación se presenta una tabla que incluye los estadisticos descriptivos básicos de las variables que se utilizaran en el desarrollo del trabajo.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Tabla de estadísticos descriptivos
</figcaption>
<div aria-describedby="tbl-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="container st-container">

<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>No</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Variable</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Stats / Values</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Freqs (% of Valid)</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Graph</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Valid</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Missing</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">sexo [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Min : 1</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean : 1.6</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Max : 2</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">584</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">36.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">1017</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">63.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAGwAAAA3BAMAAAAbAbLKAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMiiCez4gAAAARElEQVRIx2NgGN5ACTdQFMQCoNqUjXGCUW2j2ka1jWojWhuZRZAgiWBAtCmRCAiHJDZgNKptVNuotlFt2LSRWQQNVwAA17Nl2toIUAoAAAAASUVORK5CYII=" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1601 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">ingreso_hogar [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 746951.3 (844435.6)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">0 ≤ 500000 ≤ 11000000</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 550000 (1.1)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle;">194 distinct values</td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAJgAAABuBAMAAAApJ8cWAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMiiCez4gAAAAZElEQVRo3u3ZsQ2AMAwAQa/ACIQNyP67RZA0tHGQELovXJ7cuHKEZiq9LdfAjnp1wmAwGAwGg8FgMBgMBoPBYDAYDAaDwV7Gkj+eJ5bcDwb7BdaPal+D3bN+F5t4Ew+sLCk0UwNlj0SluUPpJgAAAABJRU5ErkJggg==" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1601 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">frec_hablar [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 3.3 (1.4)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 3 ≤ 5</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 3 (0.4)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">163</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">421</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">26.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">314</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">19.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">202</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">12.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">501</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">31.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAADwAAAB9BAMAAAAM1h2IAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMiiCez4gAAAAa0lEQVRIx+3UwQ2AIAxGYVboCrAB7r+biSFKpE1jVbi8d/0uHP6S0tpyS241LttRheHX7GxNjD7hrDS+vK/CcIidrc3cuXGh/aNhOMbO1ibtXOUyPhqGY+xsTYz++M/P1Au9ThWGH7OztVXtlEyAwWov9asAAAAASUVORK5CYII=" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1601 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">trat_depre [factor]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1. 0</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">2. 1</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 5px 0 7px; margin: 0; border: 0;">1393</td>
<td style="text-align: left; padding: 0 2px 0 0; border: 0;">(</td>
<td style="text-align: right; padding: 0; border: 0;">87.0%</td>
<td style="text-align: left; padding: 0 4px 0 2px; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 5px 0 7px; margin: 0; border: 0;">208</td>
<td style="text-align: left; padding: 0 2px 0 0; border: 0;">(</td>
<td style="text-align: right; padding: 0; border: 0;">13.0%</td>
<td style="text-align: left; padding: 0 4px 0 2px; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAI8AAAA3BAMAAADH1AS4AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMiiCez4gAAAATElEQVRIx2NgGAXEACVKgQLUIGVjCsGoQaMGjRo0atCoQXQziGqFvyClQGDQGoTwLIUGwWPNaNSgUYNGDRo1aNSgwW4Q1Qr/UYAfAACj3p3ZsG6LJwAAAABJRU5ErkJggg==" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1601 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
</tbody>
</table>

<p>Generated by <a href="https://github.com/dcomtois/summarytools">summarytools</a> 1.0.1 (<a href="https://www.r-project.org/">R</a> version 4.4.2)<br>2024-12-01</p>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>Respecto a los métodos estadísticos a utilizar para el contraste de hipótesis, en la primera hipótesis se utilizará la correlación de Pearson ya que lo que se busca evaluar es si existe o no una relación lineal entre las dos variables necesarias, para este caso, el ingreso del hogar y la frecuencia en la que las personas pueden hablar de sus problemas con familiares o amigos. Para este caso, el resultado nos indica el cálculo del tamaño de efecto, en cuanto a su interpretación esta se desarrollará bajo los criterios de Cohen.</p>
<p>El test de hipótesis a utilizar para la segunda y tercera hipótesis es la prueba T; esta decisión se justifica producto de que se busca relacionar las medias de dos variables sin mayor relación. Para el caso de la segunda hipótesis se busca relacionar la frecuencia en que se puede hablar de los problemas con familiares o amigos, en relacion con el sexo de los encuestados, dichas variables pertenecn a grupos independientes, por lo que la prueba t se presenta como la herramienta indicada. Con respecto a la tercera hipótesis, lo que se busca indagar es la relación entre quienes reciben tratamiento por depresión y quienes no, considerado el ingreso del hogar, en este caso la prueba t sirve para determinar si existe una media diferente en el ingreso del hogar entre quienes reciben tratamiento o no.</p>
<p>Respecto al cálculo del tamaño de efecto, al igual que utilizando la correlación de Pearson, se desarrollará un análisis de los resultados bajo los criterios de Cohen.</p>
</section>
<section id="análisis" class="level2">
<h2 class="anchored" data-anchor-id="análisis">Análisis</h2>
<section id="análisis-descriptivo-univariado" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivo-univariado">Análisis descriptivo univariado</h3>
<p>En esta sección se presentará un análisis descriptivo de las variables utilizadas, considerando las medidas de tendencia central, de dispersión y sus frecuencias. En ese sentido, es relevante destacar que la muestra se constituye de un total de 1601, de los cuales 1017 son mujeres y 584 son hombres. A continuación se presenta el análisis descriptivo.</p>
<p>Con respecto a la variable de “Frecuencia de conversación sobre problemas con familia o amigos”, la media de 3.29 sugiere que, en promedio, las personas tienen una frecuencia moderada de hablar sobre problemas con familiares o amigos. La mediana, que es 3, indica que la distribución parece estar concentrada alrededor del promedio, lo que sugiere que más de la mitad de los participantes tienen una frecuencia similar a la media.</p>
<p>El rango de 4 indica cierta dispersión en las respuestas. La desviación estándar de 1.40 y la varianza de 1.97 muestran que, aunque hay cierta variabilidad, los datos no poseen una gran dispersión.</p>
<p>Finalmente, el primer cuartil (Q1) muestra que el 25% de los participantes tienen una frecuencia menor o igual a 2 lo que indica que nunca o pocas veces suelen hablar de sus problemas con familiares y/o amigos, mientras que el segundo cuartil señala que el 75% indican una frecuencia menor o igual a 5.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Tabla de estadísticos descriptivos para la variable Frecuencia en la que se puede hablar sobre problemas con familiares o amigos
</figcaption>
<div aria-describedby="tbl-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">media</th>
<th style="text-align: right;">mediana</th>
<th style="text-align: right;">q1</th>
<th style="text-align: right;">q2</th>
<th style="text-align: right;">rango</th>
<th style="text-align: right;">desviacion_estandar</th>
<th style="text-align: right;">varianza</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">3.285447</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1.402799</td>
<td style="text-align: right;">1.967844</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>En relación con la variable “Sexo”, la población es de 1017 mujeres y 584 hombres, por lo que existe una predominanacia femenina. Cabe señalar que al ser una variable dicotómica no se requiere de un análisis descriptivo en profundidad, sin embargo a continuación se presenta la tabla proporcionada por RStudio.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Tabla de estadísticos descriptivos para la variable Sexo
</figcaption>
<div aria-describedby="tbl-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">media</th>
<th style="text-align: right;">mediana</th>
<th style="text-align: right;">q1</th>
<th style="text-align: right;">q2</th>
<th style="text-align: right;">rango</th>
<th style="text-align: right;">desviacion_estandar</th>
<th style="text-align: right;">varianza</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1.635228</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.4815166</td>
<td style="text-align: right;">0.2318582</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Respecto a la variable “Ingreso hogar”, se visualiza que el ingreso promedio es de $746.951, con una mediana de $500.000, lo que sugiere que los ingresos se encuentran distribuidos de una manera asimétrica, y se confirma con la desviación estándar, que es de $844.435. Así también, el rango de $1.100.000 muestra una gran brecha entre el ingreso más bajo y el más alto.&nbsp;</p>
<p>Los cuartiles Q1 y Q2 señalan que el 25% de la población estudiada gana 300.000 o menos, mientras que el 75% gana 850 000 o menos. Por último, la varianza es de $713.071.475.125, reforzando que existe una alta variabilidad en los ingresos de la población observada.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-4" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Tabla de estadísticos descriptivos para la variable Ingreso hogar
</figcaption>
<div aria-describedby="tbl-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 27%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">media</th>
<th style="text-align: right;">mediana</th>
<th style="text-align: right;">q1</th>
<th style="text-align: right;">q2</th>
<th style="text-align: right;">rango</th>
<th style="text-align: right;">desviacion_estandar</th>
<th style="text-align: right;">varianza</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">746951.3</td>
<td style="text-align: right;">500000</td>
<td style="text-align: right;">300000</td>
<td style="text-align: right;">850000</td>
<td style="text-align: right;">11000000</td>
<td style="text-align: right;">844435.6</td>
<td style="text-align: right;">713071475125</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Para finalizar, respecto a la variable Tratamiento por depresión, no es necesario un análisis descriptivo debido a que es una variable nominal dicotómica, al respecto, se presenta una tabla que indica la cantidad de personas que indican recibir tratamiento por depresion, y quienes no.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "No recibe tratamiento" "Si recibe tratamiento"</code></pre>
</div>
</div>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-5" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Tabla de frecuencias para la variable Tratamiento por depresión
</figcaption>
<div aria-describedby="tbl-5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No recibe tratamiento</td>
<td style="text-align: right;">1393</td>
</tr>
<tr class="even">
<td style="text-align: left;">Si recibe tratamiento</td>
<td style="text-align: right;">208</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="análisis-descriptivo-bivariado" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivo-bivariado">Análisis descriptivo bivariado</h3>
<p>Esta sección presenta un análisis bivariado representado por medio de tablas o gráficos segun sea más pertinente. En ese sentido, el análisis se desarrolla presentando tablas o gráficos para representar las relaciones entre las variables utilizadas para cada hipótesis.</p>
<p>La primera hipótesis señala que un frente a un mayor nivel socioeconómico, las personas pueden hablar más de sus problemas con amigos o familiares, a continuación se presenta un diagrama de dispersión que representa la relación entre las dos variables:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico representa la relación entre las variables “Ingreso hogar” y “Frecuencia con la que las personas hablan de sus problemas con familiares o amigos”. En este se muestra que los puntos están distribuidos en todos los niveles de frecuencia, sin depender del nivel de ingreso de los hogares. Así, se puede evidenciar que la categoría de frecuencia más alta también incluye personas de niveles socioeconómicos bajos, medios y altos.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-hipo1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hipo1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Tabla correlacion de Pearson
</figcaption>
<div aria-describedby="tbl-hipo1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed do-not-create-environment cell caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">t</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Método</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Alternativa</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">95% IC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">6.32</td>
<td style="text-align: left;">&lt; 0.001***</td>
<td style="text-align: right;">1599</td>
<td style="text-align: left;">Pearson's product-moment correlation</td>
<td style="text-align: left;">two.sided</td>
<td style="text-align: left;">[0.11,0.2]</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</figure>
</div>
</div>
<p>De esta misma manera, respecto al análisis estadístico bivariado, según la prueba de correlación de Pearson, existe una asociación de 0,16 entre las variables “Ingreso hogar” y “Frecuencia con la que las personas hablan de sus problemas con familiares o amigos”. Esto implica que la asociación existente entre ambas variables es positiva, sin embargo también es baja, por ende, tampoco es estadísticamente significativa. De este modo, la hipótesis nula de no asociación entre ambas variables no se puede rechazar con un 99% de confianza, rechazando por el contrario la hipótesis alternativa de la existencia de dicha asociación.</p>
<p>Respecto a la hipótesis dos, esta postula que existen diferencias en la frecuencia con la que hombres y mujeres hablan de sus problemas con sus amigos y/o familiares. Al respecto, se presenta el gráfico de barras que representa la relación entre las variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico anterior representa la relación entre las variables “Sexo” y “Frecuencia con la que las personas hablan de sus problemas con familiares o amigos”.</p>
<p>Este señala que existe una gran diferencia con respecto a los valores de la segunda variable dependiendo del sexo del sujeto. Esto apunta a que las mujeres presentan una mayor frecuencia para hablar de sus problemas con familiares y amigos, en comparación a los hombres, mostrando una diferencia para ambos sexos de más de 600 casos.</p>
<p>A continuación se presenta la tabla que indica los resultados de la prueba t para la segunda hipótesis:</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-hipo2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hipo2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Existen diferencias en la frecuencia con la que hombres y mujeres hablan de sus problemas con sus amigos/familiares
</figcaption>
<div aria-describedby="tbl-hipo2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-387b93e6{table-layout:auto;}.cl-3871bc7c{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3871bc86{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-3871bc90{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-3875cc4a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-3875cc54{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-3875e540{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3875e54a{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-3875e554{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-387b93e6"><thead><tr style="overflow-wrap:break-word;"><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc7c">Method</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc7c">Alternative</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc7c">Mean 1</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc7c">Mean 2</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc86">M</span><span class="cl-3871bc90">1</span><span class="cl-3871bc7c"> - </span><span class="cl-3871bc86">M</span><span class="cl-3871bc90">2</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc86">t</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc86">df</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc86">p</span></p></th><th class="cl-3875e540"><p class="cl-3875cc4a"><span class="cl-3871bc7c">95% CI</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-3875e54a"><p class="cl-3875cc54"><span class="cl-3871bc7c">Welch Two Sample t-test</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">two.sided</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">3.25</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">3.30</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">-0.05</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">-0.74</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">1,253.73</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">.461</span></p></td><td class="cl-3875e554"><p class="cl-3875cc4a"><span class="cl-3871bc7c">[-0.19, 0.09]</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>En contraste, la prueba T de dos muestras de Welch, que evalúa las diferencias en la frecuencia con la que hombres y mujeres hablan de sus problemas con familiares o amigos, sugiere que la diferencia no es estadísticamente significativa (diferencia = -0.05, t(461)=0.74, p=0.461t(461) = 0.74, p = 0.461t(461)=0.74, p=0.461). El valor de ppp indica que la probabilidad de observar una diferencia de esta magnitud, o mayor, bajo la suposición de la hipótesis nula, es superior al 5%. Por tanto, con un 95% de confianza, no es posible rechazar la hipótesis nula, ya que no existe evidencia suficiente a favor de la hipótesis alternativa respecto a que haya diferencias significativas entre hombres y mujeres en cuanto a la frecuencia con la que hablan de sus problemas.</p>
<p>La hipótesis tres postula que existen diferencias en el nivel socioeconómico entre quienes reciben tratamiento por depresión y aquellos que no lo reciben, a continuación se presenta la tabla que representa la relación entre ambas variables:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "No recibe tratamiento" "Si recibe tratamiento"</code></pre>
</div>
</div>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-6" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Relación entre las variables de ingreso hogar y tratamiento por depresión
</figcaption>
<div aria-describedby="tbl-6-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="borrador_files/figure-html/tbl-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>La tabla anterior representa la relación entre las variables “Tratamiento recibido por depresión” y “Frecuencia con la que las personas hablan de sus problemas con familiares o amigos”. Dicha tabla señala que la mayor parte de los sujetos encuestados no reciben tratamiento por depresión, sin embargo quienes sí lo reciben no parecen concentrarse en un sector específico de ingresos. Esto muestra que no parece existir una relación entre quienes reciben un tratamiento por depresión y el ingreso de sus hogares. Sin embargo, cabe destacar que con las variables escogidas no es posible determinar quienes deberían estar recibiendo dicho tratamiento, por lo que el análisis podría ser sesgado.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-hipo3" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hipo3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Tabla prueba t: Existen diferencias en el nivel socioeconómico entre quienes reciben tratamiento por depresión y aquellos que no lo reciben
</figcaption>
<div aria-describedby="tbl-hipo3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-38fd4dd2{table-layout:auto;}.cl-38f48dc8{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-38f48dd2{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-38f48ddc{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-38f7f80a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-38f7f814{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-38f80d22{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-38f80d2c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-38f80d2d{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-38fd4dd2"><thead><tr style="overflow-wrap:break-word;"><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dc8">Method</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dc8">Alternative</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dc8">Mean 1</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dc8">Mean 2</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dd2">M</span><span class="cl-38f48ddc">1</span><span class="cl-38f48dc8"> - </span><span class="cl-38f48dd2">M</span><span class="cl-38f48ddc">2</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dd2">t</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dd2">df</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dd2">p</span></p></th><th class="cl-38f80d22"><p class="cl-38f7f80a"><span class="cl-38f48dc8">95% CI</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-38f80d2c"><p class="cl-38f7f814"><span class="cl-38f48dc8">Welch Two Sample t-test</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">two.sided</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">759,418.52</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">663,456.73</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">95,961.79</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">1.39</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">256.95</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">.166</span></p></td><td class="cl-38f80d2d"><p class="cl-38f7f80a"><span class="cl-38f48dc8">[-40004.95, 231928.53]</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>Así mismo, la prueba t de dos muestras de Welch, que evalúa la diferencia de medias entre el nivel socioeconómico de quienes reciben tratamiento por depresión y quienes no lo reciben, sugiere que la diferencia no es estadísticamente significativa (diferencia = 95.961,79, t(256.95) = 1.39, p = 0.166). El valor de p indica que la probabilidad de observar una diferencia de esta magnitud, o mayor, bajo la suposición de la hipótesis nula, es superior al 5%. Por tanto, con un 95% de confianza, no es posible rechazar la hipótesis nula, ya que no existe evidencia suficiente a favor de la hipótesis alternativa respecto a que el nivel socioeconómico difiera significativamente entre quienes reciben tratamiento por depresión y aquellos que no lo reciben.</p>
<p>A modo de cierre y como discusión, se destaca en los análisis que las tres hipótesis (H1: A mayor nivel socioeconómico, las personas hablan más de sus problemas con amigos y/o familiares. H2: Existen diferencias en la frecuencia con la que hombres y mujeres hablan de sus problemas con sus amigos y/o familiares. H3: Existen diferencias en el nivel socioeconómico entre quienes reciben tratamiento por depresión y aquellos que no lo reciben) hayan sido rechazadas. Sin embargo, cabe destacar como limitación que estos hayan podido estar sesgados por la falta de un análisis multivariado que incorpore nuevas aristas. Así, se considera que para investigaciones futuras podría ser útil incluir nuevas variables que permitan una mayor comprensión de los fenómenos observados.</p>
</section>
</section>
<section id="conclusión" class="level2">
<h2 class="anchored" data-anchor-id="conclusión">Conclusión</h2>
<p>A modo de conclusión se realizará un resumen de los resultados obtenidos a partir de las hipótesis planteadas sobre las relaciones entre el sexo de los sujetos, el nivel socioeconómico, el tratamiento por depresión y la frecuencia con la que las personas hablan de sus problemas con amigos o familiares.</p>
<p>En primer lugar, se encontró evidencia de que a mayor nivel socioeconómico, las personas tienden a hablar más de sus problemas con su entorno cercano. Este resultado resalta una posible conexión entre los recursos económicos y el soporte social percibido. Sin embargo los resultados no son estadísticamente significativos. En contraste, en los otros dos casos, no se encontraron diferencias estadísticamente significativas. En relación con las diferencias entre hombres y mujeres respecto a la frecuencia con la que hablan de sus problemas, los resultados no indican evidencia suficiente para afirmar que existan disparidades significativas entre ambos grupos. De manera similar, no se hallaron diferencias significativas en el nivel socioeconómico entre quienes reciben tratamiento por depresión y quienes no lo reciben, sugiriendo que este factor puede no ser un determinante directo en la decisión o posibilidad de recibir tratamiento. Una limitación importante en el análisis es la posible influencia de variables no consideradas, como factores culturales, psicológicos o de acceso a servicios de salud, que podrían mediar las relaciones analizadas. Además, la selección de la muestra y la naturaleza autoreportada de los datos pueden introducir sesgos. Para próximos análisis, se podría explorar la influencia de factores contextuales, como que si los encuestados tienen de redes de apoyo, o la existencia de estigmas asociados a los problemas de salud mental, aquellas variables podrían dar una visión más completa de lo que buscamos comprender.</p>
</section>
<section id="bibliografía" class="level2">
<h2 class="anchored" data-anchor-id="bibliografía">Bibliografía</h2>
<p>Bizquerra, R &amp; Pérez, N. (2007). Las competencias emocionales. Educación XX1, (10), 61-82. https://hdl.handle.net/2445/111324</p>
<p>Carretero, R. &amp; Nolasco, A. (2017). Aproximación al concepto de emocionalidad, El estereotipo emocional del sexismo. Revista de Estudios e Investigación en Psicología y Educación, 4 (1), 31-41. https://doi.org/10.17979/reipe.2017.4.1.1545</p>
<p>López, M. (2007). Ansiedad y depresión, reacciones emocionales frente a la enfermedad. Anales de Medicina interna, 24 (5), 209-211. https://scielo.isciii.es/pdf/ami/v24n5/editorial.pdf</p>
<p>Ortega, María del Carmen. (2010). La educación emocional y sus implicaciones en la salud. Revista Española de Orientación y Psicopedagogía, 21 (2), 462-470. https://www.redalyc.org/pdf/3382/338230785025.pdf</p>
<p>Pulido, F. &amp; Herrera, F. (2018). Relaciones entre felicidad, inteligencia emocional y factores sociodemográficos en secundaria. Anuario de psicología, 48 (1), 34-42. https://doi.org/10.1016/j.anpsic.2018.04.002</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>