<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Bianca Balmaceda">
<meta name="author" content="Matías Flores">
<meta name="author" content="Joaquín Nuñez">
<meta name="author" content="Andrés Rendic">
<meta name="author" content="Amalia Santa Cruz">

<title>Percepciones del funcionamiento de la democracia según nivel educacional según posición política</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="reporte_files/libs/clipboard/clipboard.min.js"></script>
<script src="reporte_files/libs/quarto-html/quarto.js"></script>
<script src="reporte_files/libs/quarto-html/popper.min.js"></script>
<script src="reporte_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="reporte_files/libs/quarto-html/anchor.min.js"></script>
<link href="reporte_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="reporte_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="reporte_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="reporte_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="reporte_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Percepciones del funcionamiento de la democracia según nivel educacional según posición política</h1>
<p class="subtitle lead">Estadística Correlacional 2024, Carrera de Sociología - Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Bianca Balmaceda </p>
             <p>Matías Flores </p>
             <p>Joaquín Nuñez </p>
             <p>Andrés Rendic </p>
             <p>Amalia Santa Cruz </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">1 de diciembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    El presente trabajo tiene como objetivo analizar el nivel educacional de los encuestados y su percepción sobre el funcionamiento de la democracia y la posición política subjetiva. Para lograr esto se seleccionó la variable dependiente “¿Qué tan bien o qué tan mal cree Ud. que funciona la democracia en Chile?” y las variables independientes sobre nivel educacional, posicionamiento político en una escala, y extremismo político. Primero se presentan los estadísticos descriptivos de las variables y luego los análisis bivariados entre estas (tablas y gráficos de asociación). Resultados preliminares indican que no existe evidencia suficiente para hablar de una relación considerable entre las variables propuestas.
  </div>
</div>


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Con los resultados de las últimas elecciones municipales en Chile, quedó en evidencia la indiferencia generalizada por los procesos electorales, pilar fundamental de la democracia. Según un análisis de CIPER (Espinoza y Ríos, 2024), en la elección de concejales, el número de votos nulos y en blanco a escala nacional fue mayor que el de la lista con mejores resultados de esa elección. Comparando las elecciones municipales de 2021 (con el sistema de inscripción automática y voto voluntario) y las de 2024 (con inscripción automática y voto obligatorio), en la primera hubo una participación de 43,41% , con un 1,94% de votos nulos y blancos en la elección de alcaldes y un 5,74% en las de concejales, mientras que en las de 2024 la participación fue de un 84,87% y el porcentaje de nulos y blancos en alcaldes alcanzó un 10,72% y concejales un 21,46%, superior al 15,52% obtenido por la lista RN-IND (lista I).</p>
<p>A partir de esto surge la problemática ¿Por qué a la gente en Chile no le interesa participar en las elecciones? De acuerdo con este cuestionamiento, la literatura señala a la educación como uno de los factores críticos en las actitudes y percepciones de la democracia (Cuenca, 2020; Stojnic Chávez, 2016), también señala cómo el nivel educativo influye en el compromiso político y la tendencia a la polarización política (Pérez, 2022). De este modo, se pretende analizar cómo se asocia el nivel educacional y la posición política con la percepción del funcionamiento de la democracia en el Chile en la actualidad</p>
<p>En este sentido, definiremos la percepción del funcionamiento de la democracia en el sentido de satisfacción con la democracia según Linde y Ekman (2003) entendida como medida de evaluación sobre el funcionamiento de la democracia en la práctica, o sea el gobierno en sí, más que el acuerdo con los principios de la democracia. Para analizar la educación, esta será trabajada en base al nivel educativo, la etapa de formación educativa formal que se haya alcanzado (Básica, Media, etc.). La relevancia de esta se ve justificada por investigaciones como la de Perez (2020) que señala que “Los sujetos con mayor nivel de estudios participan más activamente en política, mientras que los sujetos con menor nivel educativo lo hacen en una menor medida.” resaltando la relación entre nivel de estudios y pensamiento político. En cuanto a la posición política, será abordada como la “identificación o simpatía con sectores políticos de izquierda a derecha” (Castillo, 2012), entendido como un espectro bajo el cuál las personas se alinean ideológicamente según sus creencias o ideas y actitudes sobre la sociedad y los individuos que la conforman (Adorno, 1964; Converse, 1964).</p>
<pre><code>De este modo, el objetivo del trabajo será analizar cómo la percepción del funcionamiento de la democracia se asocia con el nivel educacional y la posición política. Para este análisis se plantean 3 hipótesis: en primer lugar, que las personas con menor nivel educacional tengan una peor percepción sobre el funcionamiento de la democracia; en segundo lugar, que mientras más de derecha se identifique una persona, mejor sea su percepción del funcionamiento de la democracia; y en tercer lugar, que las personas con posicionamientos más extremos políticamente (1-2, 9-10) tengan una peor percepción sobre el funcionamiento de la democracia que quienes no tienen posiciones políticas extremas. </code></pre>
</section>
<section id="metodología" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metodología</h1>
<section id="datos" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="datos"><span class="header-section-number">2.1</span> Datos</h2>
<p>Para el análisis propuesto, los datos a utilizar son los de la Encuesta CEP número 89 (Centro de Estudios, Junio-Julio 2023 Nº89) con una población de personas de al menos 18 años y residentes de Chile. La muestra es de 1.467 personas, las cuales fueron entrevistadas en sus hogares, de manera cara a cara, entre las fechas del 31 de mayo al 12 de julio de 2023. Además, se estima que el error muestral es de ± 2,8% con un nivel de confianza del 95%.</p>
</section>
<section id="variables" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variables"><span class="header-section-number">2.2</span> Variables</h2>
<p>Variable dependiente:</p>
<p>MD_2. ¿Qué tan bien o qué tan mal cree Ud. que funciona la democracia en Chile? (democracia_20) Leer alternativas 1 Muy bien 2 Bien 3 Regular 4 Mal 5 Muy mal 8 No sabe (no leer) 9 No contesta (no leer)</p>
<p>Esta variable da cuenta de una percepción subjetiva de las personas acerca del funcionamiento de la democracia en Chile. Indica las valoraciones personales de los individuos sobre la calidad del funcionamiento del sistema democrático en el país.</p>
<p>La variable MD_2 es operacionalizada mediante una pregunta directa: “¿Qué tan bien o qué tan mal cree Ud. que funciona la democracia en Chile?”, la cual tiene 5 categorías de respuesta que indican el grado de satisfacción o insatisfacción con el funcionamiento de la democracia.</p>
<p>Se mide con una escala Likert ordinal, que representa las respuestas cualitativas sobre el funcionamiento de la democracia en Chile. Además, las categorías 8 y 9 se utilizan para recodificar las respuestas en las que el encuestado no sabe o no contesta respectivamente. Es una variable ordinal. La variable es recodificada para invertir su sentido, en pos de facilitar un análisis bivariado con otras variables de interés.</p>
<p>Variables independientes:</p>
<ol type="1">
<li>MB_9 (iden_pol_2): Los conceptos de izquierda y derecha son útiles para resumir de una manera muy simplificada lo que piensa la gente en muchos temas. Me gustaría que por favor se clasificara en la escala que va de 1 a 10 donde 1 representa a la izquierda y 10 representa a la derecha. 1 2 3 4 5 6 7 8 9 10 Izquierda Derecha</li>
</ol>
<p>88 No sabe (no leer) 99 No contesta (no leer)</p>
<p>Esta variable indica cómo los individuos se autoubican ideológicamente en el campo político, desde izquierda a derecha. Da cuenta de la autopercepción de las personas con respecto a la política.</p>
<p>La variable MB_9 se operacionaliza con una escala numérica continua. En esta los encuestados se deben posicionar en un rango del 1 al 10, siendo 1 el extremo de izquierda, y 10 el extremo de derecha.</p>
<p>Se mide con una escala de intervalo, en la cual la distancia entre los números es igual. Los individuos deben seleccionar el número que los represente de mejor manera en su posicionamiento político, en relación a los conceptos de izquierda y derecha. La escala nos permite analizar las tendencias ideológicas de los encuestados. Además, las categorías 88 y 99 se utilizan para recodificar las respuestas en las que el encuestado no sabe o no contesta respectivamente como valores perdidos. Se considera una variable intervalar.</p>
<ol start="2" type="1">
<li>Extremismo en política (ext.politica): en base a la variable anterior, se dividirá entre los valores extremos de izquierda y derecha (1, 2, 9, y 10), y los de centro (3, 4, 5, 6, 7, y 8), creando una nueva variable dicotómica que distingue entre extremos ideológicos y posiciones más centrales.</li>
</ol>
<p>Esta variable indica si los individuos corresponden a personas con una ideología más extrema, o si adscriben una visión más centrista en términos políticos.</p>
<ol start="3" type="1">
<li>SD_5 (esc_nivel_1) ¿Cuál es su nivel educacional? Es decir, el nivel que está cursando actualmente o el nivel ya cumplido.</li>
</ol>
<p>0 Sin estudios formales<br>
1 Básica incompleta / primaria o preparatoria incompleta<br>
2 Básica completa / primaria o preparatoria completa<br>
3 Media científico humanista o media técnico profesional incompleta / humanidades incompletas<br>
4 Media científico humanista o media técnico profesional completa / humanidades completa<br>
5 Instituto técnico (cft) o instituto profesional incompleto (carreras 1 a 3 años)<br>
6 Instituto técnico (cft) o instituto profesional completo (carreras 1 a 3 años) / hasta suboficial de ffaa/carabineros<br>
7 Universitaria incompleta (carreras 4 o más años)<br>
8 Universitaria completa (carreras 4 o más años) / oficial de ffaa/carabineros<br>
9 Postgrado (postítulo, master, magíster, doctor) incompleto<br>
10 Postgrado (postítulo, master, magíster, doctor) completo<br>
88 No sabe (no leer)<br>
99 No contesta (no leer)</p>
<p>Esta variable indica el nivel educacional actual de los encuestados, o en otras palabras, el nivel de estudios que esta cursando al momento de la realización de la encuesta. Da cuenta del grado de avance en el sistema educativo.</p>
<p>La variable SD_5 se operacionaliza mediante una pregunta directa: “¿Cuál es su nivel educacional? Es decir, el nivel que está cursando actualmente.” Esta pregunta tiene 10 categorías de respuesta que dan cuenta del nivel educacional del encuestado.</p>
<p>Es una variable ordinal, en la que las categorías están ordenadas jerárquicamente. Además, las categorías 88 y 99 se utilizan para recodificar las respuestas en las que el encuestado no sabe o no contesta respectivamente.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dfSummary</span>(CEP.selected) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  summarytools<span class="sc">::</span><span class="fu">view</span>(<span class="at">method =</span> <span class="st">"render"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-1" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="container st-container">
<h3 class="anchored">Data Frame Summary</h3>
<h4 class="anchored">CEP.selected</h4>
<strong>Dimensions</strong>: 1467 x 4
  <br><strong>Duplicates</strong>: 1146
<br>

<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>No</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Variable</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Stats / Values</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Freqs (% of Valid)</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Graph</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Valid</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Missing</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">dem.opi [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 2.7 (0.8)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 3 ≤ 5</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 1 (0.3)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">140</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">373</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">26.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">731</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">52.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">144</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">18</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">1.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAFoAAAB9CAQAAACICLwHAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfoDAIDBRbS3+mIAAABDklEQVR42u3bUWrCUBRF0aY4RwfR8dQ5dJT19yXUSCAv99yy9p+IsJBnIAez/H7067MaAJ3cbXzxeHPAv5Y66Ei7rd+673zsp068qeXxgIaGDggaGjogaGjogFqiN3cuOXcney3jvVfhLeDbRmfL4wF9Vasf4vfJw96sneTA7nG0eVeilscDGho6IGho6ICgoaEDgr4qY83MjDUVTd09Tm04uxN3jzNbXyBaHg9oaOiAoKGhA4KGhg4I+qrsHjOze1R0aPeofM7lJdpzLtDQ0NBxQUNDBwQNDR1QS7TdY2Z2j4r+2D1S1o3Xbb7p1P977KJ7BA0NHRA0NHRA0NDQAUEXoRvuHl36D8ejRy3RT1NLHUImWhCpAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1406 (95.8%)</td>
<td style="text-align: center;">61 (4.2%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">pos.politica [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 5.3 (2.4)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 5 ≤ 10</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 2 (0.4)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">96</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">9.1%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">28</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">2.7%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">68</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">6.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">96</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">9.1%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">416</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">39.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">6</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">93</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">8.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">7</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">79</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">7.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">8</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">49</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">4.7%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">9</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">21</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">2.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">10</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">104</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">9.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAEgAAADzCAQAAACP6Zh6AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfoDAIDBRbS3+mIAAABkElEQVR42u3cy03DQBiFUYLSY4qgHuiBKmEVsGH8mMXM/S2db4cQ4ihjS7kK+Pb1UqvXNACot/vyi4+dC+rtNg6x/LX39bceGz/yOfZlWVTuyICAgIDSAQEBAaX7845x3jvDrW7L97MD3zbvtjSUOzKgo1YX9fvPYY5cYR2g5y5L3mvljgwICAgoHRAQEFA6u6yVXXZp0MYu+232Qjv4vGz+XVfuyICAgIDSAQEBAaWzy1rZZT0dzqBns+aQPxsEAgJKBwQEBJQO6HIgu6yVXdbT6V02tMW1cnKXjWx9I5U7MiAgIKB0QEBAQOnKgeyyVnZZTz4vO6rckQEBAQGlAwICAkpXDmSXtbLLejq1y2b+S9eJXTb3Qi93ZEBAQEDpgICAgNKVA9llreyynnZ3WeIhiDu7LHOBlzsyICAgoHRAQEBA6cygVmbQpUHNXZZ7KP2/V+gR+Q+zHVA+ICAgoHRAQEBA6eyyVnbZpUFdz/2Ysdc6nvsx5w4sd2RAQEBA6YCAgIDS1d5lFSp3ZEBHfQPn7zroUrxvfQAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1050 (71.6%)</td>
<td style="text-align: center;">417 (28.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">ext.politica [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Min : 0</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean : 0.2</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Max : 1</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">0</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">801</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">76.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">249</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">23.7%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAH8AAAA3CAQAAACPv12ZAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfoDAIDBRbS3+mIAAAAnUlEQVRo3u3ZsQ2AIBQAUTDu6A46j+7AlNqCiQ2RkJ+719EQLgEKyHciW2YvwHzzZ1nrwYW4CPb8kZ/SNnttw5VmBN/85pOZT2Y+mflk5pOZT2Y+mflk5pO93vpK3yxh5fpxN3dPE0ldDN/88Pzm7J8/fXMcYU7RgG+OSNcnfPObT2Y+mflk5pOZT2Y+mflk5pOZT+Y3Bxl885tP9gAaiQvHvrEqJAAAAD10RVh0aWNjOmNvcHlyaWdodABDb3B5cmlnaHQgMjAwNyBBcHBsZSBJbmMuLCBhbGwgcmlnaHRzIHJlc2VydmVkLp5m3CkAAAAjdEVYdGljYzpkZXNjcmlwdGlvbgBHZW5lcmljIFJHQiBQcm9maWxlGqc4jgAAAABJRU5ErkJggg==" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1050 (71.6%)</td>
<td style="text-align: center;">417 (28.4%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">educ [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 4.3 (2.3)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">0 ≤ 4 ≤ 10</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 3 (0.5)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle;">11 distinct values</td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAJgAAABuCAQAAABxABKuAAAAAmJLR0QA/4ePzL8AAAAHdElNRQfoDAIDBRbS3+mIAAABjElEQVR42u3cQU6DQABAUTG9o3fQ89Q7eErdoklHXgNS5L9d06R0foZJgWamz6eI572/wNEUDBUMXeYvpg0OcB0ukm9bHHJ18yFc7v6UxV5uvvOxd4k7dEqigqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqGCoYKhgqFV9t65nmjXtpU2K/pfGxKNLA52plk0AjPsPLNo5Fuw48+i7bd3+zHDHmcWjYY+GvjWI/iDHerudWvo+y4A/Q5DBUMFQwVDBUMFQwVDBUMFQwVDBUMFQwVDBUMFQwVDD3wD8bY9b6UfMtieN9J3Dna8xy47B3uchy5LteijgqGCoYKhgqGCoYKhgqFDXhqt75crjtm/hU4VbJRl6TXHqYKtcSHWGoYKhqb5af1+uJstf+N1tuhPNTKdkqhgqGDoCwrZIgTkswPGAAAAPXRFWHRpY2M6Y29weXJpZ2h0AENvcHlyaWdodCAyMDA3IEFwcGxlIEluYy4sIGFsbCByaWdodHMgcmVzZXJ2ZWQunmbcKQAAACN0RVh0aWNjOmRlc2NyaXB0aW9uAEdlbmVyaWMgUkdCIFByb2ZpbGUapziOAAAAAElFTkSuQmCC" class="img-fluid figure-img" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1462 (99.7%)</td>
<td style="text-align: center;">5 (0.3%)</td>
</tr>
</tbody>
</table>

<p>Generated by <a href="https://github.com/dcomtois/summarytools">summarytools</a> 1.0.1 (<a href="https://www.r-project.org/">R</a> version 4.4.2)<br>2024-12-02</p>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Tabla: Descriptivos de variables
</figcaption>
</figure>
</div>
</div>
</section>
<section id="métodos" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="métodos"><span class="header-section-number">2.3</span> Métodos</h2>
<p>Los métodos estadísticos utilizados para el contraste de hipótesis y el cálculo de tamaño de efecto fueron múltiples, dependiendo de la naturaleza de la relación entre variables de interés.</p>
<p>En el caso de la hipótesis 1, utilizamos el test de correlación de Kendall para medir la relación entre nivel educacional y la percepción sobre el funcionamiento, ya que se trata de dos variables ordinales, y el uso de esta prueba nos permite evitar problemas de empate, los cuales surgían al utilizar otro tipo de pruebas debido al tamaño de la muestra.</p>
<p>Pasando a las hipótesis 2 y 3, decidimos utilizar el test de Pearson, ya que podemos asumir que se cumplen supuestos de normalidad. En el caso de la tercera hipótesis, sin embargo, la consideramos una prueba de punto biserial, ya que estamos hablando de una variable dicotómica y una variable ordinal; por ende, solo podemos hablar de su tamaño de efecto entre -1 y 1, no de su sentido.</p>
</section>
</section>
<section id="análisis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análisis</h1>
<section id="análisis-descriptivo" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="análisis-descriptivo"><span class="header-section-number">3.1</span> Análisis descriptivo</h2>
<p>En la posición política la mayoría de las respuestas se posicionan en el centro, y hay 417 valores perdidos. En el nivel de estudios la mayoría de los encuestados está en la categoría “Media científico humanista o media técnico profesional completa / humanidades completa”. En la opinión sobre la democracia la mayoría de las respuestas son de percepción regular sobre el funcionamiento de la democracia. Y en la variable recodificada de posición política se indica que la gran mayoría de los encuestados no están dentro de los extremos sobre opinión política.</p>
</section>
<section id="análisis-estadístico-bivariado" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="análisis-estadístico-bivariado"><span class="header-section-number">3.2</span> Análisis estadístico bivariado</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_xtab</span>(CEP.selected<span class="sc">$</span>educ, CEP.selected<span class="sc">$</span>dem.opi, <span class="at">show.row.prc =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-2" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
educ
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">
dem.opi
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Muy mal
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Mal
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Regular
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Bien
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Muy bien
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
0
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8</span><br><span style="color:#333399;">53.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6</span><br><span style="color:#333399;">40&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">6.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">15</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">13</span><br><span style="color:#333399;">9.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">46</span><br><span style="color:#333399;">34.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">62</span><br><span style="color:#333399;">47&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">5.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">132</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
2
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">17</span><br><span style="color:#333399;">11&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">41</span><br><span style="color:#333399;">26.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">86</span><br><span style="color:#333399;">55.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9</span><br><span style="color:#333399;">5.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2</span><br><span style="color:#333399;">1.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">155</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
3
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">16</span><br><span style="color:#333399;">9.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">57</span><br><span style="color:#333399;">32.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">86</span><br><span style="color:#333399;">49.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">15</span><br><span style="color:#333399;">8.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">174</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
4
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">57</span><br><span style="color:#333399;">13.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">113</span><br><span style="color:#333399;">26&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">217</span><br><span style="color:#333399;">50&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">44</span><br><span style="color:#333399;">10.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span style="color:#333399;">0.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">434</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
5
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">10.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">17</span><br><span style="color:#333399;">26.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">34</span><br><span style="color:#333399;">52.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6</span><br><span style="color:#333399;">9.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">1.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">65</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
6
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">15</span><br><span style="color:#333399;">9.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">40</span><br><span style="color:#333399;">25.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">84</span><br><span style="color:#333399;">54.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">15</span><br><span style="color:#333399;">9.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">0.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">155</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
7
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">5.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">14</span><br><span style="color:#333399;">18.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">46</span><br><span style="color:#333399;">61.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11</span><br><span style="color:#333399;">14.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">75</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
8
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9</span><br><span style="color:#333399;">5.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">30</span><br><span style="color:#333399;">18.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">92</span><br><span style="color:#333399;">57.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">25</span><br><span style="color:#333399;">15.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span style="color:#333399;">1.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">159</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
9
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2</span><br><span style="color:#333399;">12.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8</span><br><span style="color:#333399;">50&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">25&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2</span><br><span style="color:#333399;">12.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">16</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
10
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">4.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span style="color:#333399;">13.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9</span><br><span style="color:#333399;">40.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">31.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">2</span><br><span style="color:#333399;">9.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">22</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">139</span><br><span style="color:#333399;">9.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">371</span><br><span style="color:#333399;">26.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">730</span><br><span style="color:#333399;">52.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">144</span><br><span style="color:#333399;">10.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">18</span><br><span style="color:#333399;">1.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1402</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="7">
χ<sup>2</sup>=97.119 · df=40 · Cramer’s V=0.132 · Fisher’s p=0.001
</td>
</tr>
</tbody></table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Tabla: Correlación 1
</figcaption>
</figure>
</div>
</div>
<p>La tabla de contingencia muestra la correlación entre el nivel educacional de los encuestados y su percepción sobre el funcionamiento de la democracia. Por un lado, la percepción más repetida es la “Regular” con 52.1%, y le sigue “Mal” con 26.5%. Por otro lado, la percepción menos común es “Muy bien” con 1.3%, y le sigue “Muy mal” con 9.9%. Estas últimas son las categorías extremas, lo que indica que la mayoría de los encuestados tienen una opinión moderada sobre el funcionamiento de la democracia.</p>
<p>En cuanto a los niveles educacionales, de las personas que no tienen estudios formales (0) el 53.3% respondió la opción “Mal”. En las categorías de educación básica (1 y 2) el 47% y el 55.5% tiene una percepción “Regular” sobre el funcionamiento de la democracia. En las categorías de educación media (3 y 4) el 49.4% y el 50% respondieron “Regular”. En las categorías de educación técnica (5 y 6) la percepción que más se repite es “Regular” con 52.3% 54.2%. En las categorías de educación universitaria (7 y 8) la mayoría tiene una percepción “Regular” con 61.3% y con 57.9%. En estas, las opciones “Mal” y “Bien”, tienen porcentajes de respuesta más cercanos. En cambio, en las otras categorías la respuesta “Mal” tiene una gran diferencia numérica con la respuesta “Bien”. Por último, las categorías de educación de postgrado (9 y 10), que es la muestra más pequeña. En esta la respuesta más común es “Regular” con 50% y 40.9% respectivamente. Además, la siguiente opción con mayor porcentaje es “Bien”, siendo esta la única categoría en la que hay una cambio en las tendencias de respuesta, puesto que en todas las otras la segunda opción con mayor porcentaje es “Mal”.</p>
<p>En relación con los estadísticos de asociación, el chi cuadrado es de 78.755, con 16 grados de libertad, y un p de 0.000, esto demuestra que existe una relación significativa entre el nivel educativo y la percepción de la democracia. La v de Cramer tiene un valor de 0.119, lo que indica que a pesar de que existe una relación estadísticamente significativa, esta es una relación de asociación débil. Además, el valor del coeficiente de Kendall (0.117) indica una correlación positiva muy débil entre las dos variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(CEP.selected<span class="sc">$</span>dem.opi,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>         CEP.selected<span class="sc">$</span>educ,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"kendall"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kendall's rank correlation tau

data:  CEP.selected$dem.opi and CEP.selected$educ
z = 5.3708, p-value = 0.00000007837
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.1175915 </code></pre>
</div>
</div>
<p>La hipótesis “se espera que las personas con menor nivel educacional tengan una peor percepción sobre el funcionamiento de la democracia”, se cumple, puesto que las personas que no tienen estudios formales contestaron en su mayoría que tienen una percepción mala sobre el funcionamiento de la democracia. Mientras que el nivel educativo de postgrado es el único con la segunda categoría de respuesta “Bien”. Sin embargo, la percepción “Regular” sobre el funcionamiento de la democracia es la respuesta que más porcentajes tiene en todas las otras categorías educativas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_xtab</span>(CEP.selected<span class="sc">$</span>pos.politica, CEP.selected<span class="sc">$</span>dem.opi, <span class="at">show.row.prc =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-3" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
pos.politica
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">
dem.opi
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Muy mal
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Mal
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Regular
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Bien
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Muy bien
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
1
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">7.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">16</span><br><span style="color:#333399;">17.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">47</span><br><span style="color:#333399;">50.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">20</span><br><span style="color:#333399;">21.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span style="color:#333399;">3.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">93</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
2
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">14.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5</span><br><span style="color:#333399;">18.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">14</span><br><span style="color:#333399;">51.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">14.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">27</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
3
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">1.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8</span><br><span style="color:#333399;">11.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">44</span><br><span style="color:#333399;">64.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">15</span><br><span style="color:#333399;">22.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">68</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
4
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">7.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11</span><br><span style="color:#333399;">11.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">61</span><br><span style="color:#333399;">63.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">13</span><br><span style="color:#333399;">13.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">4.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">96</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
5
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">44</span><br><span style="color:#333399;">10.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">107</span><br><span style="color:#333399;">26.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">223</span><br><span style="color:#333399;">54.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">31</span><br><span style="color:#333399;">7.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5</span><br><span style="color:#333399;">1.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">410</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
6
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">4</span><br><span style="color:#333399;">4.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">26</span><br><span style="color:#333399;">28.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">50</span><br><span style="color:#333399;">54.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">10</span><br><span style="color:#333399;">11&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">1.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">91</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
7
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6</span><br><span style="color:#333399;">7.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">20</span><br><span style="color:#333399;">25.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">47</span><br><span style="color:#333399;">60.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5</span><br><span style="color:#333399;">6.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">78</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
8
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">8</span><br><span style="color:#333399;">16.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11</span><br><span style="color:#333399;">22.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">21</span><br><span style="color:#333399;">43.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">14.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">1</span><br><span style="color:#333399;">2.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">48</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
9
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span style="color:#333399;">14.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6</span><br><span style="color:#333399;">28.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">7</span><br><span style="color:#333399;">33.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">5</span><br><span style="color:#333399;">23.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">21</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
10
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">16</span><br><span style="color:#333399;">15.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">27</span><br><span style="color:#333399;">26.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">46</span><br><span style="color:#333399;">45.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">9</span><br><span style="color:#333399;">8.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">3</span><br><span style="color:#333399;">3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">101</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">100</span><br><span style="color:#333399;">9.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">237</span><br><span style="color:#333399;">22.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">560</span><br><span style="color:#333399;">54.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">119</span><br><span style="color:#333399;">11.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">17</span><br><span style="color:#333399;">1.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1033</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="7">
χ<sup>2</sup>=75.874 · df=36 · Cramer’s V=0.136 · Fisher’s p=0.000
</td>
</tr>
</tbody></table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Tabla: Correlación 2
</figcaption>
</figure>
</div>
</div>
<p>La segunda tabla de contingencia representa la correlación entre la posición política de los encuestados y su percepción sobre el funcionamiento de la democracia al momento en el que se aplicó la encuesta. En cuanto a la opinión sobre la democracia, la respuesta más común fue “regular” con un 54.2%, seguida, aunque con casi la mitad de respuestas, “mal” con un 22.9%. Por otro lado, las opciones menos respondidas fueron “muy bien” con un 1.6%, “muy mal” con un 9.7% y “bien” con un 11.5%. Estos porcentajes representan una clara tendencia por percepciones moderadas sobre qué tan bien funciona la democracia, con una leve tendencia hacia puntajes más negativos.</p>
<p>Por otro lado, la variable de posición política está representada por una escala ideológica en donde, 1 representa izquierda, y 10 derecha. Por lo que las posiciones centrales representan posicionamientos moderados, siendo 5 y 6 los valores más vinculados al centro. En este caso se da cuenta de una muestra en la cual casi la mitad de las personas encuestadas (501 de 1033) se identifican con ideologías de centro. Con respecto a los demás posicionamientos, podemos identificar una muestra bastante homogénea con una leve tendencia a ideologías moderadas.</p>
<p>Al cruzar ambas variables se da cuenta tanto en la izquierda (valores 1 y 2 = 50.8%) como en la izquierda moderada (valores 3 y 4 = 64%) más de la mayoría evalúa el funcionamiento de la democracia como “regular”. La segunda tendencia en posiciones de izquierda es “bien”, en el primer caso con un 20% y en el segundo con un 17.1%. En la posición de centro (valores 5 y 6) ocurre algo parecido. Más de la mitad (54.5%) tiene una percepción “regular” sobre el funcionamiento de la democracia. Sin embargo, hay una clara diferencia que se manifiesta en una actitud más crítica e inclinada hacia “muy mal” (9.6%) y “mal” (26.5%). Por otro lado, los posicionamientos ideológicos de derecha se diferencian un poco más entre ellos, aunque ambos tienen una peor percepción de la democracia. La mayoría de la derecha moderada (valores 7 y 8) tiene una opinión “regular” (54%) a diferencia de la derecha (valores 9 y 10) donde menos de la mitad (43.4%) responde eso. En ambas posiciones la opción que sigue es “mal”, con un 24.6% en el primer caso, y un 27% en el segundo caso, seguido de un 11.1% y un 15.6% respectivamente, en la opción “muy mal”.</p>
<p>En relación con los estadísticos de asociación, el chi cuadrado es de 75.874, con 36 grados de libertad, y un p de 0.000, esto demuestra que existe una relación significativa entre la posición política y la percepción de la democracia. La v de Cramer tiene un valor de 0.136, lo que indica que a pesar de que existe una relación estadísticamente significativa, esta es una relación de asociación débil. Además, el valor del coeficiente de Pearson (-0.125) indica una correlación negativa y débil entre las dos variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(CEP.selected<span class="sc">$</span>dem.opi,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>         CEP.selected<span class="sc">$</span>pos.politica,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  CEP.selected$dem.opi and CEP.selected$pos.politica
t = -4.0757, df = 1031, p-value = 0.00004939
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.18549333 -0.06543177
sample estimates:
       cor 
-0.1259236 </code></pre>
</div>
</div>
<p>Respecto a esto, y en contra de lo esperado, la segunda hipótesis puede ser refutada. Se esperaba encontrar una relación entre mejor percepción de la democracia y la derecha, cosa que se contradice con los resultados. A partir de ellos es posible concluir que la izquierda se presenta levemente más conforme respecto al funcionamiento de la democracia, a diferencia de la derecha, que adopta una actitud más crítica respecto a cómo debiera funcionar.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sjPlot<span class="sc">::</span><span class="fu">tab_xtab</span>(CEP.selected<span class="sc">$</span>ext.politica, CEP.selected<span class="sc">$</span>dem.opi, <span class="at">show.row.prc =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-4" class="cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table style="border-collapse:collapse; border:none;">
<tbody><tr>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">
ext.politica
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">
dem.opi
</th>
<th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">
Total
</th>
</tr>
<tr>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Muy mal
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Mal
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Regular
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Bien
</td>
<td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">
Muy bien
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
No extremista
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">70</span><br><span style="color:#333399;">8.8&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">183</span><br><span style="color:#333399;">23.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">446</span><br><span style="color:#333399;">56.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">81</span><br><span style="color:#333399;">10.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">11</span><br><span style="color:#333399;">1.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">791</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">
Extremista
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">30</span><br><span style="color:#333399;">12.4&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">54</span><br><span style="color:#333399;">22.3&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">114</span><br><span style="color:#333399;">47.1&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">38</span><br><span style="color:#333399;">15.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center; ">
<span style="color:black;">6</span><br><span style="color:#333399;">2.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;  ">
<span style="color:black;">242</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr>
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">
Total
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">100</span><br><span style="color:#333399;">9.7&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">237</span><br><span style="color:#333399;">22.9&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">560</span><br><span style="color:#333399;">54.2&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">119</span><br><span style="color:#333399;">11.5&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">17</span><br><span style="color:#333399;">1.6&nbsp;%</span>
</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;">
<span style="color:black;">1033</span><br><span style="color:#333399;">100&nbsp;%</span>
</td>
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="7">
χ<sup>2</sup>=11.539 · df=4 · Cramer’s V=0.106 · Fisher’s p=0.015
</td>
</tr>
</tbody></table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Tabla: Correlación 3
</figcaption>
</figure>
</div>
</div>
<p>En esta tabla se presentan las relaciones entre las variables de opinión sobre la percepción de la democracia y posicionamientos considerados como “extremistas” y “no extremistas” en cuanto a posicionamiento político. Dentro de los valores extremistas se consideró 1 y 2 como valores más extremos de izquierda y, 9 y 10, como valores más extremos de derecha. Quedando así dentro de la categoría “no extremista” los valores 3, 4, 5, 6, 7 y 8.</p>
<p>En el grupo “no extremista”, el porcentaje mayor (56.4%) se encuentra en la categoría “regular” en cuanto a evaluación del funcionamiento de la democracia, sin embargo, se encuentra bastante distribuido entre las demás categorías, aunque con una leve tendencia a una mala percepción. El grupo extremista también presenta mayor concentración de respuesta en la categoría “regular” (47.1%). Si bien su segunda opción más repetida es “mal” (22.3%), presenta mayor concentración que el otro grupo en las categorías de “bien” (15.7%) y “muy bien” (2.5%).</p>
<p>La hipótesis de que las personas con posicionamientos más extremos políticamente (1-2, 9-10), tienen una peor percepción sobre el funcionamiento de la democracia en comparación quienes no tienen posicionamientos políticos extremos es rechazada, puesto que ambos grupos tienen en su mayoría una tendencia hacia la percepción regular del funcionamiento de la democracia. Además, la correlación de Pearson (0.006) y el valor p &gt; 0.05 indica que no hay una asociación significativa estadísticamente entre las variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(CEP.selected<span class="sc">$</span>dem.opi,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>         CEP.selected<span class="sc">$</span>ext.politica,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  CEP.selected$dem.opi and CEP.selected$ext.politica
t = 0.21872, df = 1031, p-value = 0.8269
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.05420539  0.06777779
sample estimates:
        cor 
0.006811541 </code></pre>
</div>
</div>
</section>
</section>
<section id="conclusiones" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusiones</h1>
<p>En conclusión se aprueba la hipótesis de que las personas con menor nivel educacional tienen una peor percepción sobre el funcionamiento de la democracia, las personas sin estudios formales en su mayoría tenían una mala percepción sobre el funcionamiento de la democracia. A pesar de esto, todas las otras categorías educativas tenían en su mayoría la percepción regular sobre el funcionamiento de la democracia. Además, el coeficiente de Kendall indica una correlación positiva muy débil entre las variables de educación y percepción sobre el funcionamiento de la democracia.</p>
<p>Por otro lado, en contra de lo esperado, se rechazan la segunda y la tercera hipótesis. En cuanto a la segunda, se esperaba encontrar una relación positiva respecto a ser de derecha y tener una buena percepción sobre el funcionamiento de la democracia. Se encontró que tanto en posicionamientos de derecha, como de centro y de izquierda, la categoría más repetida fue “regular”. Se muestra que la derecha tiene una percepción levemente inclinada hacia “mal” y “muy mal”, a diferencia de la izquierda que fue el grupo que presentó mejor percepción sobre el funcionamiento de este sistema. Además, los resultados de la correlación de Pearson muestran una correlación negativa y débil entre las dos variables, aunque estadísticamente significativa.</p>
<p>En cuanto a la tercera, no se encontró que las personas con posicionamiento políticos más extremos tenían una peor percepción sobre el funcionamiento de la democracia en comparación con las personas que no tenían posiciones políticas extremas. Además, la correlación entre las variables de percepción de la democracia y posición política extrema o no extrema no es significativa estadísticamente.</p>
<p>Sobre las limitaciones se encontró que en general las variables independientes escogidas no tenían efecto significativo sobre la percepción de la democracia. Al ser ambas variables medidas en solo una pregunta no permite formar una medición matizada de los conceptos. Esto se podría mejorar componiendo un índice para cada variable que pueda capturar cada concepto de forma más completa. Por ejemplo, un índice para nivel de educación que incluya si tuvo clases de educación cívica durante su formación y actividades de participación ciudadana.</p>
</section>
<section id="bibliografía" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bibliografía</h1>
<p>Cuenca, R. (2020). Educación y democracia en América Latina: un asunto de desarrollo sostenible. Profesorado, Revista De Currículum Y Formación Del Profesorado, 24(3), 27–47. https://doi.org/10.30827/profesorado.v24i3.13213</p>
<p>Espinoza, R. y Ríos, D. (29 de octubre de 2024). Elecciones 2024: La “lista ganadora”, análisis geográfico al fenómeno de los votos nulos y blancos. CIPER Chile .https://www.ciperchile.cl/2024/10/29/elecciones-2024-la-lista-ganadora-analisis-geografico-al-fenomeno-de-los-votos-nulos-y-blancos/</p>
<p>Linde, J. y Ekman, J. (2003), Satisfaction with democracy: A note on a frequently used indicator in comparative politics. European Journal of Political Research, 42: 391-408. https://doi.org/10.1111/1475-6765.00089</p>
<p>Pérez , P. (2022). Como la polarización política amenaza la democracia… y cómo afrontarlo. Análisis Político, 35(104), 91-111. Epub December 13, 2022. https://doi.org/10.15446/anpol.v35n104.105167</p>
<p>Stojnic Chávez, L. (2016). Estudiantes peruanos y el autorreconocimiento de su poder público: ¿cuánto influye la educación universitaria?. Debates En Sociología, (43), 5-30. https://doi.org/10.18800/debatesensociologia.201602.001</p>
<p>Castillo, J. C., Miranda, D., &amp; Carrasco, D. (2012). Percepción de Desigualdad Económica en Chile: Medición, Diferencias y Determinantes. Psykhe (Santiago), 21(1), 99-114. https://www.scielo.cl/scielo.php?script=sci_arttext&amp;pid=S0718-22282012000100007</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>