<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gaspar Duclos">
<meta name="author" content="Lucas Erazo">
<meta name="author" content="Benjamín Ferrel">
<meta name="author" content="Ignacio Muñoz">
<meta name="author" content="Vicente Rojas">

<title>Trabajo final: Análisis correlacional de la confianza en la municipalidad</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="trabajo_final_conf_muni_files/libs/clipboard/clipboard.min.js"></script>
<script src="trabajo_final_conf_muni_files/libs/quarto-html/quarto.js"></script>
<script src="trabajo_final_conf_muni_files/libs/quarto-html/popper.min.js"></script>
<script src="trabajo_final_conf_muni_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="trabajo_final_conf_muni_files/libs/quarto-html/anchor.min.js"></script>
<link href="trabajo_final_conf_muni_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="trabajo_final_conf_muni_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="trabajo_final_conf_muni_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="trabajo_final_conf_muni_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="trabajo_final_conf_muni_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="trabajo_final_conf_muni_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="trabajo_final_conf_muni_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul class="collapse">
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">2</span> Metodología</a></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">3</span> Análisis</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">4</span> Conclusiones</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">5</span> Bibliografía</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo final: Análisis correlacional de la confianza en la municipalidad</h1>
<p class="subtitle lead">Universidad de Chile. Facultad de Ciencias Sociales. Carrera de Sociología. Curso: Estadística correlacional. Docente: Juan Carlos Castillo. Ayudante: Ismael Aguayo.</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Gaspar Duclos </p>
             <p>Lucas Erazo </p>
             <p>Benjamín Ferrel </p>
             <p>Ignacio Muñoz </p>
             <p>Vicente Rojas </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">29 de noviembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">1</span> Introducción</h2>
<p>Dentro de la presente investigación, se analiza el nivel de confianza en las municipalidades utilizando el Estudio Longitudinal Social de Chile (ELSOC) diseñada por investigadores pertenecientes al Centro de Estudios de Conflicto y Cohesión Social (COES); estudio que tiene como objetivo fundamental constituirse en un insumo empírico para la comprensión de las creencias, actitudes y percepciones de los chilenos hacia las distintas dimensiones de la convivencia y el conflicto, y cómo éstas cambian a lo largo del tiempo.</p>
<p>En primera instancia, es necesario entender que las instituciones públicas cumplen un rol fundamental en las sociedades para que éstas se mantengan operativas y funcionales. Según Putnam (1993), la confianza institucional es un factor clave para la sociedad y un requisito imprescindible para una buena gobernanza en dirección del desarrollo económico. A través de ellas, el Estado ejerce su soberanía sobre el territorio, como también en beneficio de la sociedad, brindando servicios, seguridad, etc. Sin embargo, a partir de las crecientes crisis de seguridad y de casos de corrupción política en Chile, las instituciones que representan al Estado han sufrido una baja en su legitimidad política. Por lo tanto, esto es importante evaluar para medir qué tanto se ha visto afectada la legitimidad institucional de los municipios. La relevancia del tema radica en que, tal como plantea Keefer y Scartascini (2022), se puede entender cómo de la confianza institucional se deriva en gran medida su capacidad de regular, ordenar y persuadir a los sujetos que están dentro de ellas</p>
<p>De esta manera, nuestro estudio se enfoca en la confianza en las instituciones públicas en Chile, específicamente las municipalidades, siendo estas una corporación autónoma de derecho público, con personalidad jurídica y patrimonio propio, a la cual le corresponde la administración de una comuna o agrupación de comunas (Artículo 118.º Constitución Política de Chile) y cuya finalidad es satisfacer las necesidades de la comunidad local y asegurar su participación en el progreso económico, social y cultural de la comuna o agrupación de comunas. Siendo la encargada de los servicios básicos de educación y salud de la comuna. Cabe señalar que en Chile no existen «gobiernos municipales», pues el gobierno interior del Estado se extiende sólo al nivel regional y provincial. Las municipalidades sólo administran a nivel comunal.</p>
<p>Ahora bien, para analizar la confianza en las municipalidades se usará como base tres variables: confianza institucional, género y su nivel educativo, respectivamente. El concepto de confianza en las instituciones públicas se explicaría por la capacidad por parte de las instituciones políticas para cumplir sus metas, hacia y en beneficio de los ciudadanos, como plantea Segovia (2008). Siendo entendida como la percepción ciudadana hacia la legitimidad y eficacia de las instituciones; género entendido como una categoría social que organiza las diferencias en las dimensiones cotidianas, y en último lugar, otro de los factores que se ven envuelto dentro de la confianza institucional es el nivel educativo, tal como dice Estella (2020) “la idea aquí es que las sociedades con más nivel educativo presentan índices de confianza más altos.” (pp.20). Siendo este mismo, un indicador de capital cultural que puede moldear las expectativas y actitudes hacia las instituciones.</p>
<p>Las varibles fueron seleccionadas en base a las siguientes <strong>tres hipótesis</strong>.</p>
<ul>
<li><p><strong>H1</strong>: Existe una relación positiva entre el nivel de confianza en la municipalidad y el nivel de confianza en el gobierno.</p></li>
<li><p><strong>H2</strong>: Existe una mayor confianza en la municipalidad en mujeres que en hombres.</p></li>
<li><p><strong>H3</strong>: Existe una relación entre el nivel de confianza en la municipalidad y el nivel educacional.</p></li>
</ul>
<p>A su vez, se desarrollan <strong>sus hipótesis nulas correspondientes</strong>:</p>
<ul>
<li><p><strong>H01</strong>: No existe una relación positiva entre el nivel de confianza en la municipalidad y el nivel de confianza en el gobierno.</p></li>
<li><p><strong>H02</strong>: No existe una mayor confianza en la municipalidad en mujeres que en hombres.</p></li>
<li><p><strong>H03</strong>: No existe una relación entre el nivel de confianza en la municipalidad y el nivel educacional.</p></li>
</ul>
<p>A continuación, se presenta detalladamente la metodología utilizada.</p>
</section>
<section id="metodología" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="metodología"><span class="header-section-number">2</span> Metodología</h2>
<p>En la sección metodológica, para analizar el nivel de confianza en las municipalidades se utilizará el cuestionario realizado por el Estudio Longitudinal Social de Chile (ELSOC). Según su ficha técnica, la población objetivo son hombres y mujeres de 18 a 75 años, residentes habituales de viviendas particulares en zonas urbanas de Chile. Para este estudio se utiliza solamente la ola 6 (año 2022) de ELSOC.</p>
<p>Dentro de este estudio, se utilizan dos variables del Módulo de Ciudadanía y Democracia (Módulo C) y dos del Módulo de Caracterización Sociodemográfica (Módulo M):</p>
<ul>
<li><p>Confianza en tu municipalidad y confianza en el Gobierno. (Módulo C)</p></li>
<li><p>Sexo y nivel educativo. (Módulo M)</p></li>
</ul>
<p>Descriptivamente, las variables son las siguientes:</p>
<ol type="1">
<li>A partir de la pregunta C05.”Utilizando una escala donde 1 representa “Nada” y 5“Mucho”, ¿podría decirme cuánto confía usted en cada una de las siguientes instituciones?“, la cual busca evaluar la confianza de instituciones públicas y privadas como Gobierno, Poder Judicial, Legislativo, Empresarios, entre otras. De allí, se desprende la principal variable C05_13, renombrada a “conf_municipalidad”. Esta variable es de carácter ordinal y pretende medir la confianza de las personas en su municipio, mediante una escala de Likert, con las siguientes alternativas: 1 (Nada), 2 (Poco), 3 (Algo), 4 (Bastante), 5 (Mucha), 6) No sabe, 7) No responde.</li>
</ol>
<!-- -->
<ol start="2" type="1">
<li>A partir del mismo enunciado, se utiliza la variable relacionada al Gobierno: C05_01 renombrada a “conf_gob”. Es de carácter ordinal y tiene por objetivo medir la confianza que tienen las personas sobre el gobierno, utilizando una escala de Likert donde las alternativas son: 1 (Nada), 2 (Poco), 3 (Algo), 4 (Bastante), 5 (Mucha), 6) No sabe, 7) No responde.</li>
</ol>
<!-- -->
<ol start="3" type="1">
<li>La tercera variable es Sexo: m0_sexo renombrada a “sexo”. Es de carácter nominal dicotómica y busca identificar el sexo de la persona encuestada como Hombre o Mujer. Estas fueron recodificadas en 0 (Hombre) y 1 (Mujer) para transformarlas de dicotómicas dummy.</li>
</ol>
<!-- -->
<ol start="4" type="1">
<li>La cuarta variable es Nivel educacional: m01 renombrada como “nivel_educ”, es de carácter intervalar y tiene por objetivo medir el nivel educativo del encuestado, mediante la siguiente pregunta “¿Cuál es su nivel educacional? Indique el tipo de estudio actual (si estudia actualmente) o el último tipo aprobado (si no estudia actualmente)”. Esta pregunta tiene 10 opciones de respuesta, las cuales son: 1) Sin estudios, 2) Educación básica o preparatoria incompleta, 3) Educación Básica o Preparatoria incompleta, 4) Educación Media o Humanidades incompleta, 5) Educación Media o Humanidades completa, 6) Técnico Superior incompleta, 7) Técnico Superior completa, 8) Universitaria incompleta, 9) Universitaria completa, 10) Estudios de posgrado (magister o doctorado), 11) No sabe, 12) No responde.</li>
</ol>
<p>Inicialmente, la base de datos constituida era de 2730 casos. Posteriormente, producto de una alta presencia de NA’s, especialmente en la variable confianza en la municipalidad (1243), y algunos valores -888 (No sabe) y -999 (No responde) presentes en las otras variables, se redujo a 1481 observaciones la muestra. El tratamiento de casos perdidos se hizo con Listwise, debido a que simplifica el análisis estadístico y no varían significativamente los resultados del análisis bivariado con Pairwise.</p>
<p>Ahora bien, para la primera hipótesis (H1) se ocuparan las variables “conf_gob” y “conf_municipalidad”, con el fin de saber si existe una relación positiva entre ambas. Para ello, se ocupará el estadístico de <strong>correlación de Spearman</strong>, debido a que las variables son ordinales. El tamaño de efecto se medirá según los criterios de Cohen, donde si la correlación es ≥0,1 el efecto es pequeño, si es ≥0,3 el efecto es mediano y si es ≤0,5 el efecto es grande.</p>
<p>En el caso de la segunda hipótesis (H2) se ocuparan las variables “conf_municipalidad” y “sexo”, el objetivo es evidenciar si existe una mayor confianza en la municipalidad en mujeres que en hombres. Para lo cual, se ocuparan los estadísticos <strong>coeficiente Biserial y Prueba de Chi-cuadrado</strong>, producto de la naturaleza de la hipótesis y variables. El tamaño de efecto se medirá con el coeficiente <strong>V de Cramer</strong>, el cual varía entre los parámetros 0 y 1, donde valores cercanos al 0 indican una asociación débil, y mientras más cercano al 1, una asociación más fuerte.</p>
<p>En la tercera hipótesis (H3) se ocupará las variables “nivel_educativo” y “conf_municipalidad”, para saber si existe una correlación entre el nivel educativo y un nivel de confianza en la municipalidad. Para ello, se recodifica la variable “conf_municipalidad”. Igualmente, se ocupará los estadísticos <strong>coeficiente de correlación de Pearson</strong> y <strong>Prueba de Chi-cuadrado</strong>, porque se utiliza una variable ordinal con una intervalar. El tamaño de efecto de la correlación, se medirá según los criterios de Cohen, ya explicado.</p>
<p>A continuación, se presentan tablas de las variables y sus posteriores análisis.</p>
<p><strong>Tabla 1 “Tabla Resumen de Variables”:</strong></p>
<div class="cell">
<div class="cell-output-display">
<div class="container st-container">
<h3 class="anchored">Data Frame Summary</h3>
<h4 class="anchored">summarytools::dfSummary</h4>
<strong>Dimensions</strong>: 1481 x 4
  <br><strong>Duplicates</strong>: 1179
<br>

<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>No</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Variable</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Label</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Stats / Values</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Freqs (% of Valid)</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Graph</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Valid</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Missing</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">conf_gob [haven_labelled, vctrs_vctr, double]</td>
<td style="text-align: left;">Grado de confianza: El Gobierno</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 2.1 (1.1)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 2 ≤ 5</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 2 (0.5)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">591</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">39.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">369</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">24.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">323</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">21.8%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">151</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">47</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">3.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAEgAAAB9BAMAAADzdDhqAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMDSkTADtAAAAcElEQVRYw+3TsQ0AIQwDQFbICDwbhP13+4YKeL8LkBLJrq+IJaeUmHlgBmodxIWEQiNq4wZzHG0OWdHazoWEsiBq4+deikLzQXWH5nZCQokQtXGDufZ3EI12LiSUEFEbN5gbf/eP2lcxIaH4iNp4tLzdQa4aQHpojgAAAABJRU5ErkJggg==" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1481 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">conf_municipalidad [haven_labelled, vctrs_vctr, double]</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 2.7 (1.1)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 3 ≤ 5</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 2 (0.4)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">272</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">18.4%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">327</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">22.1%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">502</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">33.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">299</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">20.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">81</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">5.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAD8AAAB9BAMAAADn4aaLAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMDSkTADtAAAAbUlEQVRYw+3TuxGAIBREUUqQDgQ60P57M/EDOPASFwzujU/Am1mc+0exyD8tJ0h71gYAyIG5Sd/qOxDrulfkhwAAGmBucsa/uFobV9wBABpgbnL8vwgvUF0BAKiBuclB/yL0QCqeDgDIgbnJ2R0czo6v8l1cDQAAAABJRU5ErkJggg==" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1481 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">sexo [numeric]</td>
<td style="text-align: left;"></td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Min : 0</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean : 0.7</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Max : 1</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">0</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">511</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">34.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">970</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">65.5%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAG8AAAA3BAMAAADwNgnJAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMDSkTADtAAAARUlEQVRIx2NgGBlACScQxA4EoBqVjXEAo1GNoxpHNY5qpL5GsgsrQVLBwGlUIhUoEApVXGBU46jGUY2jGinQSHZhNdwBABqDa+liTpf2AAAAAElFTkSuQmCC" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1481 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">nivel_educacional [haven_labelled, vctrs_vctr, double]</td>
<td style="text-align: left;">Nivel educacional</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 5.1 (2.2)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 5 ≤ 10</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 3 (0.4)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">13</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">0.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">190</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">12.8%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">161</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">189</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">12.8%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">472</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">31.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">6</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">38</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">2.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">7</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">178</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">12.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">8</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">51</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">3.4%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">9</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">162</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">10</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">27</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">1.8%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAADwAAADzBAMAAAAobGggAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAPUExURf////3+/aampvDw8P///7GHRIEAAAACdFJOUwAAdpPNOAAAAAFiS0dEAIgFHUgAAAAHdElNRQfoDAICMDXTSzB7AAAAoklEQVRYw+3YQQqEMAyFYa+QI7S9Qb3/3dzMFJTEp0zHIPxv+20MvITisuSmmh8Yns2WyHXE5bZ+0mFYsSiTBXmy58Xn72AwrFmUyYJwsOFXceY9r0GOX75Ph+HbLLr2556XM24rDE9i0TULMveeF5fHhsLwryy6ZkFm9fyM2/GpBcMhizJZkCfveYkGcxcUhh3O/KEiONjAMViH4assypSVDZ5NOCHv/l5cAAAAAElFTkSuQmCC" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1481 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
</tbody>
</table>

<p>Generated by <a href="https://github.com/dcomtois/summarytools">summarytools</a> 1.0.1 (<a href="https://www.r-project.org/">R</a> version 4.4.1)<br>2024-12-01</p>
</div>
</div>
</div>
</section>
<section id="análisis" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="análisis"><span class="header-section-number">3</span> Análisis</h2>
<section id="parte-1-análisis-descriptivos" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="parte-1-análisis-descriptivos"><span class="header-section-number">3.1</span> Parte 1: Análisis descriptivos</h3>
<p><strong>Tabla 2 “Tabla Resumen Descriptivo”:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">vars</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">trimmed</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mad</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">min</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">max</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">range</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">skew</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">kurtosis</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">conf_gob</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1481</td>
<td style="text-align: right;">2.1181634</td>
<td style="text-align: right;">1.139085</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1.9831224</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.6970763</td>
<td style="text-align: right;">-0.4914454</td>
<td style="text-align: right;">0.0295991</td>
</tr>
<tr class="even">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1481</td>
<td style="text-align: right;">2.7231600</td>
<td style="text-align: right;">1.140322</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2.7105485</td>
<td style="text-align: right;">1.4826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.0335854</td>
<td style="text-align: right;">-0.8188428</td>
<td style="text-align: right;">0.0296313</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexo</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1481</td>
<td style="text-align: right;">0.6549629</td>
<td style="text-align: right;">0.475541</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.6936709</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-0.6512929</td>
<td style="text-align: right;">-1.5768809</td>
<td style="text-align: right;">0.0123569</td>
</tr>
<tr class="even">
<td style="text-align: left;">nivel_educacional</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1481</td>
<td style="text-align: right;">5.1330182</td>
<td style="text-align: right;">2.205766</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5.0295359</td>
<td style="text-align: right;">2.9652</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.3942370</td>
<td style="text-align: right;">-0.6397093</td>
<td style="text-align: right;">0.0573168</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="a-hipótesis-1" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="a-hipótesis-1"><span class="header-section-number">3.2</span> <strong>a) HIPÓTESIS 1</strong></h3>
<p><strong>a.1) Análisis descriptivo</strong></p>
<p><strong>a.1.1) Tabla 3 “Tabla de frecuencias para Confianza en la municipalidad”</strong></p>
<p>En la Tabla 3, se puede observar que la moda se concentra en la opción 3 (Algo) con un 33,9% (502), seguida de “Poca” (22.08%) y “Bastante” (20.19%). También, hasta la opción 3 es donde un 74,34% de la frecuencia se acumula, mostrando una baja en las alternativas 4 (20,19%) y 5 (5,47%), con un total del 25,66%. De igual manera, en la Tabla 2, la media (2,73) y mediana (2), indican que el promedio se encuentra sobre el corte del 50% de los datos. Además, la desviación estándar (1,13) sugiere una dispersión moderada alrededor de la media y una distribución que es asimétrica positiva (skew: 0,03) y platicúrtica (kurtosis: -0,81), lo cual indica una baja concentración de los datos en el medio de los datos, con una leve tendencia hacia los valores más bajos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tabla de frecuencias para Confianza en la municipalidad:"</code></pre>
</div>
<div class="cell-output-display">
<table class="kable_wrapper">
<tbody>
<tr>
<td>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">val</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">frq</th>
<th style="text-align: right;">raw.prc</th>
<th style="text-align: right;">valid.prc</th>
<th style="text-align: right;">cum.prc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Nada</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">18.37</td>
<td style="text-align: right;">18.37</td>
<td style="text-align: right;">18.37</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Poca</td>
<td style="text-align: right;">327</td>
<td style="text-align: right;">22.08</td>
<td style="text-align: right;">22.08</td>
<td style="text-align: right;">40.45</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Algo</td>
<td style="text-align: right;">502</td>
<td style="text-align: right;">33.90</td>
<td style="text-align: right;">33.90</td>
<td style="text-align: right;">74.34</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Bastante</td>
<td style="text-align: right;">299</td>
<td style="text-align: right;">20.19</td>
<td style="text-align: right;">20.19</td>
<td style="text-align: right;">94.53</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Mucha</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">5.47</td>
<td style="text-align: right;">5.47</td>
<td style="text-align: right;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a.1.2) Tabla 4 “Tabla de frecuencias para Confianza en el Gobierno”</strong></p>
<p>En la Tabla 4, se puede observar que la alternativa con más respuestas se concentra en la opción 1 (Nada), con un 39,91% (591), seguida de “Poca” (24.92%) y “Algo” (21.81%). Además, hasta la opción 2 (Poco), la frecuencia se acumula un 64,82% y un 86,63% en la opción 3 (Algo), demostrando que más del 50% de las respuestas confían poco o nada en el gobierno. También, según la Tabla 2, la media (2,11) y mediana (2), muestran que el promedio de los datos se encuentran cercano al corte del 50%, influido por los valores más bajos. Este tiene una asimetría positiva (skew: 0,69) y moderada (&lt;0.5), indicando una fuerte tendencia hacia los valores más bajos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tabla de frecuencias para Confianza en el Gobierno:"</code></pre>
</div>
<div class="cell-output-display">
<table class="kable_wrapper">
<tbody>
<tr>
<td>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">val</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">frq</th>
<th style="text-align: right;">raw.prc</th>
<th style="text-align: right;">valid.prc</th>
<th style="text-align: right;">cum.prc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Nada</td>
<td style="text-align: right;">591</td>
<td style="text-align: right;">39.91</td>
<td style="text-align: right;">39.91</td>
<td style="text-align: right;">39.91</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Poca</td>
<td style="text-align: right;">369</td>
<td style="text-align: right;">24.92</td>
<td style="text-align: right;">24.92</td>
<td style="text-align: right;">64.82</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Algo</td>
<td style="text-align: right;">323</td>
<td style="text-align: right;">21.81</td>
<td style="text-align: right;">21.81</td>
<td style="text-align: right;">86.63</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Bastante</td>
<td style="text-align: right;">151</td>
<td style="text-align: right;">10.20</td>
<td style="text-align: right;">10.20</td>
<td style="text-align: right;">96.83</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Mucha</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: right;">100.00</td>
</tr>
<tr class="even">
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a.1.3) Gráfico 1 “Distribución de Niveles de Confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>a.1.4) Gráfico 2 “Distribución de Niveles de Confianza en el Gobierno”</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="b-hipótesis-2" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="b-hipótesis-2"><span class="header-section-number">3.3</span> <strong>b) HIPÓTESIS 2</strong></h3>
<p><strong>b.1) Análisis descriptivo</strong></p>
<p><strong>b.1.1) Tabla 5 “Tabla de frecuencias para Sexo”</strong></p>
<p>En la Tabla 5, se puede apreciar que el 34,5% de las personas encuestadas son Hombres y 65,5% son Mujeres, de un total de 1481 casos. De la misma manera, en la Tabla 2, en relación al skew (-0.65) se puede observar que hay una asimetría negativa inclinada en su mayoría hacia las mujeres. De forma simultánea, la media (0.65) se relaciona con el skew, ya que los valores del promedio determinan que hay mayor presencia femenina que masculina dentro de la encuesta. Además, la desviación estándar (0,47) muestra una moderada dispersión alrededor de la media.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tabla de frecuencias para Sexo:"</code></pre>
</div>
<div class="cell-output-display">
<table class="kable_wrapper">
<tbody>
<tr>
<td>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">val</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">frq</th>
<th style="text-align: right;">raw.prc</th>
<th style="text-align: right;">valid.prc</th>
<th style="text-align: right;">cum.prc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: left;">Hombre</td>
<td style="text-align: right;">511</td>
<td style="text-align: right;">34.5</td>
<td style="text-align: right;">34.5</td>
<td style="text-align: right;">34.5</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Mujer</td>
<td style="text-align: right;">970</td>
<td style="text-align: right;">65.5</td>
<td style="text-align: right;">65.5</td>
<td style="text-align: right;">100.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="c-hipótesis-3" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="c-hipótesis-3"><span class="header-section-number">3.4</span> <strong>c) HIPÓTESIS 3</strong></h3>
<p><strong>c.1) Análisis descriptivo</strong></p>
<p><strong>c.1.1) Tabla 6 “Tabla de frecuencias para Nivel educacional”</strong></p>
<p>En la Tabla 6, se puede observar que la alternativa más escogida se concentra en la opción 5 (Educación Media o Humanidades completa), con 472 respuestas (31,87%). Además, hasta esa opción, la frecuencia se acumula un 69,21%, demostrando que alrededor del 50% de las respuestas tienen Educación media completa o más. Esto se puede reafirmar, al observar la Tabla 2, con la mediana (5) y la media (5,13), las cuales sugieren que el promedio se encuentra cercano al corte del 50% de los datos. A su vez, con un rango (9) se explicaría la mayor desviación estándar (2.21) presente en la variable.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tabla de frecuencias para Nivel educativo:"</code></pre>
</div>
<div class="cell-output-display">
<table class="kable_wrapper">
<tbody>
<tr>
<td>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 5%">
<col style="width: 56%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">val</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">frq</th>
<th style="text-align: right;">raw.prc</th>
<th style="text-align: right;">valid.prc</th>
<th style="text-align: right;">cum.prc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Sin estudios</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.88</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Educacion Basica o Preparatoria incompleta</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">12.83</td>
<td style="text-align: right;">12.83</td>
<td style="text-align: right;">13.71</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Educacion Basica o Preparatoria completa</td>
<td style="text-align: right;">161</td>
<td style="text-align: right;">10.87</td>
<td style="text-align: right;">10.87</td>
<td style="text-align: right;">24.58</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Educacion Media o Humanidades incompleta</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">12.76</td>
<td style="text-align: right;">12.76</td>
<td style="text-align: right;">37.34</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Educacion Media o Humanidades completa</td>
<td style="text-align: right;">472</td>
<td style="text-align: right;">31.87</td>
<td style="text-align: right;">31.87</td>
<td style="text-align: right;">69.21</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Tecnico Superior incompleta</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">71.78</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Tecnico Superior completa</td>
<td style="text-align: right;">178</td>
<td style="text-align: right;">12.02</td>
<td style="text-align: right;">12.02</td>
<td style="text-align: right;">83.79</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Universitaria incompleta</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">3.44</td>
<td style="text-align: right;">3.44</td>
<td style="text-align: right;">87.24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Universitaria completa</td>
<td style="text-align: right;">162</td>
<td style="text-align: right;">10.94</td>
<td style="text-align: right;">10.94</td>
<td style="text-align: right;">98.18</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Estudios de posgrado (magister o doctorado)</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">1.82</td>
<td style="text-align: right;">100.00</td>
</tr>
<tr class="odd">
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>c.1.2) Gráfico 3 “Distribución de Niveles educacionales en la muestra”</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="parte-2-análisis-bivariados" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="parte-2-análisis-bivariados"><span class="header-section-number">3.5</span> Parte 2: Análisis bivariados</h3>
</section>
<section id="a-hipótesis-1-1" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="a-hipótesis-1-1"><span class="header-section-number">3.6</span> <strong>a) HIPÓTESIS 1</strong></h3>
<p><strong>a.2) Análisis bivariado</strong></p>
<p>Hipótesis alternativa y nula, respectivamente:</p>
<ul>
<li><strong>H1</strong>: Existe una relación positiva entre el nivel de confianza en la municipalidad y el nivel de confianza en el gobierno.</li>
</ul>
<!-- -->
<ul>
<li><strong>H01</strong>: No existe una relación positiva entre el nivel de confianza en la municipalidad y el nivel de confianza en el gobierno.</li>
</ul>
<p>Estadísticos de correlación:</p>
<p>Al someter a análisis las variables de confianza en el Gobierno y en la municipalidad, utilizando el coeficiente de Spearman para evaluar su correlación y significancia estadística. Se puede rechazar la hipótesis nula, ya que indica una correlación positiva moderada (p=0,000, p&lt;0.05). Además, señala que esta correlación sí es estadísticamente significativa con un 95% de confianza y positiva con un tamaño de efecto mediano (rho=0,304), según los criterios de Cohen. Así, a medida que aumenta la confianza en el gobierno, también tiende a aumentar la confianza en la municipalidad, y viceversa. Aunque esto sugiere que las percepciones de confianza estén relacionadas, puede que otros factores también influyen en cada una de ellas.</p>
<p>Por otra parte, al revisar la Tabla 8, igualmente se confirma la información mencionada, ya que el Chi-cuadrado observado supera el valor crítico establecido para los grados de libertad de la tabla de contingencia (Chi-cuadrado empírico: 244,2 &gt; Chi-cuadrado crítico: 26,3 , df = 16). De igual manera, en la tabla se puede apreciar que hay una mayor concentración de la frecuencia en las categorías más bajas, como Nada-Nada (70,6)%, Poca-Poca (39,4%) o Nada-Poca (37%). Aquello se puede evidenciar, igualmente, en la Tabla 9 donde el mapa de calor muestra una clara concentración de los porcentajes entre los valores 1-3 de confianza en la municipalidad y los valores 1-3 de confianza&nbsp;en&nbsp;el&nbsp;gobierno.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  data.elsoc$conf_municipalidad and data.elsoc$conf_gob
S = 377062333, p-value &lt; 0.00000000000000022
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.3035348 </code></pre>
</div>
</div>
<p><strong>a.2.1) Tabla 7 “Tabla de contingencia entre confianza en el Gobierno y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.id</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">label</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Grado de confianza: El Gobierno</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left;">pearson</td>
<td style="text-align: left;">0.3 95%CI [0.26;0.35]</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>a.2.2) Tabla 8 “Tabla de frecuencias entre confianza en el Gobierno y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Grado de confianza:<br>Su municipalidad</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="5">Grado de confianza:<br>El Gobierno</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Nada</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Poca</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Algo</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Bastante</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mucha</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">192</span><br><span style="color:#333399;">70.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">36</span><br><span style="color:#333399;">13.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">27</span><br><span style="color:#333399;">9.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span><br><span style="color:#333399;">5.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3</span><br><span style="color:#333399;">1.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">272</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poca</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">121</span><br><span style="color:#333399;">37&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">129</span><br><span style="color:#333399;">39.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">60</span><br><span style="color:#333399;">18.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">16</span><br><span style="color:#333399;">4.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#333399;">0.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">327</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">175</span><br><span style="color:#333399;">34.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">119</span><br><span style="color:#333399;">23.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">143</span><br><span style="color:#333399;">28.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">48</span><br><span style="color:#333399;">9.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">17</span><br><span style="color:#333399;">3.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">502</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">74</span><br><span style="color:#333399;">24.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">72</span><br><span style="color:#333399;">24.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">76</span><br><span style="color:#333399;">25.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">60</span><br><span style="color:#333399;">20.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">17</span><br><span style="color:#333399;">5.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">299</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Mucha</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">29</span><br><span style="color:#333399;">35.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">13</span><br><span style="color:#333399;">16&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">17</span><br><span style="color:#333399;">21&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">13</span><br><span style="color:#333399;">16&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">9</span><br><span style="color:#333399;">11.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">81</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">591</span><br><span style="color:#333399;">39.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">369</span><br><span style="color:#333399;">24.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">323</span><br><span style="color:#333399;">21.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">151</span><br><span style="color:#333399;">10.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">47</span><br><span style="color:#333399;">3.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1481</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="7">χ<sup>2</sup>=244.203 · df=16 · Cramer's V=0.203 · Fisher's p=0.000</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p><strong>a.2.3) Gráfico 4 “Asociación entre confianza en el Gobierno y en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>a.2.4) Tabla 9 “Heatmap (mapa de calor) entre confianza en el Gobierno y en la municipalidad</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="b-hipótesis-2-1" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="b-hipótesis-2-1"><span class="header-section-number">3.7</span> <strong>b) HIPÓTESIS 2</strong></h3>
<p><strong>b.2) Análisis bivariado</strong></p>
<p>Hipótesis alternativa y nula, respectivamente:</p>
<ul>
<li><p><strong>H2</strong>: Existe una mayor confianza en la municipalidad en mujeres que en hombres.</p></li>
<li><p><strong>H02</strong>: No existe una mayor confianza en la municipalidad en mujeres que en hombres.</p></li>
</ul>
<p>Estadísticos de correlación:</p>
<p>Para este analisis bivariado, se utilizaron los estadísticos coeficiente Biserial y Prueba de Chi-cuadrado entre las variables sexo y confianza en la municipalidad. El valor obtenido de la prueba Biserial (0.002) indica una correlación positiva muy pequeña que no es estadísticamente significativa (p&gt;0,05) entre estas dos variables. De igual forma, la prueba de Chi-cuadrado señala los siguientes valores: Chi-cuadrado = 1.2249, df = 4, p = 0.874. Por lo tanto, no se puede rechazar la hipótesis nula, debido a que el valor p&gt;0.05, y el valor empírico (Chi-cuadrado = 1.22) no supera el valor crítico establecido para los grados de libertad (Chi-cuadrado crítico: 9,49 , df = 4). Por lo cual, no hay evidencia suficiente para afirmar que existe una asociación significativa entre la confianza en la municipalidad y el sexo. Por último, se menciona que el tamaño de efecto, según la V de Carmer, indica que es muy pequeño (V=0.029).</p>
<p>Sin embargo, según la Tabla 11, se puede apreciar la mayor presencia femenina en la muestra, porque los porcentajes de incidencia entre la variable de confianza en la municipalidad con el sexo “Mujer” están sobre el 60% en todas las casillas respectivas. Por lo cual la hipótesis alternativa sobre una mayor presencia de mujeres en la confianza a la municipalidad si se puede afirmar, al contrastar con la frecuencia de presencia&nbsp;masculina.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "biserial(data.elsoc$conf_municipalidad,data.elsoc$sexo)"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            [,1]
[1,] 0.002466489</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  data.elsoc$conf_municipalidad and data.elsoc$sexo
X-squared = 1.2249, df = 4, p-value = 0.874</code></pre>
</div>
</div>
<p><strong>b.2.1) Tabla 10 “Tabla de contingencia entre sexo y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.id</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">label</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">0</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left;">Min / Max</td>
<td style="text-align: left;">1.0 / 5.0</td>
<td style="text-align: left;">1.0 / 5.0</td>
<td style="text-align: left;">1.0 / 5.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left;">Med [IQR]</td>
<td style="text-align: left;">3.0 [2.0;4.0]</td>
<td style="text-align: left;">3.0 [2.0;4.0]</td>
<td style="text-align: left;">3.0 [2.0;4.0]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left;">Mean (std)</td>
<td style="text-align: left;">2.7 (1.1)</td>
<td style="text-align: left;">2.7 (1.1)</td>
<td style="text-align: left;">2.7 (1.1)</td>
</tr>
<tr class="even">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left;">N (NA)</td>
<td style="text-align: left;">511 (0)</td>
<td style="text-align: left;">970 (0)</td>
<td style="text-align: left;">1481 (0)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>b.2.2) Tabla 11 “Tabla de frecuencias entre sexo y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Grado de confianza:<br>Su municipalidad</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="2">sexo</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Hombre</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Mujer</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">94</span><br><span style="color:#333399;">34.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">178</span><br><span style="color:#333399;">65.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">272</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poca</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">117</span><br><span style="color:#333399;">35.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">210</span><br><span style="color:#333399;">64.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">327</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">165</span><br><span style="color:#333399;">32.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">337</span><br><span style="color:#333399;">67.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">502</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">108</span><br><span style="color:#333399;">36.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">191</span><br><span style="color:#333399;">63.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">299</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Mucha</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">27</span><br><span style="color:#333399;">33.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">54</span><br><span style="color:#333399;">66.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">81</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">511</span><br><span style="color:#333399;">34.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">970</span><br><span style="color:#333399;">65.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1481</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="4">χ<sup>2</sup>=1.225 · df=4 · Cramer's V=0.029 · p=0.874</td> 
</tr>
 
</tbody></table>
</div>
</div>
</section>
<section id="c-hipótesis-3-1" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="c-hipótesis-3-1"><span class="header-section-number">3.8</span> <strong>c) HIPÓTESIS 3</strong></h3>
<p><strong>c.2) Análisis bivariado</strong></p>
<p>Hipótesis alternativa y nula, respectivamente:</p>
<ul>
<li><p><strong>H3</strong>: Existe una relación entre el nivel de confianza en la municipalidad y el nivel educacional.</p></li>
<li><p><strong>H03</strong>: No existe una relación entre el nivel de confianza en la municipalidad y el nivel educacional.</p></li>
</ul>
<p>Estadísticos de correlación:</p>
<p>En este último análisis bivariado, los estadísticos utilizados son el coeficiente de correlación de Pearson y Prueba de Chi-cuadrado entre el nivel educacional y confianza en la municipalidad. El valor del coeficiente de correlación (r) es de -0.026, lo que indica una correlación muy débil, según criterios de Cohen, y negativa entre variables. También, el el valor (p=0,324, p&lt;0.05) sugiere que no hay evidencia estadísticamente significativa para rechazar la hipótesis nula. Es decir, no se puede afirmar que exista una relación lineal entre estas dos variables. Además, el intervalo de confianza al 95% de [-0.0765, 0.0253] incluye el valor cero, lo que refuerza la falta de significancia de la correlación. Sin embargo, la Prueba de Chi-cuadrado señala un Chi-cuadrado = 51.292, df = 36, p = 0.047. Por lo tanto, con esta prueba sí se rechaza la hipótesis nula a un nivel de confianza del 95%. Lo cual indica que existe una asociación significativa. Sin embargo, dado el gran número de grados de libertad (df = 36), esta asociación puede ser débil o dependiente de otros factores que inciden.</p>
<p>Aunque ambas pruebas indican valores distintos, ello se debe a que cada prueba estadística se centra en aspectos distintos: Pearson evalúa la fuerza y dirección de una relación lineal, mientras que Chi-cuadrado identifica cualquier tipo de asociación categórica. Esto explica la discrepancia entre los valores P y su significancia estadística. La prueba de Chi-cuadrado puede ser influenciada por tamaños de muestra grandes y el número de categorías (grados de libertad), lo que aumenta la probabilidad de detectar asociaciones débiles que Pearson puede ignorar.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  data.elsoc$conf_municipalidad and data.elsoc$nivel_educacional
t = -0.98653, df = 1479, p-value = 0.324
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.07648118  0.02532635
sample estimates:
        cor 
-0.02564391 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  data.elsoc$conf_municipalidad and data.elsoc$nivel_educacional
X-squared = 51.292, df = 36, p-value = 0.04723</code></pre>
</div>
</div>
<p><strong>c.2.1) Tabla 12 “Tabla de contingencia entre Nivel educacional y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">.id</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">label</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Nivel educacional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">conf_municipalidad</td>
<td style="text-align: left;">Grado de confianza: Su municipalidad</td>
<td style="text-align: left;">pearson</td>
<td style="text-align: left;">-0.03 95%CI [-0.08;0.03]</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><strong>c.2.2) Tabla 13 “Tabla de frecuencias entre Nivel educacional y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Grado de confianza:<br>Su municipalidad</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="10">Nivel educacional</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Sin estudios</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educacion Basica o<br>Preparatoria<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educacion Basica o<br>Preparatoria<br>completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educacion Media o<br>Humanidades<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educacion Media o<br>Humanidades completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Tecnico Superior<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Tecnico Superior<br>completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Universitaria<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Universitaria<br>completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Estudios de posgrado<br>(magister o<br>doctorado)</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Nada</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#333399;">0.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">31</span><br><span style="color:#333399;">11.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">32</span><br><span style="color:#333399;">11.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">42</span><br><span style="color:#333399;">15.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">85</span><br><span style="color:#333399;">31.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">8</span><br><span style="color:#333399;">2.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">25</span><br><span style="color:#333399;">9.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">10</span><br><span style="color:#333399;">3.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">33</span><br><span style="color:#333399;">12.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">4</span><br><span style="color:#333399;">1.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">272</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Poca</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#333399;">0.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">39</span><br><span style="color:#333399;">11.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">26</span><br><span style="color:#333399;">8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">40</span><br><span style="color:#333399;">12.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">123</span><br><span style="color:#333399;">37.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#333399;">1.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">49</span><br><span style="color:#333399;">15&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">9</span><br><span style="color:#333399;">2.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">26</span><br><span style="color:#333399;">8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">2.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">327</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Algo</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">2</span><br><span style="color:#333399;">0.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">64</span><br><span style="color:#333399;">12.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">54</span><br><span style="color:#333399;">10.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">53</span><br><span style="color:#333399;">10.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">164</span><br><span style="color:#333399;">32.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">18</span><br><span style="color:#333399;">3.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">54</span><br><span style="color:#333399;">10.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">21</span><br><span style="color:#333399;">4.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">63</span><br><span style="color:#333399;">12.5&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">9</span><br><span style="color:#333399;">1.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">502</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Bastante</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">2.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">43</span><br><span style="color:#333399;">14.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">42</span><br><span style="color:#333399;">14&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">40</span><br><span style="color:#333399;">13.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">72</span><br><span style="color:#333399;">24.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">5</span><br><span style="color:#333399;">1.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">39</span><br><span style="color:#333399;">13&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">10</span><br><span style="color:#333399;">3.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">34</span><br><span style="color:#333399;">11.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">2.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">299</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Mucha</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">13</span><br><span style="color:#333399;">16&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">7</span><br><span style="color:#333399;">8.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">14</span><br><span style="color:#333399;">17.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">28</span><br><span style="color:#333399;">34.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#333399;">1.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">11</span><br><span style="color:#333399;">13.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1</span><br><span style="color:#333399;">1.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">6</span><br><span style="color:#333399;">7.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">0</span><br><span style="color:#333399;">0&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">81</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">13</span><br><span style="color:#333399;">0.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">190</span><br><span style="color:#333399;">12.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">161</span><br><span style="color:#333399;">10.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">189</span><br><span style="color:#333399;">12.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">472</span><br><span style="color:#333399;">31.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">38</span><br><span style="color:#333399;">2.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">178</span><br><span style="color:#333399;">12&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">51</span><br><span style="color:#333399;">3.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">162</span><br><span style="color:#333399;">10.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">27</span><br><span style="color:#333399;">1.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1481</span><br><span style="color:#333399;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="12">χ<sup>2</sup>=51.292 · df=36 · Cramer's V=0.093 · Fisher's p=0.075</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p><strong>c.2.3) Gráfico 4 “Asociación entre Nivel educacional y confianza en la municipalidad”</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>c.2.4) Tabla 14 “Heatmap (mapa de calor) entre Nivel educacional y confianza en la municipalidad</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="trabajo_final_conf_muni_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusiones" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">4</span> Conclusiones</h2>
<p>En conclusión, los resultados de los análisis bivariados permiten identificar patrones diferenciados en las variables asociadas al nivel de confianza en la municipalidad. La correlación de Spearman mostró una relación positiva moderada y estadísticamente significativa entre la confianza en el Gobierno y en la municipalidad, sugiriendo que las percepciones de confianza en estas instituciones están relacionadas. Por otro lado, tanto el coeficiente Biserial como la Prueba de Chi-cuadrado confirmaron que no existe una relación significativa entre el sexo y la confianza en la municipalidad, indicando independencia entre estas variables.</p>
<p>Respecto a la relación entre Nivel educacional y confianza en la municipalidad, los resultados fueron mixtos. La correlación de Pearson no encontró evidencia significativa de una relación lineal, mientras que la Prueba de Chi-cuadrado sí detectó una asociación significativa aunque posiblemente débil o no lineal, debido al gran número de grados de libertad. Esto sugiere que la relación entre estas variables podría depender de categorías específicas de nivel educacional, requiriendo análisis adicionales para esclarecer estos patrones.</p>
</section>
<section id="bibliografía" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">5</span> Bibliografía</h2>
<p>Centro de Estudios de Conflicto y Cohesión Social (2022). Estudio Longitudinal Social de Chile, Versión Panel Combinada (ELSOC_Long). [Archivo de datos]. Santiago, Chile: Centro de Estudios de Conflicto y Cohesión Social (COES). www.coes.cl</p>
<p>Centro de Estudios de Conflicto y Cohesión Social (2022). Manual de Usuario de Estudio Longitudinal Social de Chile. Santiago, Chile: Centro de Estudios de Conflicto y Cohesión Social (COES).</p>
<p>Chile. (1980). <em>Constitución Política de la República de Chile</em>. Artículo 118. Última reforma publicada en noviembre de 2024. Biblioteca del Congreso Nacional. Recuperado de [<a href="https://www.bcn.cl" class="uri">https://www.bcn.cl</a>].</p>
<p>Estella, A. (2020): “Confianza institucional en América Latina: un análisis comparado”, <em>Documentos de Trabajo nº 34</em> (2ª época), Madrid, Fundación Carolina.</p>
<p>Keefer, P. y Scartascini, C. 2022. <em>Confianza: La clave de la cohesión social y el crecimiento en América Latina y el Caribe</em>. Banco Interamericano de Desarrollo.</p>
<p>Segovia, C., Haye, A., González, R., Manzi, J. y Carvacho, H. (2008). Confianza en instituciones políticas en Chile: un modelo de los componentes centrales de juicios de confianza. <em>Revista de Ciencia Política</em>, 28(2), 39-60.</p>
<p>Putnam, R. D., Leonardi, R. y Nanetti, R. Y. (1993). <em>Making democracy work: Civic traditions in modern Italy</em>. Princeton, Estados Unidos: Princeton University Press.</p>
<p>Reproducible Research, Centre for Social Conflict and Cohesion Studies COES, 2024, “Estudio Longitudinal Social de Chile 2016-2023”, https://doi.org/10.7910/DVN/LD4BPH, Harvard Dataverse, V2, UNF:6:Il/1XZ8T4MaM8wOn8SvXrw== [fileUNF]</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>