<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Agustín Maldonado">
<meta name="author" content="Bastián González">
<meta name="author" content="Martín Mena">
<meta name="author" content="Vicente Olmos">
<meta name="author" content="Víctor Fuentes">
<meta name="description" content="Estadística Correlacional - Inferencia, asociación y reporte">

<title>Tendencias Políticas en Chile: Un Estudio de relación con Variables Socioeconómicas – Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../..//files/logo-correlacional-transp.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


<meta property="og:title" content="Tendencias Políticas en Chile: Un Estudio de relación con Variables Socioeconómicas – Estadística Correlacional">
<meta property="og:description" content="Este informe analiza la relación entre la tendencia política de los encuestados y variables socioeconómicas como ingreso, edad y nivel educacional en Chile. El problema central radica en comprender cómo estas variables influyen en las inclinaciones políticas de la población. Se plantearon tres hipótesis: (1) a mayores ingresos, las personas se inclinan hacia tendencias políticas de derecha; (2) existen diferencias significativas entre el nivel educacional y la tendencia política; y (3) existe una relación entre la edad y la tendencia política. Para este análisis, se utilizaron datos de la base de datos LAPOP 2023, que incluye información sobre 1,500 encuestados. Los principales resultados indican que no se encontró evidencia suficiente para respaldar ninguna de las hipótesis planteadas. La correlación entre ingresos y tendencia política resultó no significativa, al igual que la relación entre nivel educativo y tendencia política. Asimismo, no se observó una relación clara entre la edad y la inclinación política. Estos hallazgos sugieren que la orientación política puede estar influenciada por factores más complejos que no se abordaron en este estudio. Las limitaciones del análisis, como el tamaño de la muestra y la falta de variables adicionales, resaltan la necesidad de investigaciones futuras que consideren un enfoque más holístico y muestren la diversidad de factores que afectan la dinámica política en Chile.">
<meta property="og:image" content="https://correlacional.netlify.app/files/logo-correlacional.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
<meta property="og:image:height" content="533">
<meta property="og:image:width" content="466">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../assignment/index.html"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../trabajos.html"> 
<span class="menu-text">Trabajos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">2</span> Metodología</a>
  <ul class="collapse">
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos"><span class="header-section-number">2.1</span> Datos</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">2.2</span> Variables</a></li>
  <li><a href="#descriptivos-de-las-variables" id="toc-descriptivos-de-las-variables" class="nav-link" data-scroll-target="#descriptivos-de-las-variables"><span class="header-section-number">2.3</span> Descriptivos de las Variables</a></li>
  <li><a href="#métodos" id="toc-métodos" class="nav-link" data-scroll-target="#métodos"><span class="header-section-number">2.4</span> Métodos</a>
  <ul class="collapse">
  <li><a href="#descripción-de-hipótesis" id="toc-descripción-de-hipótesis" class="nav-link" data-scroll-target="#descripción-de-hipótesis"><span class="header-section-number">2.4.1</span> Descripción de hipótesis</a></li>
  <li><a href="#contraste-de-hipótesis" id="toc-contraste-de-hipótesis" class="nav-link" data-scroll-target="#contraste-de-hipótesis"><span class="header-section-number">2.4.2</span> Contraste de Hipótesis</a></li>
  <li><a href="#cálculo-del-tamaño-de-efecto" id="toc-cálculo-del-tamaño-de-efecto" class="nav-link" data-scroll-target="#cálculo-del-tamaño-de-efecto"><span class="header-section-number">2.4.3</span> Cálculo del Tamaño de Efecto</a></li>
  <li><a href="#tratamiento-casos-perdidos" id="toc-tratamiento-casos-perdidos" class="nav-link" data-scroll-target="#tratamiento-casos-perdidos"><span class="header-section-number">2.4.4</span> Tratamiento casos perdidos</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">3</span> Análisis</a>
  <ul class="collapse">
  <li><a href="#tendencia-política-e-ingresos" id="toc-tendencia-política-e-ingresos" class="nav-link" data-scroll-target="#tendencia-política-e-ingresos"><span class="header-section-number">3.1</span> Tendencia Política e Ingresos</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-dispersión" id="toc-gráfico-de-dispersión" class="nav-link" data-scroll-target="#gráfico-de-dispersión"><span class="header-section-number">3.1.1</span> Gráfico de Dispersión</a></li>
  </ul></li>
  <li><a href="#tendencia-política-y-nivel-educacional" id="toc-tendencia-política-y-nivel-educacional" class="nav-link" data-scroll-target="#tendencia-política-y-nivel-educacional"><span class="header-section-number">3.2</span> Tendencia política y Nivel educacional</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-boxplot" id="toc-gráfico-de-boxplot" class="nav-link" data-scroll-target="#gráfico-de-boxplot"><span class="header-section-number">3.2.1</span> Gráfico de Boxplot</a></li>
  </ul></li>
  <li><a href="#tendencia-política-y-edad" id="toc-tendencia-política-y-edad" class="nav-link" data-scroll-target="#tendencia-política-y-edad"><span class="header-section-number">3.3</span> Tendencia política y Edad</a>
  <ul class="collapse">
  <li><a href="#gráfico-de-dispersión-1" id="toc-gráfico-de-dispersión-1" class="nav-link" data-scroll-target="#gráfico-de-dispersión-1"><span class="header-section-number">3.3.1</span> Gráfico de Dispersión</a></li>
  </ul></li>
  <li><a href="#reflexiones" id="toc-reflexiones" class="nav-link" data-scroll-target="#reflexiones"><span class="header-section-number">3.4</span> Reflexiones</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">4</span> Conclusiones</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">5</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tendencias Políticas en Chile: Un Estudio de relación con Variables Socioeconómicas</h1>
<p class="subtitle lead">Estadística Correlacional 2024, Carrera de Sociología - Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Agustín Maldonado </p>
             <p>Bastián González </p>
             <p>Martín Mena </p>
             <p>Vicente Olmos </p>
             <p>Víctor Fuentes </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">1 de diciembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    Este informe analiza la relación entre la tendencia política de los encuestados y variables socioeconómicas como ingreso, edad y nivel educacional en Chile. El problema central radica en comprender cómo estas variables influyen en las inclinaciones políticas de la población. Se plantearon tres hipótesis: (1) a mayores ingresos, las personas se inclinan hacia tendencias políticas de derecha; (2) existen diferencias significativas entre el nivel educacional y la tendencia política; y (3) existe una relación entre la edad y la tendencia política. Para este análisis, se utilizaron datos de la base de datos LAPOP 2023, que incluye información sobre 1,500 encuestados. Los principales resultados indican que no se encontró evidencia suficiente para respaldar ninguna de las hipótesis planteadas. La correlación entre ingresos y tendencia política resultó no significativa, al igual que la relación entre nivel educativo y tendencia política. Asimismo, no se observó una relación clara entre la edad y la inclinación política. Estos hallazgos sugieren que la orientación política puede estar influenciada por factores más complejos que no se abordaron en este estudio. Las limitaciones del análisis, como el tamaño de la muestra y la falta de variables adicionales, resaltan la necesidad de investigaciones futuras que consideren un enfoque más holístico y muestren la diversidad de factores que afectan la dinámica política en Chile.
  </div>
</div>


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>La problemática que se abordará en este trabajo consiste en explorar la posible relación entre la tendencia política de los encuestados y variables como el ingreso, edad y nivel educativo. Para ello, se analizará el concepto de tendencia política, entendido como la posición política que adopta la población en el eje de izquierdas-derechas, tal como lo plantea Baño (1990). La relevancia de este trabajo radica en conocer si factores socioeconómicos y educativos influyen en la opinión y en la tendencia política de la población, ya que diversos estudios previos sugieren una relación directa entre estas variables. Un ejemplo de esto es la investigación de Altman (2004), que en uno de sus hallazgos señala que “cuanto menor es el nivel educativo y menor el ingreso, mayor es el voto a partidos de derecha” (Altman, 2004), estableciendo así una conexión entre ingresos, educación y orientación política. Otro estudio relevante para este trabajo es el de Haye et al.&nbsp;(2009), quienes analizan la relación entre las condiciones socioeconómicas y la orientación política, encontrando que el aumento de las tendencias hacia la derecha se produce a medida que se incrementa el nivel socioeconómico. Además, el Instituto Nacional de la Juventud (2009), a través de su encuesta, proporciona información crucial al evidenciar que tanto el nivel educativo como el nivel socioeconómico influyen en la participación política de la juventud chilena, observando, asimismo, que a mayor nivel socioeconómico, los jóvenes tienden a posicionarse más en el eje de derechas-izquierdas, mientras que un mayor nivel educativo incrementa el posicionamiento hacia la izquierda de este eje. Finalmente, la teoría del ciclo de vida de George Elder (1974) aporta una perspectiva importante al señalar que la edad y la madurez pueden influir en la orientación política, dado que los individuos atraviesan diversos contextos sociales y económicos a lo largo de su vida. Según Elder (1974), durante la juventud los individuos tienden a ser más liberales y progresistas debido a su cuestionamiento de las normas establecidas, mientras que en la vejez, con el paso del tiempo y la acumulación de experiencias, los individuos tienden a volverse más conservadores, priorizando la estabilidad económica y social.A partir de esta revisión bibliográfica, el objetivo principal de este estudio es determinar si existe una relación entre los ingresos, la educación y la edad respecto al concepto de tendencia política. Para alcanzar este objetivo, se han definido las siguientes hipótesis de investigación.</p>
<ul>
<li><p><strong>Hipótesis 1</strong>: Existe una relación entre los ingresos de una persona y su tendencia política.</p></li>
<li><p><strong>Hipótesis 2</strong>: A mayor nivel educacional alcanzado, se tenderá a una tendencia política de izquierda.</p></li>
<li><p><strong>Hipótesis 3</strong>: Existe una relación entre la edad y su tendencia política.</p></li>
</ul>
</section>
<section id="metodología" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metodología</h1>
<section id="datos" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="datos"><span class="header-section-number">2.1</span> Datos</h2>
<p>Para este informe se hizo uso de una encuesta realizada por el proyecto de investigación LAPOP (Proyecto de Opinión Pública de América Latina), el cual centra sus esfuerzos en la recopilación y análisis de datos sobre la opinión pública en América Latina y el Caribe. Fue fundado en 2004, desde entonces ha sido una fuente fundamental de información respecto a datos estadísticos de la región. Sus principales objetivos son: Medir la opinión pública, comparaciones transnacionales e informar en pro de las políticas. En específico para este informe se utilizaron los datos de la base de datos LAPOP 2023, Chile. La cual cuenta con 222 variables y 1653 observaciones.</p>
</section>
<section id="variables" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variables"><span class="header-section-number">2.2</span> Variables</h2>
<ol type="1">
<li>La variable L1N se emplea como una medida de la orientación política de un individuo, la cual se determina a partir de su ubicación dentro de un espectro ideológico. Este espectro se organiza de manera que el extremo izquierdo (valor 1) corresponde a una ideología política de izquierda, mientras que el extremo derecho (valor 10) se asocia con una ideología de derecha. En términos metodológicos, se trata de una variable intervalar, dado que sus valores se encuentran dispuestos en un orden jerárquico y las diferencias entre los puntos son significativas y consistentes. Aunque la tendencia política se mide en una escala de 1 a 10, se considera intervalar porque cada número representa una posición en un espectro político donde los incrementos reflejan cambios uniformes en la percepción política. Por ejemplo, la diferencia en inclinación política entre 3 y 4 es comparable a la diferencia entre 8 y 9. La operacionalización de esta variable se fundamenta en el auto-reporte de los participantes respecto a su propia orientación política. Al tratar la variable como intervalar, se reconoce que los valores reflejan tanto un orden como una magnitud constante entre ellos, lo que permite una interpretación más precisa para el análisis de correlaciones con otras variables, tales como las opiniones sobre temas políticos, los comportamientos electorales o las actitudes hacia partidos y políticas específicas.</li>
</ol>
<ul>
<li>Variable en el Cuestionario: Cambiando de tema, en esta tarjeta tenemos una escala del 1 a 10 que va de izquierda a derecha, en la que el 1 significa izquierda y el 10 significa derecha. Según el sentido que tengan para usted los términos “izquierda” y “derecha” cuando piensa sobre su punto de vista político, ¿dónde se encontraría usted en esta escala? Dígame el número.</li>
<li>Alternativas de respuesta: 1 (Izquierda), 2, 3, 4, 5, 6, 7, 8, 9, 10 (Derecha)</li>
</ul>
<ol start="2" type="1">
<li>La variable EDRE se utiliza para medir el nivel educativo alcanzado por los participantes, utilizando una serie de categorías predefinidas que reflejan diferentes niveles de educación. Esta variable es de gran relevancia en numerosos análisis correlacionales, dado que el nivel educativo puede estar vinculado a una variedad de otras variables, tales como los ingresos, las actitudes sociales o el comportamiento electoral, entre otras. Desde una perspectiva metodológica, se trata de una variable ordinal, ya que las categorías que la componen siguen un orden lógico, que va de menor a mayor en términos de nivel educativo. La operacionalización de esta variable se realiza mediante la asignación de categorías numéricas que representan distintos niveles educativos alcanzados por los individuos. A través de estas categorías, es posible realizar análisis comparativos y correlacionales para investigar la relación entre el nivel educativo y otras variables, como los ingresos, el empleo, o las actitudes políticas, entre otras.</li>
</ol>
<ul>
<li>Variable en el Cuestionario: ¿Cuál es el máximo nivel educativo que usted alcanzó?</li>
<li>Alternativas de respuesta: 0 (Ninguna), 1 (Primaria o educación básica incompleta), 2 (Primaria o educación básica completa), 3 (Secundaria o educación media científica-humanista o técnica incompleta), 4 (Secundaria o educación media científica-humanista o técnica completa), 5 (Terciaria, universitaria o técnico superior incompleta), 6 (Terciaria, universitaria o técnico superior completa)</li>
</ul>
<ol start="3" type="1">
<li>La variable Q10INC se refiere al rango de ingresos mensuales familiares de un hogar, y tiene como objetivo capturar el total de los ingresos que recibe una familia durante el mes, incluyendo pensiones, sueldos de todos los miembros adultos del hogar, entre otros conceptos. Esta variable es de gran relevancia en estudios correlacionales, ya que los ingresos familiares pueden estar estrechamente relacionados con una variedad de factores, como el nivel educativo, la satisfacción con la vida, la salud, el acceso a servicios, entre otros. La variable se considera categórica ordinal, dado que los rangos de ingresos siguen un orden lógico, de menor a mayor, en función de la cantidad de dinero percibidos, esto sumado a que los intervalos reflejan un orden,pero no tienen un valor numérico exacto para sus diferencias. La operacionalización de esta variable se realiza dividiendo los ingresos familiares mensuales en rangos predefinidos, lo que facilita el análisis de la distribución económica. Esta categorización resulta particularmente útil para mantener la confidencialidad de los participantes, ya que evita la solicitud de una cifra exacta, al mismo tiempo que permite clasificar a los hogares en diferentes niveles socioeconómicos según su capacidad económica. Para esta variable en específico fue necesario recodificar los valores, debido a que estos aparecían entre 1301 y 1315, por ello se le restó 1300 a todas las observaciones de esta con tal de que sea más fácil de interpretar y manipular.</li>
</ol>
<ul>
<li>Variable en el Cuestionario: ¿Y en cuál de los siguientes rangos se encuentran los ingresos familiares mensuales de su hogar, incluyendo las remesas del exterior, programas de ayuda en dinero del gobierno o municipio, pensiones o jubilaciones, rentas y el sueldo o ingreso de todos los adultos e hijos que viven en su hogar?</li>
<li>Alternativas de respuesta: 1 (Entre $0 y $100.000 pesos), 2 (Entre $100.001 y $200.000 pesos), 3 (Entre $200.001 y $350.000 pesos), 4 (Entre $350.001 y $475.000 pesos), 5 (Entre $475.001 y $600.000 pesos), 6 (Entre $600.001 y $700.000 pesos), 7 (Entre $700.001 y $815.000 pesos), 8 (Entre $815.001 y $975.000 pesos), 9 (Entre $975.001 y $1.200.000 pesos), 10 (Entre $1.200.001 y $1.450.000 pesos), 11 (Entre $1.450.001 y $1.600.000 pesos), 12 (Entre $1.600.001 y $1.800.000 pesos), 13 (Entre $1.800.001 y $2.000.000 pesos), 14 (Entre $2.000.001 y $2.400.000 pesos), 15 (Más de $2.400.000 pesos)</li>
</ul>
<ol start="4" type="1">
<li>La variable Q2 hace referencia a la edad de un participante, expresada en años cumplidos, y se considera una de las variables más comunes y fundamentales en la investigación, especialmente en el contexto de los análisis correlacionales. La edad se encuentra frecuentemente vinculada a una amplia variedad de factores, tales como actitudes, comportamientos, salud, nivel educativo, entre otros. Desde una perspectiva metodológica, esta variable se clasifica como continua. La operacionalización de la variable se lleva a cabo mediante la solicitud directa de los participantes para que reporten su edad exacta en años cumplidos. La edad constituye un dato demográfico básico que, además de ser utilizado para segmentar a los participantes en diferentes grupos etarios, resulta de gran utilidad en los análisis correlacionales, ya que permite estudiar cómo la edad influye en otras variables, tales como la orientación política, el nivel educativo, los ingresos o las actitudes hacia determinados temas.</li>
</ol>
<ul>
<li>Variable en el Cuestionario: ¿Cuál es su edad en años cumplidos? (Anotar la edad)</li>
</ul>
</section>
<section id="descriptivos-de-las-variables" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="descriptivos-de-las-variables"><span class="header-section-number">2.3</span> Descriptivos de las Variables</h2>
<p>A continuación, se presentan los descriptivos de las variables analizadas:</p>
<div class="cell">
<div class="cell-output-display">
<div class="container st-container">
<h3 class="anchored">Data Frame Summary</h3>
<h4 class="anchored">summarytools::dfSummary</h4>
<strong>Dimensions</strong>: 1653 x 4
  <br><strong>Duplicates</strong>: 211
<br>

<table class="table table-striped table-bordered st-table st-table-striped st-table-bordered st-multiline caption-top table-sm small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>No</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Variable</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Stats / Values</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Freqs (% of Valid)</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Graph</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Valid</strong></th>
<th class="st-protect-top-border" style="text-align: center;" data-quarto-table-cell-role="th"><strong>Missing</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">tendecia_politica [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 5.1 (2.4)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 5 ≤ 10</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 2 (0.5)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">98</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.7%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">24</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">2.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">83</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">9.1%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">97</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">340</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">37.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">6</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">73</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">8.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">7</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">64</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">7.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">8</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">39</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">4.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">9</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">20</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">2.2%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">10</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">76</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">8.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAEQAAADzCAQAAACV1Xj0AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAd0SU1FB+gMBRYxLCjDmu8AAAGFSURBVHja7dxBasMwEAXQccnpcoL2hO0Jer12UVpsp1ZssDRjeH8XQpKHRwZ9EmX6ihp5yQaAbOU2f/D+dMG8Tmd++PzNbsun7s0Xfna8ImVGAwICAgICAgKSndUOrecerJ1pvk0d3XHme9YyowFZZ7FYP/4Wybn95TDkt9dk3DtlRgMCAgICAgICkh29JkKvuQhko9c8pnfT2fl9Tf+7qcxoQEBAQEBAQECyo9dE6DXt7K4TP+lXKvz8CwQEBAQEBCQ7IGUhek2EXtPOwV5zbt5msznUa87N8sYoMxoQEBAQEBAQkOyUgeg1EXpNOzt7Tf9jLrt6zYglXGY0ICAgICAgICDZKQPRayL0mnZ29JoxR/ef9ppRy7fMaEBAQEBAQEBAslMGotdE6DXtNHrN2L8i2+w1o5dtmdGAgICAgICAgGRHnYhQJy4C+bfXjP9z5Ycrch96wqYByQsICAgICAgISHb0mgi95iIQ52vWKTMaEBAQEBAQEJDs1Ow1mSkzGpB1vgGYiTq8JtkLRgAAAABJRU5ErkJggg==" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">914 (55.3%)</td>
<td style="text-align: center;">739 (44.7%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">nivel_educativo [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 4.1 (1.5)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">0 ≤ 4 ≤ 6</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 2 (0.4)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; padding: 0; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">0</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">0.3%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">1</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">109</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">6.6%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">2</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">139</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">8.4%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">3</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">197</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">11.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">4</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">626</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">38.0%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">5</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">179</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">10.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: right; padding: 0 2px 0 7px; margin: 0; border: 0;">6</td>
<td style="text-align: left; padding: 0 2px; border: 0;">:</td>
<td style="text-align: right; padding: 0 4px 0 6px; margin: 0; border: 0;">394</td>
<td style="text-align: left; padding: 0; border: 0;">(</td>
<td style="text-align: right; padding: 0 2px; margin: 0; border: 0;">23.9%</td>
<td style="text-align: left; padding: 0 4px 0 0; border: 0;">)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAEYAAACsCAQAAABs+BLrAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAd0SU1FB+gMBRYxLCjDmu8AAAE4SURBVHja7dpBasMwEAXQcenpeoL2hO0Jej13O2piahtJHpf3s5EhhIdHAn+cZY06ebkaAHMY87muMftzjztzdWBgYGBgYGBgYP4rZsmPxFcUuiWtS92ZUpjXfPH1dE7vy76f6oyJeHv4wvcsSRQbEwwMDAwMDAwMTMf8euyc+ZD5GL1pK6UwO3pTxKzu9Gdvipi3rUuNCQYGBgYGBgbm7hhVpQGkdakxwWxlZ2/KGdehdvWmnJHnrdSYYGBgYGBgYGDujtGbGkBalxoTzFZO9Ka++Uib5nBv6pv29JYaEwwMDAwMDAzM3TF6UwNI61JjKoU5WFXG/kXuUFUZvb1LjQkGBgYGBgYGBqZj9KYGkNalxlQKM+QVz9l2NeAVz/lDUGpMMDAwMDAwMDAwHVO3N12dUmOC2coPNDtgHx95RFAAAAAASUVORK5CYII=" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1649 (99.8%)</td>
<td style="text-align: center;">4 (0.2%)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">ingresos_familiares [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 6 (3.1)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">1 ≤ 5 ≤ 15</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 4 (0.5)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle;">15 distinct values</td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAJgAAABuCAQAAABxABKuAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAd0SU1FB+gMBRYxLCjDmu8AAAGySURBVHja7dxdbsIwEABhgnI6TgAnLCfo9cqrgZXwuPnZDfO9tVKjZhS7iWM6/Z1EnPf+BaoxGGQwaG6/+M98dg9/+DrtfYJLaE9iHjlAHOfy9p3fvc90BUPBviVOxDkMMhhkMMhgkMEgg0EGgwwGGQwyGGQwyGCQwSCDQQaDDAYZDDIYZDDIYJDBIINBBoMMBhkMMhhkMOjj3oq7WxSfdGxG+d6NJxGHJGQwyGCQwSCDQQaDDAYZDDIYZDDIYNDgBxt6RY/utT9Os3Kw4z24OyQhg0EGgwwGGQxa+a9kpPatxlOwbV541L7VeLnCap/MFpzDoB3msB55/0dB0mB5JweHJGQwyGCQwSCDQQaDDAYZDDIYZDDIYJDBoCQP33X2aicJ9ro2kWNlIuKQhJJcYX0yvD4pFSzDoqJDEjIYZDDIYJDBIINBBoMMBhkMMhhkMMhgkMEgg0EGgwwGlVpAjCy7Chu/jLk1xysfbOlV2E/Hc0hC5a+wSN8wHXsXeshg0bCK8owM50MGiyw11zmHQQaDDAYZDDIYZDBoam9Pfspsa9tW+yw52YhxSEIGgwwGPQABXC7sMsWg9AAAAABJRU5ErkJggg==" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1406 (85.1%)</td>
<td style="text-align: center;">247 (14.9%)</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">edad [numeric]</td>
<td style="text-align: left; padding: 8; vertical-align: middle;"><table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">Mean (sd) : 42.5 (16.5)</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">min ≤ med ≤ max:</td>
</tr>
<tr class="odd" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">18 ≤ 40 ≤ 90</td>
</tr>
<tr class="even" style="background-color:transparent">
<td style="text-align: left; padding: 0; margin: 0; border: 0;">IQR (CV) : 23 (0.4)</td>
</tr>
</tbody>
</table></td>
<td style="text-align: left; vertical-align: middle;">72 distinct values</td>
<td style="text-align: left; vertical-align: middle; padding: 0; background-color: transparent;"><img src="data:image/png;base64,%20iVBORw0KGgoAAAANSUhEUgAAAJgAAABuCAQAAABxABKuAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAD/h4/MvwAAAAd0SU1FB+gMBRYxLCjDmu8AAAG2SURBVHja7dtbroIwAABRMa6OFegKdQVuT38rJcFpWvqa82dyNZeJfQCyfC4irrX/gd4YDDIYdAtfpM5nr5033pfah5ZPeCi35E/5sW5ev2sfYzEOSchgkMEgg0EGgwwGGQwyGGQwyGCQwSCDQQaDDAYZDDIYZDDIYFCmS9RperwXUDVYj/cCHJKQwSCDQQaDDAYZDDIYZDDIYJDBIINBBoMMBhkMMhiUcD3sNfWzEEkXEPu77JePQxIyGGQwyGDQaXeNRllbD4OlHmj8vjX6mx5X1z++YWmbiFG3Hs5hkMEgg0EGgwwGGQz62VaMsrksabMPG2NzWZJDEjIYZDDIYJDBIINBBoMMBlV+sOFYa0+LNB+stWu3HQSL1fzWdRms5hmvkz5kMMhgkMEgg0HNrZL5fppQZqPRXLDUbepZ21uHJGQwyGCQwSCDQQaDDAYZDDIY1NxOP58yJ0sDBytzsuSQhAwGGQwyGDTwpB/LsW5OFSzHuumQhAwGGQwyGDTVpB/j6+bkwfi66ZCEDAYZDJp8Dovt/bbjESwEBts4+jnoEgZ9+oDprvAbttiIcdKHDAYZDPoCjxQx9HbOqlgAAAAASUVORK5CYII=" class="img-fluid" style="border:none;background-color:transparent;padding:0;max-width:max-content;"></td>
<td style="text-align: center;">1653 (100.0%)</td>
<td style="text-align: center;">0 (0.0%)</td>
</tr>
</tbody>
</table>

<p>Generated by <a href="https://github.com/dcomtois/summarytools">summarytools</a> 1.0.1 (<a href="https://www.r-project.org/">R</a> version 4.3.3)<br>2024-12-05</p>
</div>
</div>
</div>
<p><strong>Interpretación de los Resultados:</strong></p>
<ul>
<li><p>Tendencia Política: La media en los valores de tendencia política, en una escala del 1 al 10 es de 5, representando el “centro” del espectro político. Esto sugiere que las observaciones están distribuidas de manera equilibrada, sin una inclinación marcada hacia las posiciones de izquierda y derecha, lo que indica una distribución relativamente proporcionada y natural entre las posturas ideológicas expresadas. El promedio de esta variable es de 5.1, lo que refuerza la idea de una distribución equitativa de una distribución equilibrada.</p></li>
<li><p>Nivel Educacional: Este varía entre 0 y 6, con una media de 4.196, lo que sugiere que la mayoría de los encuestados posee un nivel educativo que oscila entre secundaria y terciaria. La mediana es 4, lo que indica que al menos la mitad de los participantes tiene educación secundaria completa. El valor mínimo de 0 en la escala implica la presencia de respuestas que reflejan una ausencia total de educación formal.</p></li>
<li><p>Ingresos Familiares: Esta variable tiene un rango de 1 a 15, con un promedio de 6.192. Esto sugiere que los ingresos familiares tienden a ser relativamente altos en comparación con la escala utilizada. La mediana de 5 indica que la mitad de los encuestados reporta ingresos familiares por encima de este nivel, lo que sugiere una distribución algo sesgada hacia los ingresos más altos. Sin embargo, el rango amplio entre 1 y 15 también sugiere que hay una diversidad significativa en los ingresos</p></li>
<li><p>Edad: Con un rango de 18 a 89 años y una media de 42.47, la muestra incluye una variedad de edades. La mediana de 40 años sugiere que la mayoría de los encuestados son adultos jóvenes a adultos de mediana edad, lo que puede ser importante para comprender las tendencias o comportamientos de este grupo etario.</p></li>
</ul>
</section>
<section id="métodos" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="métodos"><span class="header-section-number">2.4</span> Métodos</h2>
<section id="descripción-de-hipótesis" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="descripción-de-hipótesis"><span class="header-section-number">2.4.1</span> Descripción de hipótesis</h3>
<p>Para guiar la investigación se basará en las siguientes hipótesis:</p>
<ul>
<li><p><strong>Hipótesis 1</strong>: Existe una relación entre los ingresos de una persona y su tendencia política. En este caso se aplicará un análisis correlacional para verificar si hay relación directa entre la cantidad de ingresos de una persona y su tendencia a nivel político. Por medio de la correlación de Spearman para determinar la fuerza y dirección de una posible relación lineal entre las variables “ingresos” y “tendencia política.”</p></li>
<li><p><strong>Hipótesis 2</strong>: A mayor nivel educacional alcanzado, se tenderá a una tendencia política de izquierda. Se hará una correlación de Spearman entre las variables orientación política de personas con diferentes niveles educacionales que luego se usará para estimar si existe evidencia estadística donde se pueda verificar o desestimar que hay diferencias significativas entre ambas. Para finalmente evaluar la fuerza de asociación entre las variables.</p></li>
<li><p><strong>Hipótesis 3</strong>: Existe una relación entre la edad y su orientación política. Mediante una correlación de Pearson se determinará si existen o no diferencias estadísticamente significativas entre diferentes edades relacionados con su tendencia política.</p></li>
</ul>
</section>
<section id="contraste-de-hipótesis" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="contraste-de-hipótesis"><span class="header-section-number">2.4.2</span> Contraste de Hipótesis</h3>
<p>Para evaluar las hipótesis planteadas en el estudio, se utilizarán los siguientes métodos estadísticos:</p>
<ul>
<li><p><strong>Correlación de Spearman</strong>: Este método se usará para analizar la relación entre las variables ordinales (tendencia política, ingresos familiares y edad). Es adecuado dado que no se asume normalidad en los datos y permite identificar relaciones monotónicas.</p></li>
<li><p><strong>Correlación de Pearson</strong>: Se aplicará para evaluar la relación entre variables continuas (edad y tendencia política) cuando se cumplan los supuestos de normalidad. Este método proporcionará una medida de la fuerza y dirección de la relación lineal entre las variables.</p></li>
</ul>
</section>
<section id="cálculo-del-tamaño-de-efecto" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="cálculo-del-tamaño-de-efecto"><span class="header-section-number">2.4.3</span> Cálculo del Tamaño de Efecto</h3>
<p>Para complementar los resultados de las pruebas de hipótesis, se calculará el tamaño de efecto utilizando los siguientes índices:</p>
<ul>
<li><p><strong>Coeficiente de Correlación de Spearman (ρ)</strong>: Este coeficiente no solo indica la dirección y la fuerza de la relación entre dos variables ordinales, sino que también sirve como medida del tamaño del efecto.</p></li>
<li><p><strong>Coeficiente de Correlación de Pearson (r)</strong>: Este coeficiente se usará para medir la fuerza y dirección de la relación lineal entre las variables continuas.</p></li>
</ul>
<p>Los resultados de estas pruebas se interpretarán en función de los valores p obtenidos (con un nivel de significancia de α = 0.05) y los tamaños de efecto calculados, lo que permitirá una comprensión más profunda de las relaciones entre las variables estudiadas.</p>
</section>
<section id="tratamiento-casos-perdidos" class="level3" data-number="2.4.4">
<h3 data-number="2.4.4" class="anchored" data-anchor-id="tratamiento-casos-perdidos"><span class="header-section-number">2.4.4</span> Tratamiento casos perdidos</h3>
<p>En cuanto al manejo de los datos faltantes (NA), se eligió el método de eliminación por pares (pairwise deletion). Algunas de las variables seleccionadas presentaban una considerable cantidad de valores faltantes, siendo tendencia política la variable con mayor número de casos perdidos, además de ser la variable dependiente que se deseaba analizar en relación con las demás. La aplicación de este método permitió conservar la mayor cantidad posible de casos en el análisis, evitando la pérdida de información relevante de otras variables.</p>
</section>
</section>
</section>
<section id="análisis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análisis</h1>
<section id="tendencia-política-e-ingresos" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="tendencia-política-e-ingresos"><span class="header-section-number">3.1</span> Tendencia Política e Ingresos</h2>
<p>Para la primera hipótesis se realizó una prueba de correlación de Spearman entre las variables ingresos y tendencia política.</p>
<p>Recordando y definiendo las hipótesis como:</p>
<p><strong>Hipótesis nula</strong>: No existe relación entre los ingresos de una persona y su tendencia política. (ρ=0, donde ρes el coeficiente de correlación de Spearman).</p>
<p><strong>Hipótesis alternativa</strong>: Existe una relación significativa entre los ingresos de una persona y su tendencia política. (ρ≠0≠0).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlación de Spearman entre Ingresos Familiares y Tendencia Política</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Estadístico</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">83394416.5880177</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-value</td>
<td style="text-align: right;">0.5210673</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Rho</td>
<td style="text-align: right;">0.0227202</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Se puede apreciar de este test que el valor (rho = 0.0227) indica una relación directa muy débil según criterio de Cohen entre las variables ingreso y tendencia política, mientras que el p-valor (0.5211 &gt; 0.05) implica que no hay suficiente evidencia estadística que permita rechazar la hipótesis nula de no-relación entre las variables seleccionadas. En otras palabras, los resultados no apoyan la hipótesis de que, a medida que aumentan los ingresos, las personas tienden a tener inclinaciones políticas más hacia la derecha.</p>
<section id="gráfico-de-dispersión" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="gráfico-de-dispersión"><span class="header-section-number">3.1.1</span> Gráfico de Dispersión</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reporte_files/figure-html/Dispersion_Hipotesis1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Al analizar el diagrama de dispersión que relaciona ingresos y tendencia política, se observa una dispersión de los puntos carente de patrones definidos. Esto sugiere la ausencia de una relación lineal directa entre ambas variables. Los resultados obtenidos no respaldan la hipótesis de que un mayor nivel de ingresos esté asociado con una mayor inclinación hacia ideologías de derecha.</p>
</section>
</section>
<section id="tendencia-política-y-nivel-educacional" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="tendencia-política-y-nivel-educacional"><span class="header-section-number">3.2</span> Tendencia política y Nivel educacional</h2>
<p>Definiendo las hipótesis como:</p>
<p><strong>Hipótesis nula</strong>: No existe una relación significativa entre el nivel educacional alcanzado y la tendencia política hacia la izquierda.(ρ=0, donde ρρ es el coeficiente de correlación de Spearman).</p>
<p><strong>Hipótesis alternativa</strong>: A mayor nivel educacional alcanzado, las personas tienden a una tendencia política hacia la izquierda. (ρ≠0≠0)</p>
<p>Para abordar la segunda hipótesis se realizó una prueba de correlación de Spearman entre las variables nivel educacional y tendencia política.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlación de Spearman entre Nivel Educativo y Tendencia Política</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Estadístico</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">128038025.4150725</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-value</td>
<td style="text-align: right;">0.8532787</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Rho</td>
<td style="text-align: right;">-0.0061255</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A partir del test de Correlación de Spearman, es posible apreciar que el valor (rho = -0.0061255 ) que indica una correlación inversa y extremadamente débil entre las variables según criterio de Cohen. Por otro lado, el p-valor (0.8532787 &gt; 0.05) implica que no hay suficiente evidencia estadística para rechazar la hipótesis nula que establece que no existe correlación entre las variables. En otras palabras, la prueba de Spearman sugiere que no existe una relación significativa para afirmar que, a mayor nivel educativo alcanzado, las personas tiendan hacia una inclinación política hacia la izquierda.</p>
<section id="gráfico-de-boxplot" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="gráfico-de-boxplot"><span class="header-section-number">3.2.1</span> Gráfico de Boxplot</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reporte_files/figure-html/Boxplot_Hipótesis2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El boxplot muestra que las medianas de la tendencia política son similares en todos los niveles educativos, lo que sugiere que no existen diferencias significativas en las orientaciones políticas promedio según el nivel educativo. Además, la dispersión de los datos es similar en cada grupo, indicando que las opiniones políticas son diversas y no están fuertemente influenciadas por la educación. Los valores atípicos representan a individuos con opiniones políticas muy diferentes al resto de su grupo, lo que resalta la presencia de opiniones extremas. En general, no se observa una relación clara entre el nivel educativo y la tendencia política, lo que sugiere un equilibrio ideológico y una gran diversidad de opiniones dentro de cada nivel educativo.</p>
</section>
</section>
<section id="tendencia-política-y-edad" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="tendencia-política-y-edad"><span class="header-section-number">3.3</span> Tendencia política y Edad</h2>
<p>Definiendo las hipótesis como:</p>
<p><strong>Hipótesis nula</strong>: No existe relación entre la edad de una persona y su tendencia política. (ρ=0, donde ρes el coeficiente de correlación de Spearman).</p>
<p><strong>Hipótesis alternativa</strong>: Existe una relación significativa entre la edad de una persona y su tendencia política. (ρ≠0≠0).</p>
<p>Para la tercera hipótesis se realizó un cálculo de correlación de Pearson entre las variables edad y tendencia política.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Correlación de Pearson entre Edad y Tendencia Política</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Estadístico</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cor</td>
<td style="text-align: left;">r</td>
<td style="text-align: right;">-0.0231675</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-value</td>
<td style="text-align: right;">0.4842109</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En base a los resultados obtenidos en el test de correlación de Pearson, el valor de (r= -0.0231675) indica una discrepancia entre las frecuencias observadas y las esperadas, además de ser extremadamente débil, según criterios de Cohen, como para sugerir una relación significativa entre las variables edad y tendencia política. Por otro lado, con un p-valor (0.4842109 &gt; 0.05), no existe suficiente evidencia para rechazar la hipótesis nula de no-correlación entre las variables escogidas. Lo que indica una relación débil entre las variables, que también sugieren la ausencia de una asociación significativa o fuerte entre ellas. En otras palabras, no hay evidencia estadística suficiente para afirmar que, a una cierta edad, las personas tiendan hacia una inclinación política.</p>
<section id="gráfico-de-dispersión-1" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="gráfico-de-dispersión-1"><span class="header-section-number">3.3.1</span> Gráfico de Dispersión</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="reporte_files/figure-html/Dispersión_Hipótesis3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico de dispersión entre las variables edad y tendencia política no revela, a simple vista, una correlación evidente entre ambas. Los puntos se distribuyen de manera bastante aleatoria, lo que sugiere que no existe una relación directa entre edad y tendencia política, y que los datos presentan una notable variabilidad. Este gráfico respalda la idea de que no existe una relación significativa entre las variables seleccionadas.</p>
</section>
</section>
<section id="reflexiones" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="reflexiones"><span class="header-section-number">3.4</span> Reflexiones</h2>
<p>De acuerdo a los resultados del informe se pueden destacar como principales reflexiones los siguientes puntos: Primeramente destacar que se esperaban resultados totalmente contrarios a los obtenidos, en base a la revisión bibliográfica investigaciones realizada en la introducción, investigaciones como la de Altman (2004),que planteaba que a menor ingresos y menor nivel educativo más se votaba por partidos de derecha, o la investigación de Haye et al.(2009), que plantea que a un nivel socioeconómico más alto es más probable una tendencia hacia el derecha, por lo que basado a los enunciados e investigaciones anteriores,y sumado también a la creencia o prejuicio propio de que existía una relación, se esperaba que la evidencia en la investigación sería favorable a nuestras hipótesis, mostrando una relación significativa entre la edad, el nivel educativo alcanzado y los ingresos familiares con la tendencia política, al ocurrir todo lo contrario, donde según nuestros resultados se ve que no hay suficiente significancia estadística para relacionar las variables, nos quedan variadas conclusiones, como principal fundamento la complejidad de las relaciones sociales, donde cada persona o grupos de persona generará una tendencia política por múltiples factores y contextos además de los descritos como variables, igualmente creemos que aunque nuestras hipótesis no se hayan cumplido no necesariamente habla de que las relaciones no existan, simplemente pueden ser indicativos de relaciones más sutiles o que no se logran captar en los datos conseguidos, pudiendo ser factores más allá de los datos estadísticos. También nos queda como opción a mejorar, los límites de los estadísticos usados, donde las relaciones que buscábamos las cerramos a estos estadísticos lineales y a las variables y datos que se nos daban. Dejando de lado a lo mejor algún otro factor no considera que si muestre relación con tendencias políticas. En resumen con los resultados se nos invita a replantear nuestras hipótesis y premisas, analizando si hubieron supuestos sólidos y si se usaron correlaciones correctas para este estudio, lo que nos ayudará en un futuro a mejorar nuestro enfoque y viéndolo finalmente como una oportunidad para aprender y mejorar interpretandolo no como un resultado negativo sino como un rango de mejora ante futuros trabajos.</p>
</section>
</section>
<section id="conclusiones" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusiones</h1>
<p>El presente informe ha analizado la relación entre la tendencia política de los encuestados y variables socioeconómicas como ingreso, edad y nivel educacional. A través de un enfoque estadístico, se plantearon y evaluaron tres hipótesis. Los resultados obtenidos no encontraron evidencia suficiente para respaldar ninguna de las hipótesis, sugiriendo que las relaciones entre estas variables pueden ser más complejas de lo inicialmente considerado. Los análisis realizados, incluyendo la correlación de Spearman y la correlación de Pearson, indicaron que no existe una relación significativa entre los ingresos familiares, el nivel educativo y la edad con la tendencia política en la muestra analizada. Estos hallazgos resaltan la importancia de considerar factores adicionales que puedan influir en la orientación política de la población chilena, más allá de las variables estudiadas. Entre las limitaciones del estudio, se destaca el tamaño de la muestra, que podría no ser representativo de la población general. Además, la naturaleza transversal de los datos limita la capacidad de establecer relaciones causales. Variables adicionales, como la cultura política, la historia personal de los encuestados y el contexto socioeconómico más amplio, no fueron incluidas en el análisis, lo que podría haber influido en los resultados. Estas limitaciones sugieren que se requiere un enfoque más holístico para comprender las dinámicas políticas en el país. Para futuras investigaciones, se sugiere utilizar muestras más representativas que reflejen la diversidad socioeconómica y demográfica de la población chilena. También sería beneficioso incluir variables adicionales que puedan influir en la tendencia política, como la participación en redes sociales,el nivel de información política y la confianza en las instituciones. Adoptar enfoques longitudinales permitiría observar cambios en la tendencia política a lo largo del tiempo, ofreciendo una perspectiva más dinámica sobre cómo y por qué cambian las inclinaciones políticas. En conclusión, aunque este estudio no encontró evidencia significativa que respalde las hipótesis planteadas, abre la puerta a nuevas líneas de investigación que podrían proporcionar una comprensión más profunda de los factores que influyen en la orientación política en Chile, complementando así el análisis inicial y sugiriendo que la orientación política puede estar influenciada por factores más complejos que no se abordaron en este estudio.</p>
</section>
<section id="bibliografía" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bibliografía</h1>
<ul>
<li><p>Altman, David. (2004). Redibujando el mapa electoral chileno: incidencia de factores socioeconómicos y género en las urnas. Revista de ciencia política (Santiago), 24(2), 49-66. https://dx.doi.org/10.4067/S0718-090X2004000200003</p></li>
<li><p>Baño, R. (1990). Chile. Tendencias políticas y resultados electorales después de veinte años. Revista Mexicana de Sociología, 52(4), 69–82. https://doi.org/10.2307/3540601</p></li>
<li><p>Andrés Haye, Héctor Carvacho, Roberto González, Jorge Manzi y Carolina Segovia, «Relación entre orientación política y condición socioeconómica en la cultura política chilena», Polis [En línea], 23 | 2009, Publicado el 19 julio 2011, consultado el 28 noviembre 2024. URL: http://journals.openedition.org/polis/1789</p></li>
<li><p>Instituto Nacional de la Juventud (INJUV). (2009). 6ta Encuesta Nacional de Juventud 2009 (pp.&nbsp;154-166). Instituto Nacional de la Juventud. https://www.injuv.gob.cl/libro-6ta-enj-2009</p></li>
<li><p>Elder, G. H. (1974). Children of the Great Depression: Social change in life experience. University of Chicago Press.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/correlacional\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>