<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Javiera Morales">
<meta name="author" content="Catalina Silva">
<meta name="author" content="Catalina Santos">
<meta name="author" content="Micaela Peña">
<meta name="author" content="Martina Villatoro">
<meta name="description" content="Estadística Correlacional - Inferencia, asociación y reporte">

<title>Estatus Social Subjetivo, Nivel Educacional y su Impacto en la Identificación Partidaria en Chile – Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../..//files/logo-correlacional-transp.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


<meta property="og:title" content="Estatus Social Subjetivo, Nivel Educacional y su Impacto en la Identificación Partidaria en Chile – Estadística Correlacional">
<meta property="og:description" content="Para la sociología la identificación partidaria es importante de estudiar para comprender las dinámicas sociales, ya que es necesario comprender cómo se lleva respecto a la estratificación y percepción de estatus, la forma en que incide en la participación en la política a través de partidos. Pero, ¿Cuáles son las variables que influyen en la decisión de los sujetos para llegar a identificarse en partidos políticos? El estudio busca conocer la relación entre la variable de “Estatus Social Subjetivo” y “Nivel Educacional” con los partidos políticos. En base a la bibliografía, se evidencia que ambas variables son fundamentales como base para la identificación partidaria, ya que ambas son espacios sociales donde se reproducen orientaciones políticas.Teniendo como la hipótesis 1 propone que el nivel educativo tiene una relación positiva con la identificación partidaria, donde las personas con mayor educación están más inclinadas a identificarse con un partido político. Por otro lado, la hipótesis 2 propone que quienes se identifican partidariamente tienen más estatus social subjetivo que quienes no se identifican partidariamente. Para la investigación se realizó un estudio cuantitativo de la base de datos ELSOC, encuesta aleatoria diseñada por investigadores del Centro de Estudios de Conflicto y Cohesión Social (COES) en este caso se utilizó la ola 2022, donde se recolectó información de 18.035 personas. Para llegar a los resultados se realizaron dos análisis bivariados y uno descriptivo, donde se utilizaron distintas estrategias estadísticas para encontrar correlaciones entre las variables escogidas. Si bien las variables “Identificación política” y “Estatus Social Subjetivo” juegan un rol importante en la identificación partidaria, las correlaciones son débiles. Se rechaza la hipótesis nula pero sería necesario que a futuros estudios se agregue una mayor cantidad de variables que demuestren la identificación partidaria. Finalmente en los resultados se encontró que la mayoría de los sujetos (70.4%) no se identifican con ningún partido político.">
<meta property="og:image" content="https://correlacional.netlify.app/files/logo-correlacional.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
<meta property="og:image:height" content="533">
<meta property="og:image:width" content="466">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../assignment/index.html"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../trabajos.html"> 
<span class="menu-text">Trabajos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#introducción." id="toc-introducción." class="nav-link active" data-scroll-target="#introducción."><span class="header-section-number">1</span> Introducción.</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">2</span> Metodología</a></li>
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos"><span class="header-section-number">3</span> Datos</a>
  <ul class="collapse">
  <li><a href="#identificación-partidaria" id="toc-identificación-partidaria" class="nav-link" data-scroll-target="#identificación-partidaria"><span class="header-section-number">3.1</span> Identificación partidaria</a></li>
  <li><a href="#nivel-educacional" id="toc-nivel-educacional" class="nav-link" data-scroll-target="#nivel-educacional"><span class="header-section-number">3.2</span> Nivel educacional</a></li>
  <li><a href="#estatus-social" id="toc-estatus-social" class="nav-link" data-scroll-target="#estatus-social"><span class="header-section-number">3.3</span> Estatus social</a></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">4</span> Análisis</a>
  <ul class="collapse">
  <li><a href="#identificación-partidaria-y-nivel-educativo" id="toc-identificación-partidaria-y-nivel-educativo" class="nav-link" data-scroll-target="#identificación-partidaria-y-nivel-educativo"><span class="header-section-number">4.1</span> Identificación partidaria y nivel educativo</a></li>
  <li><a href="#estatus-social-e-identificacion-partidaria" id="toc-estatus-social-e-identificacion-partidaria" class="nav-link" data-scroll-target="#estatus-social-e-identificacion-partidaria"><span class="header-section-number">4.2</span> Estatus social e Identificacion Partidaria</a></li>
  <li><a href="#punto-biserial" id="toc-punto-biserial" class="nav-link" data-scroll-target="#punto-biserial"><span class="header-section-number">4.3</span> Punto biserial</a></li>
  <li><a href="#prueba-t" id="toc-prueba-t" class="nav-link" data-scroll-target="#prueba-t"><span class="header-section-number">4.4</span> Prueba t</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">4.5</span> Conclusiones</a></li>
  <li><a href="#referencias-bibliográficas" id="toc-referencias-bibliográficas" class="nav-link" data-scroll-target="#referencias-bibliográficas"><span class="header-section-number">4.6</span> Referencias Bibliográficas</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estatus Social Subjetivo, Nivel Educacional y su Impacto en la Identificación Partidaria en Chile</h1>
<p class="subtitle lead">Estadística Correlacional 2024, Carrera de Sociología - Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Javiera Morales </p>
             <p>Catalina Silva </p>
             <p>Catalina Santos </p>
             <p>Micaela Peña </p>
             <p>Martina Villatoro </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">19 de noviembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    Para la sociología la identificación partidaria es importante de estudiar para comprender las dinámicas sociales, ya que es necesario comprender cómo se lleva respecto a la estratificación y percepción de estatus, la forma en que incide en la participación en la política a través de partidos. Pero, ¿Cuáles son las variables que influyen en la decisión de los sujetos para llegar a identificarse en partidos políticos? El estudio busca conocer la relación entre la variable de “Estatus Social Subjetivo” y “Nivel Educacional” con los partidos políticos. En base a la bibliografía, se evidencia que ambas variables son fundamentales como base para la identificación partidaria, ya que ambas son espacios sociales donde se reproducen orientaciones políticas.Teniendo como la hipótesis 1 propone que el nivel educativo tiene una relación positiva con la identificación partidaria, donde las personas con mayor educación están más inclinadas a identificarse con un partido político. Por otro lado, la hipótesis 2 propone que quienes se identifican partidariamente tienen más estatus social subjetivo que quienes no se identifican partidariamente. Para la investigación se realizó un estudio cuantitativo de la base de datos ELSOC, encuesta aleatoria diseñada por investigadores del Centro de Estudios de Conflicto y Cohesión Social (COES) en este caso se utilizó la ola 2022, donde se recolectó información de 18.035 personas. Para llegar a los resultados se realizaron dos análisis bivariados y uno descriptivo, donde se utilizaron distintas estrategias estadísticas para encontrar correlaciones entre las variables escogidas. Si bien las variables “Identificación política” y “Estatus Social Subjetivo” juegan un rol importante en la identificación partidaria, las correlaciones son débiles. Se rechaza la hipótesis nula pero sería necesario que a futuros estudios se agregue una mayor cantidad de variables que demuestren la identificación partidaria. Finalmente en los resultados se encontró que la mayoría de los sujetos (70.4%) no se identifican con ningún partido político.
  </div>
</div>


</header>


<section id="introducción." class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción.</h1>
<p>En los últimos años en Chile se ha experimentado un significativo descenso en lo que son los niveles de identificación partidaria. Esta situación, va acompañada de una creciente percepción de descontento político y de manejo elitista de lo que son las instituciones políticas, lo que refleja de cierta forma una desconexión entre la ciudadanía y los partidos políticos tradicionales (Torres, 2009). Si bien estas tendencias podrían significar una despolitización generalizada, persisten en gran parte de la población chilena. Este contraste plantea ciertas interrogantes sobre aquellos factores subyacentes que moldean la identificación partidaria, particularmente en un contexto de desigualdad estructural.</p>
<p>La presente investigación aborda esta problemática desde una perspectiva sociológica, explorando así como el estatus social subjetivo y el nivel educacional (ambos vinculados a aquellas dinámicas de estratificación social) influyen en lo que es la identificación partidaria. El estatus social subjetivo se define como la percepción individual sobre la posición propia en la estructura social, la cual está influida por aquellos factores objetivos como lo puede ser la ocupación, nivel educativo y nivel socioeconómico, además de los grupos de referencia automática como familia y amistades (Castillo, Miranda y Madero, 2013). Este concepto no solo refleja cómo los individuos se perciben en su entorno, sino que además afecta sus expectativas, aspiraciones y orientaciones ideológicas, que a menudo se alinean con aquellos intereses percibidos en su contexto social (Wright, 1997).</p>
<p>En suma, el nivel educativo se presenta como un elemento clave en lo que es la formación de preferencias políticas. En Chile, el sistema educativo ha sido históricamente desigual, con disparidades en lo que es la calidad y asimismo el acceso según aquellos recursos disponibles (Gayo, Otero y Mendes, 2019). Estas desigualdades no sólo condicionaron aquellas trayectorias de vida más individuales , sino que además refuerza lo que son las estructuras de poder y relación de clases, influyendo en las orientaciones ideológicas y partidarias de los sujetos (Ávila, 2005). Estudios demuestran que a niveles más altos de educación están más asociados a un mayor compromiso cívico y partidario, ya que la educación provee de habilidades críticas y conocimientos necesarios para interpretar dinámicas políticas y sociales, además de incentivar la participación en los sistemas democráticos (Luna, J.P, 2019).</p>
<p>A nivel latinoamericano hay un desplome en cuanto al apoyo a los partidos políticos, porcentaje el cual ha ido decayendo durante los años hasta la actualidad. Según Latinobarómetro (2023) El 80% de los encuestados chilenos están en desacuerdo con la afirmación: “Los partidos políticos funcionan bien”. Y el 77% del total de los países está en desacuerdo también. El análisis de las variables en este estudio se fundamenta en antecedentes internacionales que han explorado la relación entre identificación partidaria y nivel educacional. Un ejemplo relevante es el estudio de Brasil que relaciona lo que es la identidad partidaria y nivel educacional. Este estudio muestra una relación entre bajos niveles de educación y baja identificación paritaria siendo esta un 27,8% en contraparte con un 44,2% de personas que declaran poseer educación superior. (Rojas, 2013, pg. 16)</p>
<p>En el caso de Chile se busca examinar si estas tendencias se replican, considerando las particularidades de su propio contexto socioeducativo.</p>
<p>En base a la justificación anterior, la investigación tiene como objetivo principal analizar la relación entre lo que es identificación partidaria y las variables independientes como el estatus social subjetivo y nivel educacional. Es por esto, que se busca contribuir en la comprensión de cómo estas variables, relacionadas con la estratificación social, se relacionan con las orientaciones políticas en Chile. Para lo anterior se planeta 2 hipótesis: Quienes se identifican partidariamente tienen menos estatus social subjetivo que quienes no se identifican partidariamente. El nivel educativo tiene una relación positiva con la identificación partidaria, donde las personas con mayor educación están más inclinadas a identificarse con un partido político.</p>
</section>
<section id="metodología" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metodología</h1>
<p>El Estudio Longitudinal Social de Chile (EL SOC) es una encuesta diseñada por investigadores pertenecientes al Centro de Estudios de Conflicto y Cohesión Social (COES). La cobertura geográfica del diseño muestral final de la ola 1 de ELSOC COES proporciona una cobertura adecuada de las ciudades más grandes del país (Gran Santiago, Gran Valparaíso y Gran Concepción), así como ciudades más pequeñas, y también asegura la representación de personas en el norte y sur del país. La muestra poblacional de esta encuesta fue una muestra aleatoria simple entre los adultos entre 18 y 75 años que habitan la vivienda. Además de ser aplicada en los años 2016, 2017, 2018, 2019, 2021 y 2022 El instrumento de recolección de información consiste en un cuestionario estructurado (tipo encuesta) aplicado a todos los participantes. El cuestionario fue diseñado para medir una serie de aspectos conceptualmente relevantes que permiten caracterizar los niveles de conflicto y cohesión social en Chile, enfatizando su evolución a lo largo del tiempo. Los principales temas de interés analítico abordados por la encuesta corresponden a los módulos en los cuales se estructura: Ciudadanía y democracia, redes sociales e interacciones intergrupales, legitimidad y desigualdad social, conflicto social dimensión barrial, salud y bienestar además de una caracterización sociodemográfica y género (agregado a la encuesta a partir de 2019). El proceso de muestreo de la muestra original se realizó en base a los datos del pre-censo del año 2011, los cuales fueron formateados por el CIT. Se utilizaron bloques urbanos, para determinar qué bloques eran urbanos, se empleó la codificación del tipo de localidad (urbana o rural) contenida en la base de datos del pre-censo de 2011. Los bloques que habían sido previamente geo-referenciados por el CIT se conservaron para el muestreo.<br>
El marco muestral final contiene 120.857 bloques. El número de viviendas seleccionadas en cada bloque varió según el estrato. Para la selección de entrevistados los encuestadores visitaron cada vivienda seleccionada e intentaron llevar a cabo la entrevista. Cuando había más de un adulto en la vivienda, uno fue seleccionado usando una muestra aleatoria simple.</p>
</section>
<section id="datos" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Datos</h1>
<section id="identificación-partidaria" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="identificación-partidaria"><span class="header-section-number">3.1</span> Identificación partidaria</h2>
<p>La primera variable dependiente es identificación partidaria y esta tiene un nivel de medición nominal. Además, está utilizó la unidad de medida en porcentaje y el código de esta variable es c16 y utiliza el siguiente fraseo: ¿Cuál de los siguientes partidos políticos representa mejor sus intereses, creencias y valores?. Posteriormente, la recodificamos dónde empezamos por eliminar los NA que fueron -999, -888, -777 y -666 y luego integramos el valor 0 dando a entender que no se identifica con ningún partido, está que se modificó sería la opción “ninguno” y el valor 1 significa que se identifica con algún partido, aquí se modificaron las siguientes categorías: PC, PH, RD, PRO, Evopoli, PPD, PDC, PRI, RN, UDI, PS, PRSD, CS, PDG y PRL. También tuvimos que dicotomizar esta variable. Y el objetivo que busca es conocer la identificación política de los individuos entrevistados.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>proc_elsoc$Identificación_Partidaria was converted to a data frame</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
------------------------------------------------------------------------------------------------
No   Variable                    Stats / Values        Freqs (% of Valid)   Valid      Missing  
---- --------------------------- --------------------- -------------------- ---------- ---------
1    Identificación_Partidaria   1. No se identifica   10513 (70.4%)        14924      0        
     [character]                 2. Si se identifica    4411 (29.6%)        (100.0%)   (0.0%)   
------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="nivel-educacional" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="nivel-educacional"><span class="header-section-number">3.2</span> Nivel educacional</h2>
<p>La segunda variable es la de nivel educacional que pertenece al nivel de medición ordinal. Por otra parte se utilizó el porcentaje como la unidad de medida en esta variable y el código de la variable es m01 y utiliza el siguiente fraseo: ¿Cuál es su nivel educacional? Indique el tipo de estudio actual (si estudia actualmente) o el último tipo aprobado (si no estudia actualmente). Tuvimos que recodificar todos los NA que fueron -999, -888, -777 y -666 para que fuera legible al momento de verla. Además por otro lado esta variable no presenta dimensiones, ya que este tipo de variable es unidimensional y solo busca el orden de las categorías. Esta busca saber de qué manera influye el nivel educacional que tienen las personas en la sociedad.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>proc_elsoc$Nivel_Educacional was converted to a data frame</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
-------------------------------------------------------------------------------------------------
No   Variable            Stats / Values                 Freqs (% of Valid)   Valid      Missing  
---- ------------------- ------------------------------ -------------------- ---------- ---------
1    Nivel_Educacional   1. Educación Básica o Prepar   1434 ( 9.6%)         14924      0        
     [factor]            2. Educación Básica o Prepar   1760 (11.8%)         (100.0%)   (0.0%)   
                         3. Educación Media o Humanid   4406 (29.5%)                             
                         4. Educación Media o Humanid   1961 (13.1%)                             
                         5. Estudios de posgrado (mag    239 ( 1.6%)                             
                         6. Sin estudios                 146 ( 1.0%)                             
                         7. Técnica Superior completa   1868 (12.5%)                             
                         8. Técnica Superior incomple    569 ( 3.8%)                             
                         9. Universitaria completa      1634 (10.9%)                             
                         10. Universitaria incompleta    907 ( 6.1%)                             
-------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section>
<section id="estatus-social" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="estatus-social"><span class="header-section-number">3.3</span> Estatus social</h2>
<p>Por último, la tercera variable es la de estatus social subjetivo que tiene un nivel de medición ordinal como la anterior. Esta variable fue la única con una unidad de medida diferente a las demás, ya que medirá sus valores por pesos y su código de interpretación es d01_01, el fraseo que ocupa es el siguiente: En nuestra sociedad, hay grupos que tienden a ubicarse en los niveles más altos y grupos que tienden a ubicarse en los niveles más bajos de la sociedad. Usando la escala presentada, donde 0 es el nivel más bajo y 10 el nivel más alto, ¿Dónde se ubicaría usted en la sociedad chilena?. También tuvimos que recodificar todos los NA que fueron -999, -888, -777 y -666 para que fuera más amigable a la hora de visibilizar. Como bien sabemos, no tiene dimensiones debido a que es categoría ordinal. Y el objetivo de esta es analizar cómo influye el estatus social en la sociedad y todos sus ámbitos.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>proc_elsoc$Estatus_Social was converted to a data frame</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
--------------------------------------------------------------------------------
No   Variable         Stats / Values   Freqs (% of Valid)   Valid      Missing  
---- ---------------- ---------------- -------------------- ---------- ---------
1    Estatus_Social   1. 0              313 ( 2.1%)         14924      0        
     [factor]         2. 1              419 ( 2.8%)         (100.0%)   (0.0%)   
                      3. 2              851 ( 5.7%)                             
                      4. 3             2075 (13.9%)                             
                      5. 4             3314 (22.2%)                             
                      6. 5             5578 (37.4%)                             
                      7. 6             1372 ( 9.2%)                             
                      8. 7              481 ( 3.2%)                             
                      9. 8              350 ( 2.3%)                             
                      10. 9              54 ( 0.4%)                             
                      11. 10            117 ( 0.8%)                             
--------------------------------------------------------------------------------</code></pre>
</div>
</div>
</section>
</section>
<section id="análisis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Análisis</h1>
<section id="identificación-partidaria-y-nivel-educativo" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="identificación-partidaria-y-nivel-educativo"><span class="header-section-number">4.1</span> Identificación partidaria y nivel educativo</h2>
<p>La tabla nos muestra como las proporciones de lo que es la identificación partidaria varía según el nivel educativo. Algunos ejemplos de estos son: Las personas con niveles educativos más bajos como lo son “sin estudios” y “ educación básica o media incompleta”, presentan una mayor proporción de “quienes no se identifican con algún partido político”. Un ejemplo, el 85,6% de quienes no tienen estudios no se identifican con algún partido político, y solo el 14,4% si lo hace. En cuanto a aquellas personas con niveles educativos más altos como lo son “universitaria completa” y “estudios de posgrado”, las proporciones de identificación partidaria aumentan de manera considerable. Por ejemplo: el 60,3% de quienes tienen estudios de posgrado se identifican con algún partido político.</p>
<p>A pesar de que las variables son categóricas, la tendencia central puede interpretarse desde la proporción dominante en cada una de las categorías. Las categorías más altas del nivel educativo presentan más dispersión respecto a lo que es la identificación partidaria, con proporciones mucho más equilibradas entre el “sí” y “no”, mientras que en las categoría más bajas de educación predomina claramente el grupo de “ no se identifica”.</p>
<p>Análisis bivariado Para poder verificar nuestra hipótesis de “El nivel educativo tiene una relación positiva con la identificación partidaria, donde las personas con mayor educación están más inclinadas a identificarse con un partido político”. Se realiza un análisis estadístico considerando las medidas de asociación y prueba de hipótesis.</p>
<p>La tabla de contingencia fue sometida a un test de Chi cuadrado, el que resultó en un valor de 415.262, con un valor p &lt;0.05, indicando que las diferencias entre categorías si son estadísticamente significativas. Por otro lado, el V de cramer= 0.167, indica una relación débil a moderada entre nivel educativo e identificación partidaria. Aunque el efecto no es fuerte, es suficiente para decir que existe una relación significativa entre las variables.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `scale_name` argument of `continuous_scale()` is deprecated as of ggplot2
3.5.0.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `trans` argument of `continuous_scale()` is deprecated as of ggplot2 3.5.0.
ℹ Please use the `transform` argument instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `unite_()` was deprecated in tidyr 1.2.0.
ℹ Please use `unite()` instead.
ℹ The deprecated feature was likely used in the ggmosaic package.
  Please report the issue at &lt;https://github.com/haleyjeppson/ggmosaic&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ESTE-ES-EL-REPORTE--cambiar-nombre-_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table style="border-collapse:collapse; border:none;">
 <tbody><tr>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; border-bottom:1px solid;" rowspan="2">Identificación_Partidaria</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal;" colspan="10">Nivel_Educacional</th>
 <th style="border-top:double; text-align:center; font-style:italic; font-weight:normal; font-weight:bolder; font-style:italic; border-bottom:1px solid; " rowspan="2">Total</th>
 </tr>
 
<tr>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educación Básica o<br>Preparatoria<br>completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educación Básica o<br>Preparatoria<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educación Media o<br>Humanidades completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Educación Media o<br>Humanidades<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Estudios de posgrado<br>(magíster o<br>doctorado)</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Sin estudios</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Técnica Superior<br>completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Técnica Superior<br>incompleta</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Universitaria<br>completa</td>
 <td style="border-bottom:1px solid; text-align:center; padding:0.2cm;">Universitaria<br>incompleta</td>
 </tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">No se identifica</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1055</span><br><span style="color:#333399;">10&nbsp;%</span><br><span style="color:#339933;">73.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1404</span><br><span style="color:#333399;">13.4&nbsp;%</span><br><span style="color:#339933;">79.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">3216</span><br><span style="color:#333399;">30.6&nbsp;%</span><br><span style="color:#339933;">73&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1488</span><br><span style="color:#333399;">14.2&nbsp;%</span><br><span style="color:#339933;">75.9&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">95</span><br><span style="color:#333399;">0.9&nbsp;%</span><br><span style="color:#339933;">39.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">125</span><br><span style="color:#333399;">1.2&nbsp;%</span><br><span style="color:#339933;">85.6&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1230</span><br><span style="color:#333399;">11.7&nbsp;%</span><br><span style="color:#339933;">65.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">391</span><br><span style="color:#333399;">3.7&nbsp;%</span><br><span style="color:#339933;">68.7&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">967</span><br><span style="color:#333399;">9.2&nbsp;%</span><br><span style="color:#339933;">59.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">542</span><br><span style="color:#333399;">5.2&nbsp;%</span><br><span style="color:#339933;">59.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">10513</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">70.4&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  text-align:left; vertical-align:middle;">Si se identifica</td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">379</span><br><span style="color:#333399;">8.6&nbsp;%</span><br><span style="color:#339933;">26.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">356</span><br><span style="color:#333399;">8.1&nbsp;%</span><br><span style="color:#339933;">20.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">1190</span><br><span style="color:#333399;">27&nbsp;%</span><br><span style="color:#339933;">27&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">473</span><br><span style="color:#333399;">10.7&nbsp;%</span><br><span style="color:#339933;">24.1&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">144</span><br><span style="color:#333399;">3.3&nbsp;%</span><br><span style="color:#339933;">60.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">21</span><br><span style="color:#333399;">0.5&nbsp;%</span><br><span style="color:#339933;">14.4&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">638</span><br><span style="color:#333399;">14.5&nbsp;%</span><br><span style="color:#339933;">34.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">178</span><br><span style="color:#333399;">4&nbsp;%</span><br><span style="color:#339933;">31.3&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">667</span><br><span style="color:#333399;">15.1&nbsp;%</span><br><span style="color:#339933;">40.8&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center; "><span style="color:black;">365</span><br><span style="color:#333399;">8.3&nbsp;%</span><br><span style="color:#339933;">40.2&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;  "><span style="color:black;">4411</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">29.6&nbsp;%</span></td> 
</tr>
 
<tr> 
<td style="padding:0.2cm;  border-bottom:double; font-weight:bolder; font-style:italic; text-align:left; vertical-align:middle;">Total</td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1434</span><br><span style="color:#333399;">9.6&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1760</span><br><span style="color:#333399;">11.8&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">4406</span><br><span style="color:#333399;">29.5&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1961</span><br><span style="color:#333399;">13.1&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">239</span><br><span style="color:#333399;">1.6&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">146</span><br><span style="color:#333399;">1&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1868</span><br><span style="color:#333399;">12.5&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">569</span><br><span style="color:#333399;">3.8&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">1634</span><br><span style="color:#333399;">10.9&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">907</span><br><span style="color:#333399;">6.1&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td>
<td style="padding:0.2cm; text-align:center;   border-bottom:double;"><span style="color:black;">14924</span><br><span style="color:#333399;">100&nbsp;%</span><br><span style="color:#339933;">100&nbsp;%</span></td> 
</tr>
<tr><td style="text-align:right; font-size:0.9em; font-style:italic; padding:0.2cm;" colspan="12">χ<sup>2</sup>=415.262 · df=9 · Cramer's V=0.167 · p=0.000</td> 
</tr>
 
</tbody></table>
</div>
</div>
<p>Los resultados respaldan la hipótesis planteada. El nivel educativo se vincula de manera positiva con lo que es la identificación partidaria. Entonces, en base a la muestra se puede decir que a medida que aumenta el nivel educativo, las personas tienden a identificarse con más frecuencia en partidos políticos. Esto puede ser explicado por factores como, un mayor conocimiento y comprensión del sistema político, un mayor interés por la política y acceso a información y además, la educación como promotora de valores cívicos y participación ciudadana. Por otro lado, el tamaño del efecto sugiere que otros factores también pueden influir en la identificación partidaria como lo puede ser la edad, ingreso o contexto social, las que podrían ser variables a considerar en futuros análisis para así tener un entendimiento mucho más completo de la dinámica política.</p>
<p>Desde la perspectiva sociológica, estos hallazgos son consistentes con aquellas teorías que asocian lo que es la educación con una mayor participación política y sentidos de pertenencia social. En contraste, aquella baja participación política que se vincula con los niveles más bajos educativamente, podrían reflejar exclusión política, desconfianza de los partidos o bien barreras estructurales.</p>
<p>Para concluir, el análisis nos confirma una relación positiva y significativa entre las variables estudiadas (nivel educativo e identificación partidaria), aunque no muy fuerte. La educación no solo influye en las actitudes políticas, sino que también demuestra ser un factor importante en la integración y participación ciudadana.</p>
</section>
<section id="estatus-social-e-identificacion-partidaria" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="estatus-social-e-identificacion-partidaria"><span class="header-section-number">4.2</span> Estatus social e Identificacion Partidaria</h2>
</section>
<section id="punto-biserial" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="punto-biserial"><span class="header-section-number">4.3</span> Punto biserial</h2>
<p>Se utilizará el punto biserial la cual es una extensión del coeficiente de Pearsons y se aplica en el caso de tener una variable intervalar dicotómica la cual es “Identificación Partidaria” y otra variable nominal continua “Estatus Social”. Contando con las siguientes hipótesis: Hipótesis nula (H0): No hay relación entre la identificación partidaria y el estatus social subjetivo. Hipótesis alternativa (H2): Que quienes se identifican partidariamente tienen más estatus social subjetivo que quienes no se identifican partidariamente. Las diferencias observadas entre la variable Estatus Social y la variable Identificación Partidaria son significativas y tiene un valor alto (t = 11.95). Teniendo en cuenta que la muestra es grande, ya que los grados de libertad (df) son de 14.922. La probabilidad de error es muy baja, reforzando la significación de la correlación (p-value &lt; 0.001***). Por lo tanto este resultado al ser tan pequeño demuestra que es posible rechazar la hipótesis nula y que existe una evaluación significativa entre la variable intervalar dicotómica y la nominal continua. Además el intervalo de confianza es de [0.08; 0.11], por lo tanto con un 95% de confianza podemos decir que la correlación es distinta y mayor que 0. Finalmente la correlación indica que es 0.0974 por tanto según los criterios de Cohen indica una relación débil entre variables, aunque sea significativa. Además indica ser una correlación positiva y tiene un efecto grande, sin embargo, la fuerza de esta correlación no es lo suficientemente fuerte como para afirmar que alguna de las dos variables explica de manera significativa estadísticamente al otro.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  proc_elsoc$Identificación_Partidaria_num and Estatus_Socialnum
t = 11.955, df = 14922, p-value &lt; 0.00000000000000022
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.08148756 0.11327114
sample estimates:
       cor 
0.09740419 </code></pre>
</div>
</div>
</section>
<section id="prueba-t" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="prueba-t"><span class="header-section-number">4.4</span> Prueba t</h2>
<p>Se realizó una prueba t para muestras independientes con el fin de comparar la identificación partidaria entre el Grupo 0 “No se identifica” y Grupo 1 “Si se identifica” y la variable Estatus Social Subjetivo. Los resultados indicaron una diferencia significativa en la identificación del grupo 0 y grupo 1. Donde tenemos el resultado del grupo 0 el cual es 4.29 y el resultado del Grupo 1 es 4.63. En consecuencia el promedio del grupo 1 es mayor al del Grupo 0.</p>
<p>Por otro lado el intervalo de confianza [-0.40, -0.29] es del 95% para la diferencia de medias, siendo la diferencia entre ambos de -0.11, el hecho de que no se incluya al 0 en este intervalo quiere decir que la diferencia es significativa. Los resultados fueron estadísticamente significativos con una prueba t = -11.96 lo cual indica un resultado negativo, distintos de 0 y con un valor alto estadísticamente. Este resultado se compara con el valor crítico el cual se encuentra asociado a una probabilidad de error alfa, este corresponde a un nivel de error máximo de 0.05 en una prueba de dos colas. Para rechazar la hipótesis nula necesitamos demostrar que las diferencias estadísticamente significativas deben ser distintas a cero, ya que el valor estadístico de t debe sobrepasar el valor crítico de t. Por ello el valor p, el cual es la probabilidad de error de un t específico en este caso p &lt; 0.001***. Por tanto si disminuye del valor máximo (0.05), más disminuye la probabilidad de error, como en nuestro caso es muy bajo, por tanto la probabilidad de que la hipótesis nula sea cierta es casi nula. Ya que a mayor valor t, hay una menor probabilidad de error p.&nbsp;Sabiendo que un p &lt; 0.001 significa que la probabilidad de error es muy baja, por ende se rechaza la hipótesis nula. Por lo tanto con un 95% de confianza se rechazó la hipótesis nula, a lo cual se acepta la hipótesis alternativa que quienes se identifican partidariamente tienen un mayor nivel de Estatus Social Subjetivo que quienes no se identifican partidariamente.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Estatus_Socialnum by Identificación_Partidaria_num
t = -11.955, df = 14922, p-value &lt; 0.00000000000000022
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -0.3991844 -0.2867265
sample estimates:
mean in group 0 mean in group 1 
       4.290688        4.633643 </code></pre>
</div>
</div>
<p>Tanto la correlación punto biserial y la prueba t muestran resultados significativos que permiten rechazar la hipótesis nula y aceptar la hipótesis alternativa, por tanto podemos asegurar que la identificación política está asociada con un estatus social subjetivo más alto. Sin embargo, respecto a los resultados de la correlación punto biserial esta nos indica que la relación entre las variables no es determinante.</p>
</section>
<section id="conclusiones" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">4.5</span> Conclusiones</h2>
<p>Finalmente, luego de realizar un análisis bivariado, univariado y descriptivo estadístico llegamos a la conclusión de que la mayoría de las personas encuestadas (70.4%) no se identifican con ningún partido político. Ahora la muestra de nivel educativo tiene una relación directa con la identificación partidaria, ya que el 15.1% con sus estudios completados se identifican con algún partido político. El Chi cuadrado nos confirma que existe una relación estadísticamente significativa entre el nivel educativo y la identificación partidaria. Pero la fuerza que tiene esta relación es débil, queriendo decir que no es un factor determinante por sí solo en la identificación partidaria. Por lo tanto, el nivel educativo influye en la variable dependiente, pero su impacto es moderado y esto nos dice que se necesitan investigar factores adicionales como cultura, económico, contexto social, etc. Ahora, sucedió algo similar entre la variable de Estatus Social Subjetivo e Identificación Partidaria, ya que los resultados fueron significativos estadísticamente pero la relación es débil. Sin embargo la hipótesis nula fue rechazada y se confirma que la identificación política está asociada a un estatus social subjetivo más alto. Si bien, los anteriores entran como actores determinantes a la hora de identificarse políticamente, aun así nos dimos cuenta de que una gran limitación que teníamos era que nos faltaban más y otros tipos de factores para hacer un mayor análisis respecto a la identificación política en la población. Todo esto para un futuro análisis sociológico sería de mucha ayuda agregar esos factores restantes, ya que el estudio nos demostró que la gente ya no se afilia a los partidos políticos y que durante los últimos años la tendencia o relación con la política ha ido bajando. Entonces para cerrar nuestra hipótesis dejamos una posible pregunta de investigación para estudios futuros: ¿Por qué la gente no sé está identificando con los partidos políticos?.</p>
</section>
<section id="referencias-bibliográficas" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="referencias-bibliográficas"><span class="header-section-number">4.6</span> Referencias Bibliográficas</h2>
<p>Ávila, M. (2005). Socialización, educación y reproducción cultural: Bordieu y Bernstein. Revista Interuniversitaria de Formación del Profesorado, 19(1), 159-174. Universidad de Zaragoza.</p>
<p>Castillo, J., Miranda, D., &amp; Madero, I. (2013). Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Revista de investigaciones latinoamericanas, 48(1), 155-173. https://doi.org/10.1353/lar.2013.0006</p>
<p>Corporación Latinobarómetro. (2023). Informe 2023: La recesión democrática de América Latina. Latinobarómetro. Recuperado de https://www.latinobarometro.org</p>
<p>Gayo, M., Otero, G., &amp; Méndez, M. (2019). Elección escolar y selección de familias: reproducción de la clase media alta en Santiago de Chile. Revista Internacional de Sociología, 77(1), e120. https://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1020/1338</p>
<p>Luna, J. P., 2008. Partidos políticos y sociedad en Chile: trayectoria histórica y mutaciones recientes. En: Reforma de los partidos políticos en Chile. Santiago: CEP-PNUD, pp.&nbsp;75-124. https://www.cieplan.org/wp-content/uploads/2019/12/Reforma-partidos-politicos_Capitulo_1_P3_partidos-politicos-y-sociedad-en-chile_juan-pablo-luna.pdf</p>
<p>Rojas, F. (2013a). Predictores de la identificación partidaria en Brasil 2006-2012. . https://doi.org/10.13140/RG.2.1.1234.3761</p>
<p>Torres, J. (2009). Identificación política en Chile: Síntoma de una paradoja. Working papers ICSO UDP (No.&nbsp;1-2009).</p>
<p>Wright, E. O. (1997). “Class counts: Comparative studies in class analysis”. University of Wisconsin Press. https://ia800807.us.archive.org/22/items/ClassCounts/Class%20counts.pdf</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/correlacional\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>