<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martina Buzio">
<meta name="author" content="Nino Figueroa">
<meta name="author" content="Martina Lagos">
<meta name="author" content="Valentina Montecinos">

<title>Rol de la percepción política, ecónomica y factores sociodemográficos en la confianza en el Gobierno</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Reporte_files/libs/clipboard/clipboard.min.js"></script>
<script src="Reporte_files/libs/quarto-html/quarto.js"></script>
<script src="Reporte_files/libs/quarto-html/popper.min.js"></script>
<script src="Reporte_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Reporte_files/libs/quarto-html/anchor.min.js"></script>
<link href="Reporte_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Reporte_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Reporte_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Reporte_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Reporte_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Reporte_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Reporte_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<style>
  body {
    margin: 2.54cm; /* Márgenes equivalentes a Google Docs */
    text-align: justify; /* Justificación del texto */
  }
</style>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Rol de la percepción política, ecónomica y factores sociodemográficos en la confianza en el Gobierno</h1>
<p class="subtitle lead">Estadística Correlacional 2024, Carrera de Sociología - Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Martina Buzio </p>
             <p>Nino Figueroa </p>
             <p>Martina Lagos </p>
             <p>Valentina Montecinos </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">29 de noviembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    La confianza en instituciones políticas es fundamental para una buena democracia, cohesión social, y desarrollo económico, político y social de los Estados. Es por ello que en el siguiente informe se intentará responder la pregunta: ¿Cómo influyen la percepción de la situación económica, la percepción de la situación política y las características sociodemográficas en la confianza en el Gobierno? De acuerdo a la revisión de estudios anteriores, se tiene la hipótesis que cada una de estas variables poseerá correlación con la confianza en el Gobierno. Para comprobar las cuatro hipótesis, se utilizará la base de datos de la última Encuesta CEP de este año, la cual entrega datos de 1.478 casos. Se realizaron análisis bivariados, utilizando específicamente la correlaciones entre las variables de interés con los métodos de Spearman, Punto Biserial y Pearson dependiendo de la naturaleza de las variables, y los casos perdidos fueron tratados con listwise. Los resultados del análisis indican que existe asociación estadísticamente significativa entre confianza en el gobierno y todas las demás variables, siendo el resultado más concluyente la correlación entre la confianza en el gobierno y la percepción de la situación económica, seguida en tamaño de efecto por la percepción de situación económica.
  </div>
</div>


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>La confianza en las instituciones políticas es fundamental para la estabilidad de las democracias y el desarrollo multidimensional de los países (CEP, 2023). En este trabajo, se pondrá el foco en la confianza en el Gobierno, una variable seleccionada considerando que Chile, como república presidencialista, tiene a este como la principal cara visible de la política nacional. Entre 1996 y 2011, el Gobierno fue mayoritariamente la institución política mejor evaluada en Latinoamérica, superando a los partidos políticos y al Congreso (Bargsted et al., 2017). Estos hallazgos son consistentes con el Estudio Nacional de Opinión Pública (2022) y con los resultados de la última encuesta CEP realiza a mediados de este año. Por estas razones, se ha elegido esta variable como la dependiente y eje de este análisis.</p>
<p>La confianza se define como una posición sobre el comportamiento venidero de un otro, entendiéndose que este puede beneficiar a los efectos de las acciones propias. La confianza entre agentes sociales es esencial para la cooperación y agilización de procesos, mejorando así el desempeño de instituciones, y el desarrollo económico y social (Riffo et al., 2019). Para ello, tanto la confianza interpersonal como hacia las instituciones son relevantes (estadísticamente suelen tener comportamiento similar, siendo directamente proporcionales). Como se mencionó, se ha elegido la confianza institucional para este trabajo, en específico a la institución política que es el Gobierno.</p>
<p>De acuerdo a Saldaña y Pineda (2019), la literatura sobre confianza en instituciones políticas puede explicarse desde dos enfoques principales. El primero atribuye la confianza a satisfacción con un contexto socioeconómico particular, apego a la institucionalidad y respeto de derechos de los ciudadanos de la institución, teniendo estas variables asociación positiva con la confianza (Morales, 2008; del Tronco 2012 como se citó en Saldaña y Pineda, 2019). El segundo se refiere a interiorización de normas vía socialización, participación en asociaciones voluntarias y confianza interpersonal.</p>
<p>Es por ello que es fundamental comprender las bases que sustentan la relación entre las distintas variables asociadas, ya que aquello ilustra un marco global del funcionamiento de la democracia a raíz de las necesidades, demandas y expectativas de la sociedad chilena.</p>
<p>De este modo, el objetivo de esta investigación es analizar cómo la percepción de la situación política y económica se relaciona con la confianza en el gobierno y sus instituciones, considerando que estas variables están profundamente influenciadas por contextos personales, económicos, sociales y culturales. Además, se busca comprender de qué manera factores como el nivel educativo y el área de residencia afectan esta relación. En este marco, la pregunta de investigación de este trabajo es: <em>¿Cómo influyen la percepción de la situación económica, la percepción de la situación política y las características sociodemográficas en la confianza en el Gobierno?</em> Para abordar este objetivo, se emplearán análisis bivariados entre nuestras variables de interés. Basándonos en el Estudio Nacional de Opinión Pública, creado en base a la encuesta CEP del 2024, planteamos las siguientes 4 hipótesis:</p>
<p>H1: Existe asociación entre las variables percepción de la situación económica y confianza en el gobierno.</p>
<p>H2: Existe asociación entre las variables percepción de la situación política y confianza en el gobierno.</p>
<p>H3: Existe asociación entre las variables área urbano/rural y confianza en el gobierno.</p>
<p>H4: Existe asociación entre las variables nivel educacional y confianza en el gobierno.</p>
</section>
<section id="metodología" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metodología</h1>
<p>Para realizar el análisis sobre este fenómeno, se utilizó la Encuesta Nacional de Opinión Pública CEP N°91 del 2024. Esta es realizada por el Centro de Estudios Públicos, y su objetivo es “conocer las preocupaciones, preferencias y necesidades de la población así como reflejar las continuidades y cambios que experimenta la sociedad chilena” (Centro de Estudios Públicos [CEP], s.f). Se aplicó entre el 31 de mayo y el 14 de julio de 2024 en 1.478 personas mayores de 18 años residentes en Chile, de 118 comunas del país, a través de entrevistas cara a cara realizadas por un/a encuestador/a (CEP, 2024). El diseño de la muestra se hizo de manera probabilística, siendo proporcional a la población mayor de 18 años del país, por estratificación de región y zona urbana/rural, y la selección fue aleatoria en cada etapa, es decir, primero por manzana/entidad, luego por vivienda y finalmente por persona entrevistada.</p>
<p>En primer lugar, de la base de datos de la encuesta se seleccionó la variable “confianza_6_i”, que se renombró a “conf_gob”, ya que mide la confianza en el Gobierno, y es la variable que será utilizada como dependiente en esta investigación. Pertenece a la pregunta MB_14 del Módulo Básico (MB), que mide la confianza en 20 instituciones mediante una escala ordinal de Likert con 4 opciones: “Mucha confianza” (1), “Bastante confianza” (2), “Poca confianza” (3) y “Nada de confianza” (4). Para facilitar el análisis, la escala debió ser recodificada para que representara un orden de menor a mayor confianza, asignándole el valor 1 a la opción “Nada de confianza”, y así consecutivamente.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de frecuencia de Confianza en el Gobierno</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">valid.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Nada de confianza</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">74</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.32</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Poca confianza</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">170</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12.21</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">17.53</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Bastante confianza</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">617</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">44.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">44.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">61.85</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Mucha confianza</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">531</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">38.15</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">38.15</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Como variables independientes fueron seleccionadas 4 variables: “percepcion_2”, “percepcion_38”, “zona_u_r” y “esc_nivel_1_c”. Las dos primeras variables, correspondientes a las preguntas MB_2 y MB_6 del Módulo Básico (MB), miden de forma ordinal, por medio de escalas Likert la percepción de la situación económica y la situación política actuales, por lo que fueron renombradas a “situacion_econ” y “situacion_politica” respectivamente.</p>
<p>La variable percepción económica tiene 5 opciones, que son: “Muy mala” (1), “Mala” (2), “Ni buena, ni mala” (3), “Buena” (4), y “Muy buena” (5), mientras que la de percepción política contaba con las mismas opciones, pero estas estaban ordenadas al revés, es decir, de “Muy buena” a “Muy mala”, por lo que se decidió recodificarla para que siguiera el mismo orden de la anterior.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de frecuencia de Situación Política</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">valid.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Muy mala</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">19</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.36</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Mala</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">82</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.26</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Ni buena, ni mala</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">369</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">26.51</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">26.51</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">33.76</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Buena</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">606</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">43.53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">43.53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">77.3</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Muy buena</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">316</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">22.7</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">22.7</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de frecuencia de Situación Económica</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">valid.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Muy mala</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">263</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">18.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">18.89</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">18.89</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Mala</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">530</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">38.07</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">38.07</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">56.97</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Ni buena, ni mala</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">487</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">34.99</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">34.99</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">91.95</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Buena</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">99.14</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Muy buena</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.86</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.86</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>La tercera variable no es una pregunta del cuestionario, sino que es parte de la estrategia de muestreo y el perfil de las zonas donde se aplicó la encuesta. Es una variable nominal dicotómica, que expresa si el encuestado vive en un área urbana o rural, donde se le asignó el valor 1 a urbana y 2 a rural, pero para su mejor manejo fue recodificada en valores de 0 a 1, en el mismo orden.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de frecuencia de Área urbano/rural</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">valid.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Urbano</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1217</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">87.43</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">87.43</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">87.43</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Rural</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">175</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12.57</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12.57</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>En último lugar, la cuarta variable es de tipo intervalar, y mide el mayor nivel de escolaridad alcanzado por el encuestado, por lo que se la renombró a “nivel_educ” en la base de datos. Esta corresponde al módulo socioeconómico, se divide en 10 opciones que van desde “Sin estudios” (0) a “Postgrado completo” (10), y está contenida entre 2 preguntas, que serían la S7.A y la S7.B, esto porque son preguntas encadenadas a una anterior, que pregunta si se encuentra estudiando actualmente, y si el encuestado responde que sí, entonces pregunta por el nivel actual que cursa, y si contesta que no, pregunta por el último nivel alcanzado.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Tabla de frecuencia de Nivel Educacional</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">val</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">label</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">frq</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">raw.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">valid.prc</td>
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: italic; font-weight: normal; padding: 0.2cm; border-bottom: 1px solid black;">cum.prc</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Sin estudios formales</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.65</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Básica incompleta / Primaria o preparatoria incompleta</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">111</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.97</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7.97</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8.62</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Básica completa / Primara o preparatoria completa</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">166</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.93</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">11.93</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">20.55</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Media científico humanista o media técnico profesional incompleta / Humanidades incompleta</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">172</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">12.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">32.9</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Media científico humanista o media técnico profesional completa / Humanidades completa</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">411</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">29.53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">29.53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">62.43</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">5</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Instituto técnico (CFT) o instituto profesional incompleto (carreras 1 a 3 años)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">57</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.09</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">4.09</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">66.52</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Instituto técnico (CFT) o instituto profesional completo (carreras 1 a 3 años) / Hasta suboficial de FFAA/Carabineros</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">138</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.91</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9.91</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">76.44</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">7</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Universitaria incompleta (carreras 4 o más años)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">96</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.9</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">6.9</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">83.33</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">8</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Universitaria completa (carreras 4 o más años) / oficial de FFAA/Carabineros</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">186</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">13.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">13.36</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">96.7</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">9</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Postgrado (postítulo, Máster, Magíster, Doctorado) incompleto</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">14</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.01</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.01</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">97.7</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Postgrado (postítulo, Máster, Magíster, Doctorado) completo</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.3</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">0</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top; border-bottom: double;">NA</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Posteriormente, se procedió a recodificar los valores -8 (“No contesta”) y -9 (“No sabe”) a valores perdidos (NA), para luego saber cuántos tenía nuestra muestra y decidir con qué método manejarlos. En total, habían 102 NA, principalmente concentrados en percepción política y confianza en el gobierno. Como la muestra es de 1478 observaciones, y por lo tanto, constituía menos del 10%, se decidió eliminarlos con <em>listwise</em>. Para la falsación de la hipótesis 1 y 2 se utilizará la medida de correlación Spearman, puesto que las variables son ordinales, para la 3 se usará punto biserial, porque una de las variables es ordinal y la otra nominal dicotómica, y por último, para la 4 se usará Pearson, porque una variable es ordinal y la otra intervalar. La manera en que se medirá el tamaño de efecto en todas estas será con los criterios de Cohen, donde &lt;0,1 es muy pequeño, de 0,1 a 0,3 es pequeño, de 0,3 a 0,5 es moderado, y &gt;0,5 es grande.</p>
</section>
<section id="análisis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análisis</h1>
<section id="análisis-de-descriptivosunivariados" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="análisis-de-descriptivosunivariados"><span class="header-section-number">3.1</span> Análisis de descriptivos/univariados</h2>
<p>Para dar inicio al análisis del fenómeno que se pretende estudiar, se comenzará con un análisis univariado de las variables con respecto a estadíticos descriptivos y frecuencias.</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla de Estadísticos Descriptivos</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">moda</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rango</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">desviacion_estandar</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">coeficiente_variacion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Confianza en el Gobierno</td>
<td style="text-align: right;">1.8469828</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.8326581</td>
<td style="text-align: right;">0.4508207</td>
</tr>
<tr class="even">
<td style="text-align: left;">Situación política</td>
<td style="text-align: right;">2.1968391</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.9013394</td>
<td style="text-align: right;">0.4102892</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Situación económica</td>
<td style="text-align: right;">2.3304598</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.8916856</td>
<td style="text-align: right;">0.3826222</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nivel educacional</td>
<td style="text-align: right;">4.5416667</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">2.3253647</td>
<td style="text-align: right;">0.5120069</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Área urbana/rural</td>
<td style="text-align: right;">0.1257184</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3316509</td>
<td style="text-align: right;">2.6380457</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Con respecto a la variable dependiente: <strong>confianza en el gobierno</strong>, en esta tabla se ve, primero, que la media de la muestra siendo cercana a 2 indica que en promedio los resultados se reúnen en torno a la “Poca confianza” en el Gobierno. La mediana es de 2, reflejando que el punto central de la distribución posee “Poca confianza” en el Gobierno, esto quiere decir que el 50% de los datos se encuentran por debajo de este valor y el 50% por encima. La moda es de 2 también, lo que significa que la respuesta más común es de “Poca confianza”. Por otra parte, la desviación estándar de aproximadamente 0.833 es relativamente baja, lo que muestra que la mayoría de las respuestas están cerca del promedio, y que en general, se encuentran entre “Nada de confianza” y “Poca confianza”. Todo lo anterior expresa que la opinión de los encuestados posee una tendencia general hacia la desconfianza gubernamental.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Por último, las frecuencias también reflejan lo mencionado anteriormente, ya que de las 1392 observaciones, 531 personas respondieron que sentían “Nada de confianza”, lo que es un 38.15% de la muestra, y 617 respondieron “Poca confianza”, lo que es un 44.32%, y que junto a la alternativa anterior, componen el 82.47% del total. Además, 170 personas respondieron sentir “Algo de confianza”, lo que es el 12.21%, y 74 personas respondieron sentir “Mucha confianza”, lo que es el 5.32%.</p>
<p>Siguiendo con la variable independiente de <strong>percepción de la situación económica</strong>, la media, cercana a 2 indica que en promedio los resultados se acercan a una “Mala” percepción de la situación económica. La mediana, es de 2, reflejando que el punto central de la distribución posee una “Mala” percepción. La moda es de 2, lo que refleja que la respuesta más popular fue también de una “Mala” percepción. Por último, la desviación estándar es de aproximadamente 0.9, lo que es relativamente baja, por lo que el resto de la muestra tiende a concentrarse cercanamente al promedio, lo que es visible a su vez en la tabla de frecuencias.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico representa los datos obtenidos en la encuesta en valores límites del 1 al 5, cada uno representando un nivel sobre la percepción de la situación económica del país.</p>
<p>Luego, con respecto a la variable de <strong>percepción de la situación política</strong>, la media de la muestra indica que en promedio las personas encuestadas posee una “Mala” percepción de la situación política. La mediana es de 2 reflejando que el punto central de la distribución posee una “Mala” percepción. Por otro lado, la moda es también de 2, lo que significa que la mayoría de las personas poseen una “Mala” percepción. Por último, la desviación estándar es de 0.9 aproximadamente, lo que, nuevamente, es baja y significa que la mayoría de resultados se concentra en torno al promedio, lo que se puede ver reflejado en la siguiente tabla de frecuencias.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A continuación, en la variable sobre <strong>nivel educacional</strong>, la media de la muestra indica que en promedio las personas encuestadas posee un nivel educacional de “Media científico humanista o media técnico profesional completa / Humanidades completa” pues el valor 4.542 se aproxima a 5. La mediana, al igual que la moda, se encuentran en el valor 4, que es “Media científico humanista o media técnico profesional completa / Humanidades completa”. Por último, la desviación estándar de 2.32, que indica que hay una mayor dispersión de los datos en torno al promedio, expresado en las frecuencias.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Finalmente, como la variable <strong>zona rural/urbana</strong> es nominal dicotómica, por lo que toma dos valores, el 0 para área urbana y 1 para área rural se mencionará la moda, que es 0 y significa que la mayoría de las personas pertenecen al área urbana, lo que también se refleja en las siguientes frecuencias con una gran diferencia.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="análisis-estadísticosbivariados" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="análisis-estadísticosbivariados"><span class="header-section-number">3.2</span> Análisis estadísticos/bivariados</h2>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Tabla de Correlaciones</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Variables</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Coeficiente</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">p_valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Confianza en el Gobierno ~ Situación Económica</td>
<td style="text-align: right;">0.44270</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Confianza en el Gobierno ~ Situación Política</td>
<td style="text-align: right;">0.35854</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Confianza en el Gobierno ~ Nivel Educacional</td>
<td style="text-align: right;">0.08554</td>
<td style="text-align: right;">0.00140</td>
</tr>
<tr class="even">
<td style="text-align: left;">Confianza en el Gobierno ~ Área Urbana/Rural</td>
<td style="text-align: right;">-0.05264</td>
<td style="text-align: right;">0.04956</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<section id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-situación-económica-situacion_econ" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-situación-económica-situacion_econ"><span class="header-section-number">3.2.1</span> Análisis entre la correlación de las variables <em>Confianza en el Gobierno</em> (conf_gob) y <em>Situación Económica</em> (situacion_econ)</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Confianza en el Gobierno ~ Situación Económica</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Métrica</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Coeficiente</td>
<td style="text-align: right;">0.4426978</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-valor</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Continuando ahora con los análisis bivariados, primero se hizo una correlación entre las variables <strong>confianza en el Gobierno</strong> y <strong>percepción de la situación económica</strong>, y los resultados obtenidos en la prueba Spearman en R para estas variables se concluye que con un p &lt; 0.01 es estadísticamente significativo para con un 99% de confianza rechazar la hipótesis nula de no asociación entre variables, existiendo evidencia a favor de la H1 sobre asociación entre la confianza en el Gobierno y la situación económica. Por otro lado, el coeficiente de correlación de Spearman (r =0.4426978) indica que la asociación entre estas variables es positiva, y según Cohen el tamaño de efecto es moderado. Como el coeficiente de correlación es positivo, la relación entre percepción de la situación económica y confianza en el Gobierno es directamente proporcional, es decir, a una mejor percepción de la situación económica existe una mayor confianza en el Gobierno y viceversa.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico de dispersión muestra la relación entre la percepción de la situación económica (eje X) y la confianza en el gobierno (eje Y). En el eje X los puntos están más concentrados en los valores 2 y 3, y el del eje Y la mayoría de los puntos se encuentra en los valores 1 y 2, que corresponden a “Nada de confianza”. Esto refleja que la mayoría de los encuestados tienen percepciones económicas negativas o neutrales, y además, niveles bajos de confianza en el Gobierno.</p>
</section>
<section id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-situación-política-situacion_politica" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-situación-política-situacion_politica"><span class="header-section-number">3.2.2</span> Análisis entre la correlación de las variables <em>Confianza en el Gobierno</em> (conf_gob) y <em>Situación Política</em> (situacion_politica)</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Confianza en el Gobierno ~ Situación Política</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Métrica</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rho</td>
<td style="text-align: left;">Coeficiente</td>
<td style="text-align: right;">0.3585448</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-valor</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>En segundo lugar, para la correlación entre <strong>confianza en el Gobierno</strong> y <strong>percepción de la situación política</strong>, según los resultados obtenidos en la prueba Spearman en R para estas variables se concluye que con un p &lt; 0.01 es estadísticamente significativo para con un 99% de confianza rechazar la hipótesis nula de no asociación entre variables, existiendo evidencia a favor de la H2 sobre asociación entre ellas. Por otro lado, el coeficiente de correlación de Spearman (r = 0.3585448) indica que la asociación entre estas variables es positiva, y según Cohen el tamaño de efecto es moderado. Como el coeficiente de correlación es positivo, la relación entre percepción de la situación política y confianza en el Gobierno es directamente proporcional, es decir, a una mejor percepción de la situación política existe una mayor confianza en el Gobierno y viceversa.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico muestra la relación entre la percepción de la situación política (eje X) y la confianza en el Gobierno (eje Y). Los datos están concentrados en niveles bajos de confianza en el gobierno (valores 1 y 2 en el eje Y) y en percepciones negativas o neutras de la situación política (valores 2 y 3 en el eje X). Por otro lado, la mayor densidad se encuentra en la intersección entre “Poca confianza” y percepciones “Mala” o “Ni buena ni mala”.</p>
</section>
<section id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-nivel-educacional-nivel_educ" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-nivel-educacional-nivel_educ"><span class="header-section-number">3.2.3</span> Análisis entre la correlación de las variables <em>Confianza en el Gobierno</em> (conf_gob) y <em>Nivel Educacional</em> (nivel_educ)</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Confianza en el Gobierno ~ Nivel Educacional</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Métrica</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cor</td>
<td style="text-align: left;">Coeficiente</td>
<td style="text-align: right;">0.0855363</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-valor</td>
<td style="text-align: right;">0.0014017</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>En tercer lugar, en la correlación entre <strong>confianza en el Gobierno</strong> y <strong>nivel educacional</strong>, según los resultados obtenidos en la prueba de Pearson en R para estas variables se concluye que con un p &lt; 0.01 es estadísticamente significativo con un 99% de confianza rechazar la hipótesis nula de no asociación entre variables, existiendo evidencia a favor de la HA sobre una asociación entre ellas. Por otro lado, el coeficiente de correlación de Pearson (r = 0.0855363) indica que la asociación entre estas variables es positiva, y según Cohen el tamaño de efecto es muy pequeño. Como el coeficiente de correlación es positivo, la relación entre nivel educacional y confianza en el Gobierno es directamente proporcional, es decir, a un mayor nivel educacional, existe una mayor confianza en el Gobierno.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico10.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico ilustra la relación entre la confianza en el Gobierno y el nivel educativo. Los puntos muestran una leve tendencia ascendente, lo que podría indicar una relación positiva muy débil entre estas variables. Sin embargo, el nivel educativo se mantiene concentrado alrededor de valores intermedios (aproximadamente entre 4 y 6) en casi todos los niveles de confianza. La línea de tendencia, acompañada de un intervalo de confianza estrecho, refuerza la idea de que el nivel educativo no varía significativamente con la confianza en el Gobierno. En conclusión, aunque se observa un pequeño aumento, no parece haber una asociación sustancial entre ambas variables.</p>
</section>
<section id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-área-urbanarural-area" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="análisis-entre-la-correlación-de-las-variables-confianza-en-el-gobierno-conf_gob-y-área-urbanarural-area"><span class="header-section-number">3.2.4</span> Análisis entre la correlación de las variables <em>Confianza en el Gobierno</em> (conf_gob) y <em>Área Urbana/Rural</em> (area)</h3>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Confianza en el Gobierno ~ Área Urbana/Rural</caption>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Métrica</th>
<th data-quarto-table-cell-role="th" style="text-align: right; font-weight: bold; color: mistyrose !important; background-color: rgba(180, 82, 205, 255) !important;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">cor</td>
<td style="text-align: left;">Coeficiente</td>
<td style="text-align: right;">-0.0526440</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">p-valor</td>
<td style="text-align: right;">0.0495627</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>Por último, para la correlación entre <strong>confianza en el Gobierno y zona rural/urbana</strong>, según los resultados obtenidos en la prueba de punto biserial en R para estas variables se concluye que con un valor p &lt; 0.05 es estadísticamente significativo con un 95% de confianza rechazar la hipótesis nula de no asociación entre variables, existiendo evidencia a favor de la HA sobre una asociación entre ellas. Según los datos obtenidos es posible interpretar que las personas que viven en zonas rurales tienen una menor confianza en el Gobierno que quienes viven en zonas urbanas. Por otro lado, el coeficiente de correlación Punto biserial (r = -0.05264399) indica que la asociación entre estas variables es negativa, y según Cohen el tamaño de efecto es muy pequeño.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="input/img/grafico8.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico muestra la distribución de las respuestas de los encuestados con respecto a los valores que fueron recodificados como 1, 2, 3 y 4 en relación a la confianza en el Gobierno que se tiene según la zona en la que habitan, sea esta una área rural o urbana. La mayoría de los datos en ambas opciones se agrupa en el valor 2, el cual representa poca confianza.</p>
</section>
</section>
</section>
<section id="conclusiones" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusiones</h1>
<p>En síntesis, del análisis bivariado se puede extraer que la asociación más fuerte con la variable de confianza en el Gobierno es con la variable de percepción de la situación económica, seguida por la de percepción de la situación política, ambas a su vez estadísticamente significativas. Por otro lado, el nivel educativo y la zona urbana/rural tienen una relación más débil con confianza en el Gobierno, pero de igual forma estadísticamente significativa. Con esta información, se puede dar respuesta a la pregunta de investigación: <em>¿Cómo influyen la percepción de la situación económica, la percepción de la situación política y las características sociodemográficas en la confianza en el Gobierno?</em> Se puede decir que todas las variables influyen en la confianza en el Gobierno, siendo la percepción de la situación política y económica las que tienen la mayor influencia en esta.</p>
<p>Esto aporta a la literatura sobre el tema, ya que comprueba que, efectivamente, la confianza en la institución del Gobierno se ve influida por la percepción de la situación económica, como fue mencionado por Saldaña y Pineda (2019), de una manera importante, y que también, hay una influencia de factores sociodemográficos, como lo son el nivel educacional y la zona de residencia. Por otro lado, otorga reproducibilidad, ya que se pueden utilizar los mismos procedimientos para analizar este fenómeno con otros datos.</p>
<p>Por último, una de las limitaciones que este informe pudo contemplar fue que en el proceso de eliminar los casos perdidos se identificó que la mayor cantidad de NA se encontraban en la variable de confianza en el Gobierno, que si bien no alcanzaba a ser el 5% de las observaciones, igual es relevante, puesto que indica que muchas personas evitan responder su grado de confianza en el Gobierno, por lo que sería interesante que otros estudios podrían analizar este suceso con una muestra mayor.</p>
</section>
<section id="bibliografía" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bibliografía</h1>
<p>Centro de Estudios Públicos. (s.f.). <em>Encuesta CEP</em>. https://www.cepchile.cl/opinion-publica/encuesta-cep</p>
<p>Centro de Estudios Públicos. (2024). Encuesta CEP_91: <em>Manual de Usuario</em>. https://static.cepchile.cl/uploads/cepchile/2024/07/06-220349_m3ge_Manual-del-Usuario-CEP-91.pdf</p>
<p>Riffo, F., Pérez, D., Salazar, C., &amp; Acuña, A. (2019). ¿Qué influye en la confianza política en las instituciones? Evidencia empírica para Chile. <em>Revista Facultad de Ciencias Económicas</em>, 27(2), 83-104. https://doi.org/10.18359/rfce.3517</p>
<p>Saldaña, V., y Pineda, M. (2019). Confianza en instituciones políticas: Factores que explican la percepción de confianza en Chile. <em>Temas sociológicos, (25)</em>, 231-258. https://dialnet.unirioja.es/servlet/articulo?codigo=7958105</p>
<p>Bargsted, Somma &amp; Castillo (2017) Political Trust in Latin America en Zmerli &amp; W. G. van den Meer (Ed.), <em>Handbook of Political Trust</em> (pp.&nbsp;395-417). Edward Elgar Publishing</p>
<p>Le Foulon, C. (2022) .<em>Estudio Nacional de Opinión Pública: Encuesta CEP 86</em> [Diapositiva de PowerPoint]. Centro de Estudios Públicos. https://static.cepchile.cl/uploads/cepchile/2022/06/CEP86_CONF_v4.pdf</p>
<p>Irarrázabal, I. &amp; Cruz, F. (2023) <em>Confianza institucional en Chile: un desafío para el desarrollo (Informe n°682)</em>. Carmen Le Foulon y Aldo Mascareño. https://www.cepchile.cl/investigacion/confianza-institucional-en-chile-un-desafio-para-el-desarrollo/</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>