<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Estadística Correlacional - Inferencia, asociación y reporte">

<title>Trabajo Estadistica – Estadística Correlacional</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../..//files/logo-correlacional-transp.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<meta property="og:title" content="Trabajo Estadistica – Estadística Correlacional">
<meta property="og:description" content="">
<meta property="og:image" content="https://correlacional.netlify.app/files/logo-correlacional.png">
<meta property="og:site_name" content="Estadística Correlacional">
<meta property="og:locale" content="es">
<meta property="og:image:height" content="533">
<meta property="og:image:width" content="466">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Estadística Correlacional</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../news/index.html"> 
<span class="menu-text">Informaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../assignment/index.html"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../trabajos.html"> 
<span class="menu-text">Trabajos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../resource/index.html"> 
<span class="menu-text">Recursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#la-justificación-de-la-violencia-en-chile" id="toc-la-justificación-de-la-violencia-en-chile" class="nav-link active" data-scroll-target="#la-justificación-de-la-violencia-en-chile"><strong>La justificación de la violencia en Chile</strong></a>
  <ul class="collapse">
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen"><strong>Resumen</strong></a></li>
  </ul></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><strong>2. Metodología</strong></a>
  <ul class="collapse">
  <li><a href="#datos-descripción-detallada-de-los-datos-a-utilizar" id="toc-datos-descripción-detallada-de-los-datos-a-utilizar" class="nav-link" data-scroll-target="#datos-descripción-detallada-de-los-datos-a-utilizar"><strong>2.1 Datos: descripción detallada de los datos a utilizar</strong></a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><strong>2.2 Variables</strong></a></li>
  <li><a href="#métodos" id="toc-métodos" class="nav-link" data-scroll-target="#métodos"><strong>2.3 Métodos</strong></a></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><strong>3. Análisis</strong></a>
  <ul class="collapse">
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo"><strong>3.1 Análisis descriptivo</strong></a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#análisis-estadístico-bivariado" id="toc-análisis-estadístico-bivariado" class="nav-link" data-scroll-target="#análisis-estadístico-bivariado"><strong>3.2 Análisis estadístico bivariado</strong></a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><strong>4. Conclusiones</strong></a></li>
  <li><a href="#referencias-bibliográficas" id="toc-referencias-bibliográficas" class="nav-link" data-scroll-target="#referencias-bibliográficas"><strong>Referencias bibliográficas</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo Estadistica</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="la-justificación-de-la-violencia-en-chile" class="level1">
<h1><strong>La justificación de la violencia en Chile</strong></h1>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen"><strong>Resumen</strong></h2>
<p>En este estudio se abordará el concepto de justificación de la violencia, siendo la violencia un fenómeno muy presente en la sociedad chilena, y su justificación un fenómeno muy complejo fundamental para entender las dinámicas que se dan en nuestro país. Haciendo un desglose en tres subconceptos: 1) justificación de violencia hacia la institución de Carabineros, 2) justificación de violencia de género, y 3) justificación de violencia hacia delincuentes; realizaremos un análisis en relación con las variables demográficas de ingresos, edad y nivel educacional, respectivamente. Para lograr nuestro cometido hicimos uso de la Encuesta Longitudinal de Social de Chile a cargo del Centro de Estudios del Conflicto y Cohesión Social (COES), de la que extrajimos variables tales como “Justificación de violencia de: “Estudiantes tiren piedras a Carabineros”, “Marido abofetee a su mujer”, “Perseguir y golpear a delincuentes” y “Amarrar a un poste a un delincuente”.</p>
<ol type="1">
<li>Introducción</li>
</ol>
<p>En la sociedad chilena, la violencia es un fenómeno social complejo que se manifiesta de distintas formas y en distintos contextos, desde las dinámicas de género hasta conflictos de la sociedad civil con el Estado. Conocer bajo qué parámetros y dinámicas se sustenta su justificación se vuelve relevante para comprender las dinámicas de conflicto y legitimación de tipos de violencia. Este estudio aborda las justificaciones, entendiendo que reflejan un aspecto fundamental en las percepciones arraigadas en la sociedad. Como afirma Alemany Briz (2000): “Los mecanismos que justifican la violencia a pequeña escala son los mismos que la justifican a gran escala.” (p.2). Comprender los niveles de la justificación de violencia en la población chilena nos ayuda a entender la inseparable relación que tiene con la violencia en general.</p>
<p>Como se afirmó, la violencia se puede expresar de distintas maneras. En esto juegan un rol importante los medios de comunicación, como indica Penalva (2002) “La dictadura del tiempo real lleva a una cobertura apresurada que dificulta obtener análisis profundos y verídicos.” (p.20). En términos de género, un estudio realizado en la región de la Araucanía analiza las dinámicas de violencia de género. El estudio revela que, en consonancia con investigaciones previas en la materia en Chile, las masculinidades hegemónicas están fuertemente relacionadas con la violencia de género (Arias et al., 2017). Además, los estudios confirman que la desigualdad de género incrementa el riesgo de la violencia sexual y femicidios. Según Espinoza &amp; Arias (2020), en Chile el 90% de las relaciones de pareja de adolescentes reportan violencia en alguna de sus formas; y esto es solamente en las relaciones adolescentes, es decir, tempranas, en la vida de los chilenos. En el ámbito institucional, se encuentra muy presente la violencia relativa a las instituciones, particularmente, a la ejercida y percibida por Carabineros: existe una relación fundamental entre las percepciones de injusticia en relación con la legitimidad institucional. En el contexto de protestas, cuando las personas sienten que son tratadas de manera injusta por parte de Carabineros, crece la deslegitimación de las instituciones (Figueiredo et al., 2023), y crece de igual forma, la justificación de la violencia ejercida contra Carabineros. Otra dimensión relevante en la justificación de la violencia ha sido la justicia vecinal. Según Delgado (2020), en Chile:</p>
<p>“ la justicia por mano propia se plantea como la idea de justificar perseguir y golpear a un individuo que acaba de cometer un delito, y en Chile esta actitud se ha justificado por sus ciudadanos como un tipo de violencia para establecer mayor control social” (p.12)</p>
<p>Así, la violencia vecinal se describe como un fenómeno en el cual los ciudadanos justifican la violencia debido a la percepción de inseguridad con el objetivo de restablecer el orden.</p>
<p>En la presente investigación, se buscará analizar la justificación de la violencia en Chile y las variaciones que presenta en relación a variables como, género, nivel educacional e ingreso. Tomando el concepto de “justificación de violencia” como la aceptación pública del uso de la fuerza, actos o estrategias violentas, lo cual está directamente ligado a la percepción de legitimidad que se tiene de las instituciones de justicia (Gerber, M. M., Figueiredo, A., Sáez, L., &amp; Orchard, M., 2023). En base a lo expuesto, el objetivo de este estudio es analizar las variables que, recodificadas, representen la justificación de la violencia 1) hacia la institución de Carabineros; 2) de género; 3) hacia los delincuentes; y relacionarlas con características sociodemográficas. Para la primera utilizaremos la variable “Estudiantes tiren piedras a Carabineros”, y analizaremos la relación que tiene con los ingresos de los encuestados; para la segunda utilizaremos la variable “Marido abofetee a su mujer”, y analizaremos la relación que tiene con la edad de los encuestados; y para la tercera utilizaremos las variables “Perseguir y golpear a delincuentes” y “Amarrar a un poste a un delincuente”, y analizaremos su relación con el nivel educacional de los encuestados. Planteamos tres hipótesis que guiarán el estudio:</p>
<ol type="i">
<li>Ha: Existe una relación negativa entre el nivel de ingresos percibido y la justificación de la violencia hacia carabineros desde los estudiantes. H0: No existe relación entre el nivel de ingresos percibido y la justificación de violencia hacia Carabineros desde los estudiantes.</li>
<li>Ha: Existe una relación significativa entre la edad del encuestado y la justificación de que el marido golpee a su mujer. H0: No existe relación entre la edad del encuestado y la justificación de que el marido golpee a su mujer.</li>
<li>Ha: Existe una relación negativa entre el nivel educacional alcanzado y la justificación de la violencia hacia delincuentes. H0: No existe una relación entre el nivel educacional alcanzado y la justificación de la violencia hacia los delincuentes.</li>
</ol>
</section>
</section>
<section id="metodología" class="level1">
<h1><strong>2. Metodología</strong></h1>
<section id="datos-descripción-detallada-de-los-datos-a-utilizar" class="level2">
<h2 class="anchored" data-anchor-id="datos-descripción-detallada-de-los-datos-a-utilizar"><strong>2.1 Datos: descripción detallada de los datos a utilizar</strong></h2>
<p>Los datos que se utilizarán para el presente informe son de carácter cuantitativo por medio de un cuestionario estructurado, correspondientes a la base de datos del Estudio Longitudinal Social de Chile “ELSOC”. La población objetivo de la encuesta son hombres y mujeres de 18 a 75 años, residentes habituales de viviendas particulares en zonas urbanas. La representatividad estimada del estudio es de, aproximadamente, un 77% de la población total del país y un 93% de la población urbana. Esta encuesta está a cargo del Centro de Estudios del Conflicto y Cohesión Social (COES). En particular, se utilizó la encuesta aplicada durante el año 2019 correspondiente a la ola 4. Además, se le añadieron a las variables sociodemográficas las variables del módulo de Conflicto Social, con el fin de obtener los datos correspondientes con el foco del tema central de la investigación.&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://dataverse.harvard.edu/api/access/datafile/7245118"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pacman)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, car, psych, sjmisc, sjPlot, sjlabelled, ggcorrplot, dplyr)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="variables" class="level2">
<h2 class="anchored" data-anchor-id="variables"><strong>2.2 Variables</strong></h2>
<p>El tipo de medición será tipo Likert y se miden en: “Nunca se justifica”, “Pocas veces se justifica”, “Algunas veces se justifica”, “Muchas veces se justifica” y “Siempre se justifica”, y se medirán las siguientes variables:</p>
<ul>
<li><p><strong>f05_01</strong> “Justificación de la violencia: Perseguir y golpear a delincuentes”: Actitud hacia el uso de violencia física como medio de castigo o justicia por mano propia contra personas consideradas delincuentes.&nbsp;</p></li>
<li><p><strong>f05_02</strong> “Justificación de la violencia: Amarrar a un poste a un delincuente”: Actitud hacia la humillación pública o el castigo físico extrajudicial contra un presunto delincuente.&nbsp;</p></li>
<li><p><strong>f05_05</strong> “Justificación de la violencia: Marido abofetee a su mujer”: Actitud hacia la violencia doméstica en forma de agresión física por parte del esposo hacia su pareja.</p></li>
<li><p><strong>f05_07</strong> “Justificación de la violencia: Estudiantes tiren piedras a carabineros”: Actitud hacia el uso de violencia física por parte de estudiantes contra las fuerzas policiales en el contexto de manifestaciones.&nbsp;</p></li>
</ul>
<p>Para los fines del trabajo se agruparon y recodificaron algunas variables siendo que “Justificación de la violencia: Perseguir y golpear a delincuentes” y “Justificación de la violencia: Amarrar a un poste a un delincuente” quedaron como “Violencia Criminalidad”, también “Justificación de la violencia: Marido abofetee a su mujer” quedó como “Violencia de género” y por último “Justificación de la violencia: Estudiantes tiren piedras a carabineros” quedó como “Violencia a carabineros”</p>
<p><strong>A esto se le suman las variables sociodemográficas de:</strong></p>
<ul>
<li><p>Nivel educacional : Se refiere al grado máximo de instrucción formal que una persona ha alcanzado, lo que puede ser indicativo de sus habilidades, conocimientos y oportunidades sociales. Su tipo de medición será <strong>categórico ordinal.</strong> Estas están ordenadas del 1 al 10 dependiendo el nivel educativo, estás son: 1. Sin estudios 2. Educación Básica o Preparatoria incompleta 3. Educación Básica o Preparatoria completa 4. Educación Media o Humanidades incompleta 5. Educación Media o Humanidades completa 6. Técnico Superior incompleta 7. Técnico Superior completa 8. Universitaria incompleta 9. Universitaria completa 10. Estudios de posgrado (magíster o doctorado)&nbsp;</p></li>
<li><p>Ingresos(Sueldo Líquido): Se refiere a la cantidad de dinero que una persona percibe al mes, ya sea a través de salarios, negocios, transferencias u otras fuentes. Su nivel de medición será <strong>categórico ordinal.</strong> Esto estará ordenado en 5 categorías menos de 500.000 se considera “muy bajo”, entre 500.000 y 700.000 “bajo” entre 700.000 y 1.200.000 “medio” entre 1.200.000 y 1.800.000 “alto” y desde 1.800.000 hacia arriba “muy alto”. Se tomó esta decisión debido a que en Chile, el ingreso mínimo mensual en 2024 ronda los 500.000 pesos chilenos, lo que hace que los ingresos inferiores a esta cifra se consideren como ingresos “muy bajo”</p></li>
</ul>
<p>Edad: Se refiere a la cantidad de años de la persona. Por los objetivos del trabajo, se recodificó en 4 grupos etarios. Su tipo de medición será <strong>categórico ordinal</strong>. La edad recodificada en grupos permite evaluar patrones de comportamiento o actitudes en diferentes etapas de la vida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar la ola</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ola_4 <span class="ot">&lt;-</span> elsoc_long_2016_2022<span class="fl">.2</span> <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ola <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar variables y limpiar valores problemáticos</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>variables_seleccionadas <span class="ot">&lt;-</span> ola_4 <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(m0_sexo, m0_edad, m01, m13, f05_01, f05_02, f05_05, f05_07) <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">replace</span>(., . <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">88</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">99</span>, <span class="dv">999999999</span>), <span class="cn">NA</span>))</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Renombrar las variables </span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>final <span class="ot">&lt;-</span> variables_seleccionadas <span class="sc">%&gt;%</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">sexo =</span> m0_sexo, <span class="at">edad =</span> m0_edad, <span class="at">niv_educativo =</span> m01, <span class="at">ingresos =</span> m13, <span class="at">viol_delinc =</span> f05_01, <span class="at">poste_delinc =</span> f05_02, <span class="at">marido_agrede_mujer =</span> f05_05, <span class="at">estudiantes_agreden_carab =</span> f05_07)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear nuevas variables de violencia</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>tipos_de_violencia <span class="ot">&lt;-</span> final <span class="sc">%&gt;%</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">violencia_criminalidad =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., viol_delinc, poste_delinc), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">violencia_a_carabineros =</span> estudiantes_agreden_carab,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">violencia_genero =</span> marido_agrede_mujer)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Eliminar filas con NA</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>final_final <span class="ot">&lt;-</span> tipos_de_violencia <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>()</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Recodificación de edad en grupos</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>final_final <span class="ot">&lt;-</span> final_final <span class="sc">%&gt;%</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">edad_recodificada =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    edad <span class="sc">&gt;=</span> <span class="dv">18</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">29</span> <span class="sc">~</span> <span class="st">"Jóvenes"</span>,  </span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    edad <span class="sc">&gt;=</span> <span class="dv">30</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">44</span> <span class="sc">~</span> <span class="st">"Adultos jóvenes"</span>,   </span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    edad <span class="sc">&gt;=</span> <span class="dv">45</span> <span class="sc">&amp;</span> edad <span class="sc">&lt;=</span> <span class="dv">59</span> <span class="sc">~</span> <span class="st">"Adultos"</span>,  </span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    edad <span class="sc">&gt;=</span> <span class="dv">60</span> <span class="sc">~</span> <span class="st">"Adultos mayores"</span>,  </span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span>  </span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a><span class="co">#Recodificación ingresos</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>final_final<span class="sc">$</span>ingreso_recodificado <span class="ot">&lt;-</span> <span class="fu">cut</span>(final_final<span class="sc">$</span>ingresos,</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">500000</span>, <span class="dv">700000</span>, <span class="dv">1200000</span>, <span class="dv">1800000</span>, <span class="cn">Inf</span>),</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Muy bajo"</span>, <span class="st">"Bajo"</span>, <span class="st">"Medio"</span>, <span class="st">"Alto"</span>, <span class="st">"Muy alto"</span>),</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">right =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#resumen descriptivo</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>desc_cuantitativas <span class="ot">&lt;-</span> final_final <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">describe</span>()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(desc_cuantitativas)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          vars    n      mean        sd median   trimmed
sexo                         1 2012      1.53      0.50      2      1.53
edad                         2 2012     45.13     13.00     45     45.04
niv_educativo                3 2012      5.60      2.18      5      5.60
ingresos                     4 2012 534804.81 580577.29 400000 447464.60
viol_delinc                  5 2012      2.61      1.31      3      2.51
poste_delinc                 6 2012      1.92      1.24      1      1.70
marido_agrede_mujer          7 2012      1.07      0.38      1      1.00
estudiantes_agreden_carab    8 2012      1.50      0.97      1      1.27
violencia_criminalidad       9 2012      2.26      1.14      2      2.13
violencia_a_carabineros     10 2012      1.50      0.97      1      1.27
violencia_genero            11 2012      1.07      0.38      1      1.00
                                mad min      max    range  skew kurtosis
sexo                           0.00   1        2        1 -0.11    -1.99
edad                          16.31  19       78       59  0.05    -0.90
niv_educativo                  2.97   1       10        9  0.18    -0.80
ingresos                  222390.00   0 15000000 15000000 10.25   207.44
viol_delinc                    1.48   1        5        4  0.27    -1.03
poste_delinc                   0.00   1        5        4  1.14     0.12
marido_agrede_mujer            0.00   1        5        4  7.02    54.88
estudiantes_agreden_carab      0.00   1        5        4  1.99     3.22
violencia_criminalidad         1.48   1        5        4  0.73    -0.29
violencia_a_carabineros        0.00   1        5        4  1.99     3.22
violencia_genero               0.00   1        5        4  7.02    54.88
                                se
sexo                          0.01
edad                          0.29
niv_educativo                 0.05
ingresos                  12943.33
viol_delinc                   0.03
poste_delinc                  0.03
marido_agrede_mujer           0.01
estudiantes_agreden_carab     0.02
violencia_criminalidad        0.03
violencia_a_carabineros       0.02
violencia_genero              0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tablas de frecuencia para variables categóricas</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>categoricas <span class="ot">&lt;-</span> final_final <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.factor)  </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>categoricas <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">map</span>(<span class="sc">~</span> <span class="fu">frq</span>(.))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$ingreso_recodificado
x &lt;categorical&gt; 
# total N=2012 valid N=2012 mean=1.72 sd=1.05

Value    |    N | Raw % | Valid % | Cum. %
------------------------------------------
Muy bajo | 1221 | 60.69 |   60.69 |  60.69
Bajo     |  342 | 17.00 |   17.00 |  77.68
Medio    |  296 | 14.71 |   14.71 |  92.40
Alto     |  100 |  4.97 |    4.97 |  97.37
Muy alto |   53 |  2.63 |    2.63 | 100.00
&lt;NA&gt;     |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>final_final<span class="sc">$</span>ingreso_ordinal <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(final_final<span class="sc">$</span>ingreso_recodificado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="métodos" class="level2">
<h2 class="anchored" data-anchor-id="métodos"><strong>2.3 Métodos</strong></h2>
<p>Para contrastar la hipótesis y calcular el tamaño de efecto se hará uso del coeficiente de Spearman para contrastar “Violencia a carabineros” con la variable “Ingresos”, también se utilizará el coeficiente de Kendall Tau para relacionar la “Violencia criminalidad” con el “Nivel educacional” y por último se utilizará el test de Chi-cuadrado para el contraste entre “Violencia de género” y la variable de “Edad”.</p>
<p><strong>Spearman - Violencia hacia Carabineros e Ingresos (Recodificada en Ordinal)</strong></p>
<p>Elegimos utilizar el coeficiente de correlación de Spearman por las características de las variables que decidimos analizar, es decir, dos variables ordinales que no necesariamente tienen una relación lineal, y Spearman nos ayuda al análisis de esta relación monótona, lo que detectara si a medida que el ingreso aumenta (o disminuye), la justificación también disminuye o aumenta de manera consistente, sin que esta relación sea estrictamente lineal. Además, con Spearman los valores sensibles que puede tener la variable de ingresos quedan fuera del análisis, ya que trabaja directamente con rangos y no con los valores originales.</p>
<p><strong>Chi cuadrado - Marido abofetea a su mujer y Edad (Recodificada en Ordinal)</strong></p>
<p>En este caso, utilizamos la prueba de Chi cuadrado para el análisis de las variables Edad y Marido abofetea a su mujer, esto porque el análisis que queremos hacer entre estas dos variables es netamente el de buscar una relación entre ellas, es decir, si existe una relación entre la edad y la justificación en la violencia de género. Al recodificar la variable de edad, esta quedó en 4 categorías, siendo estas: jóvenes, adultos jóvenes, adultos y adultos mayores. Por ello, las dos variables a analizar quedaron como variables categóricas, ya que, la violencia de género es de tipo likert y la prueba de Chi cuadrado era las más adecuada para el fin de buscar aquella relación.</p>
<p><strong>Kendall Tau - Violencia hacia la criminalidad y Nivel educativo (Recodificado en Ordinal)</strong></p>
<p>Se utilizará el coeficiente de Kendall Tau para relacionar “Violencia criminalidad” con “Nivel educacional” esto por que ambas variable son ordinales cosa que es necesaria para este tipo de correlación, también lo que queremos ver es si a mayor nivel educativo, hay una tendencia consistente a justificar menos la violencia criminalidad, esto se verá de mejor manera gracias a que este coeficiente mide la fuerza de esa relación (intensidad), lo que resulta útil para interpretar tendencias sociales.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Spearman </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar los niveles del factor</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(final_final<span class="sc">$</span>ingreso_recodificado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Muy bajo" "Bajo"     "Medio"    "Alto"     "Muy alto"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mapear manualmente los niveles a valores numéricos</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>final_final<span class="sc">$</span>ingreso_recodificado <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  final_final<span class="sc">$</span>ingreso_recodificado,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Muy bajo"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bajo"</span> <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Medio"</span> <span class="ot">=</span> <span class="dv">3</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Alto"</span> <span class="ot">=</span> <span class="dv">4</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Muy alto"</span> <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar que ahora es numérico</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(final_final<span class="sc">$</span>ingreso_recodificado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>spearman_data <span class="ot">&lt;-</span> final_final <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(violencia_a_carabineros, ingreso_recodificado) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar el test de Spearman</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>spearman_data <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  spearman_data<span class="sc">$</span>violencia_a_carabineros,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  spearman_data<span class="sc">$</span>ingreso_recodificado,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"spearman"</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(spearman_data$violencia_a_carabineros,
spearman_data$ingreso_recodificado, : Cannot compute exact p-value with ties</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los resultados</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(spearman_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  spearman_data$violencia_a_carabineros and spearman_data$ingreso_recodificado
S = 1320815450, p-value = 0.2259
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.02700733 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Kendall tau violencia y nivel educativo</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>kendall_data <span class="ot">&lt;-</span> final_final <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(violencia_criminalidad, niv_educativo) </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar el test de correlación de Kendall Tau</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>kendall_tau_result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  kendall_data<span class="sc">$</span>violencia_criminalidad,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  kendall_data<span class="sc">$</span>niv_educativo,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"kendall"</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(kendall_tau_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kendall's rank correlation tau

data:  kendall_data$violencia_criminalidad and kendall_data$niv_educativo
z = 0.84761, p-value = 0.3967
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.0145568 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi cuadrado marido abofetea a su mujer y edad</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>tabla_chi <span class="ot">&lt;-</span> <span class="fu">table</span>(final_final<span class="sc">$</span>marido_agrede_mujer, final_final<span class="sc">$</span>edad_recodificada)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>chi_cuadrado_result <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tabla_chi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tabla_chi): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi cuadrado violencia criminalidad y nivel educativo</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>grafico_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tabla_chi)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(grafico_data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"violencia_criminalidad"</span>, <span class="st">"niv_educativo"</span>, <span class="st">"Frecuencia"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los resultados</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(chi_cuadrado_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tabla_chi
X-squared = 9.4289, df = 12, p-value = 0.6659</code></pre>
</div>
</div>
</section>
</section>
<section id="análisis" class="level1">
<h1><strong>3. Análisis</strong></h1>
<section id="análisis-descriptivo" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo"><strong>3.1 Análisis descriptivo</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama justificación violencia hacia carabineros</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> final_final, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> estudiantes_agreden_carab)) <span class="sc">+</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2000</span>)) <span class="sc">+</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Justificar que estudiantes tiren piedras a Carabineros"</span>, </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Justifica la agresion de estudiantes"</span>, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo_final_estadistica_files/figure-html/Gráfico-violencia-a-carabineros-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el gráfico que se muestra arriba, se puede observar la variable: “justificar que estudiantes tiren piedras a carabineros”, donde se puede ver como la gran mayoría de las personas no justifica este tipo de violencia, encontrándose la mayor parte de las respuestas en el valor 1, que significa que nunca lo justifica, y así baja paulatinamente hasta justificarlo siempre, que se encuentra con la menor frecuencia de respuestas, como se puede ver en el gráfico.&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico Justificación violencia hacia delincuentes</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> final_final, </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> violencia_criminalidad)) <span class="sc">+</span> </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"green"</span>) <span class="sc">+</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">600</span>)) <span class="sc">+</span> </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Justificar violencia hacia delincuentes"</span>, </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Violencia hacia delincuentes"</span>, </span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo_final_estadistica_files/figure-html/Gráfico-violencia-hacia-delincuentes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En el gráfico presentado se puede observar que hay una distribución más balanceada entre la frecuencia de las variables, considerando perseguir a los delincuentes y agredirlos y amarrarlos a un poste, lo que da un resultado a tener en consideración al ser el gráfico más equilibrado entre los mostrados. Con una media de 2.25936 la variable indica que hay una percepción que, aunque los encuestados no se sitúen en su mayoría en que se justifique la práctica, si son niveles más alto en comparación con los niveles de justificación de la violencia en los otros aspectos ilustrados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diagrama justificación violencia domestica</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> final_final, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> marido_agrede_mujer)) <span class="sc">+</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2000</span>)) <span class="sc">+</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Justificación de violencia domestica"</span>, </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Violencia de género"</span>, </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Elaboración propia"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Trabajo_final_estadistica_files/figure-html/Gráfico-violencia-de-género-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>En este gráfico podemos observar la variable de “Violencia de género”, donde existe una tendencia más que marcada hacia la respuesta de “nunca lo justifica”, lo que quiere decir que no hay (o hay muy pocas) respuestas que se alejen de dicha respuesta, lo que a su vez indica que a medida que se aleja de la opción 1 “no justifica nunca” la frecuencia va bajando hasta hacerse casi o prácticamente nula.&nbsp;</p>
</section>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section"></h2>
</section>
<section id="análisis-estadístico-bivariado" class="level2">
<h2 class="anchored" data-anchor-id="análisis-estadístico-bivariado"><strong>3.2 Análisis estadístico bivariado</strong></h2>
<p><strong>CORRELACIÓN DE SPEARMAN</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Spearman </span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar los niveles del factor</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(final_final<span class="sc">$</span>ingreso_recodificado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mapear manualmente los niveles a valores numéricos</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>final_final<span class="sc">$</span>ingreso_recodificado <span class="ot">&lt;-</span> <span class="fu">recode_factor</span>(</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  final_final<span class="sc">$</span>ingreso_recodificado,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Muy bajo"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Bajo"</span> <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Medio"</span> <span class="ot">=</span> <span class="dv">3</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Alto"</span> <span class="ot">=</span> <span class="dv">4</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Muy alto"</span> <span class="ot">=</span> <span class="dv">5</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in recode.numeric(.x, !!!values, .default = .default, .missing =
.missing): NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar que ahora es numérico</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(final_final<span class="sc">$</span>ingreso_recodificado)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>spearman_data <span class="ot">&lt;-</span> final_final <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(violencia_a_carabineros, ingreso_recodificado) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar el test de Spearman</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>spearman_data <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  spearman_data<span class="sc">$</span>violencia_a_carabineros,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  spearman_data<span class="sc">$</span>ingreso_recodificado,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"spearman"</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(spearman_data$violencia_a_carabineros,
spearman_data$ingreso_recodificado, : Cannot compute exact p-value with ties</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los resultados</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(spearman_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  spearman_data$violencia_a_carabineros and spearman_data$ingreso_recodificado
S = 1320815450, p-value = 0.2259
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.02700733 </code></pre>
</div>
</div>
<p>Según el valor del coeficiente de Spearman (0,027), podemos deducir que, al ser un valor muy cercano a 0, la correlación entre las dos variables es casi nula. La relación entre los ingresos de los encuestados y la justificación de violencia hacia Carabineros es muy ligeramente positiva, es decir, a mayor nivel de ingreso mayor justificación de la violencia; pero esta ni siquiera es estadísticamente significativa. Además, con un valor p obtenido de (0,2259), muy por encima de 0,05, se concluye que no hay evidencia significativa para rechazar la hipótesis nula de que no existe relación entre ambas variables. Por otro lado, el valor de la estadística de prueba de Spearman (S = 1321), muy alejado de 0, refleja que las diferencias entre los rangos de las dos variables es muy alta, o sea, que no existe una relación monotónica significativa entre las dos variables.</p>
<p><strong>ANÁLISIS DE CHI-CUADRADO</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi cuadrado marido abofetea a su mujer y edad</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>tabla_chi <span class="ot">&lt;-</span> <span class="fu">table</span>(final_final<span class="sc">$</span>marido_agrede_mujer, final_final<span class="sc">$</span>edad_recodificada)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>chi_cuadrado_result <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tabla_chi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tabla_chi): Chi-squared approximation may be incorrect</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Chi cuadrado violencia criminalidad y nivel educativo</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>grafico_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tabla_chi)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(grafico_data) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"violencia_criminalidad"</span>, <span class="st">"niv_educativo"</span>, <span class="st">"Frecuencia"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los resultados</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(chi_cuadrado_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tabla_chi
X-squared = 9.4289, df = 12, p-value = 0.6659</code></pre>
</div>
</div>
<p>Dado que el valor p obtenido de la prueba Chi-cuadrado es mucho mayor a 0,05, ya que fue de 0,6659, no es posible rechazar la hipótesis nula. Es decir, no hay evidencia estadísticamente significativa para afirmar que existe una asociación entre la edad y la justificación de que el marido abofetee a su mujer, y se podría decir que ambas variables son independientes en esta muestra. Además, los grados de libertad obtenidos en la prueba fueron 12, lo que indica que las variables analizadas tienen múltiples categorías (4 grupos para la edad y 5 niveles en la actitud hacia la violencia), esto implica que el análisis tiene que considerar una tabla de contingencia con un número bastante grande de combinaciones entre categorías. Con este valor de grados de libertad, se requiere un valor de Chi-cuadrado muchísimo más alto para obtener una diferencia significativa, esto dado a que el valor crítico es de aproximadamente 21,920; lo que refuerza la conclusión de que no se encontró una relación significativa entre las variables en este caso.</p>
<p><strong>CORRELACIÓN DE KENDALL TAU</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(kendall_tau_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kendall's rank correlation tau

data:  kendall_data$violencia_criminalidad and kendall_data$niv_educativo
z = 0.84761, p-value = 0.3967
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.0145568 </code></pre>
</div>
</div>
<p>El resultado de la correlación de Kendall Tau entre las variables de violencia hacia delincuentes con la variable de nivel educativo es de 0.0145568, El valor obtenido indica una correlación muy baja entre las dos variables. El valor es cercano a cero, por lo que sugiere que no existe una relación significativa entre el nivel educativo de las personas y la justificación de estos en la violencia hacia los delincuentes (incluyendo perseguirlos, golpearlos y amarrar a un poste). Esta consideración refuerza la hipótesis nula, que sostiene que no hay relación significativa entre el nivel educacional y la justificación de la violencia hacia los delincuentes. Es posible que el enfoque específico de los datos presentados presente complicaciones y justifique el resultado dado. Es por esto, que otras interpretaciones en base a otra codificación de la variable de nivel educativo podrían indicar correlaciones distintas.</p>
</section>
</section>
<section id="conclusiones" class="level1">
<h1><strong>4. Conclusiones</strong></h1>
<p>El trabajo realizado en torno al análisis estadístico de la justificación de la violencia en Chile da cuenta de resultados significativos; con esto, también hay que tener en cuenta consideraciones del estudio, la base de datos, y los resultados presentados. En primer lugar, la correlación de Spearman entre la violencia hacia Carabineros y los ingresos —.&nbsp;</p>
<p>El análisis de la relación entre el nivel educativo con la justificación de la violencia hacia los delincuentes mostró una correlación baja. De este modo, se encontró que no existe una tendencia clara entre el nivel educativo y la justificación de la violencia hacia los delincuentes, contrariamente a lo que se podría esperar, y que fue la hipótesis planteada, de que el nivel educativo influye en la justificación de efectuar actos violentos en contra de delincuentes. El resultado plantea la necesidad de reconsiderar las variables consideradas y explorar más factores asociados a la justificación de la violencia hacia delincuentes.</p>
<p>Finalmente, el análisis de Chi-cuadrado entre la edad y la justificación de la violencia de género no arrojó resultados estadísticamente significativos (valor p = 0.6659), lo que da a entender que no existe una relación fuerte entre ambas variables. En primera instancia, se consideró la variable edad como un factor que podría ser significativo para comprender un aspecto de la relación en la justificación con la violencia de género; sin embargo, la edad no parece ser un factor determinante en la justificación de la práctica mencionada.&nbsp;</p>
<p>Es posible que la codificación de las variables haya afectado el resultado de los estudios porque al elegir variables siempre corremos el riesgo de realizar el estudio bajo sesgos que nos impiden observar el panorama completo de la investigación que pretendemos realizar, a esto debemos sumarle que la base de datos – la encuesta – con la que realizamos este estudio, se realizó en el año 2019, al comprender esto y saber todos los sucesos que han impactado en las percepciones de los chilenos desde entonces puede haber cambiado ciertos aspectos de esta, por lo que hay podemos encontrar otra limitación.</p>
</section>
<section id="referencias-bibliográficas" class="level1">
<h1><strong>Referencias bibliográficas</strong></h1>
<p>Alemany Briz, J. (2000). Mecanismos de justificación de la violencia y cultura de paz. Revista de Fomento Social, (55), 419.433. <a href="https://doi.org/10.32418/rfs.2000.219.2488" class="uri">https://doi.org/10.32418/rfs.2000.219.2488</a></p>
<p>Arias, L., Peña, J. &amp; Sáez, F. (2017). Masculinidad, Socialización y Justificación de la Violencia de Género. El Caso de la Región de la Araucanía (Chile). Masculinities and Social Change, 6(2), 142-165. <a href="https://doi.org/10.17583/mcs.2017.2235" class="uri">https://doi.org/10.17583/mcs.2017.2235</a></p>
<p>Delgado, J. (2020). Delincuencia y justificación de la violencia: Justicia por mano propia en Chile [Tesis de maestría, Universidad de Chile]. Repositorio Institucional. https://repositorio.uchile.cl/bitstream/handle/2250/179393/Tesis%20-%20Jorge%20Delgado.pdf?sequence=1</p>
<p>Espinoza, S., &amp; Arias, A. (2020). Violencia de pareja en estudiantes secundarios de Osorno (Chile). Revista de Ciencias Humanas y Sociales, (93), 300–314. <a href="https://dialnet.unirioja.es/servlet/articulo?codigo=7621434" class="uri">https://dialnet.unirioja.es/servlet/articulo?codigo=7621434</a></p>
<p>Gerber, M., Figueiredo, A., Sáez, L. &amp; Orchard, M. (2023). Legitimidad, Justicia y Justificación de la Violencia Intergrupal entre Carabineros y Manifestantes en Chile. Psykhe (Santiago), 32(1), 1-15. <a href="https://dx.doi.org/10.7764/psykhe.2021.31721" class="uri">https://dx.doi.org/10.7764/psykhe.2021.31721</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/correlacional\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by <a href="https://www.jc-castillo.com">Juan Castillo</a> <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/cursos-metodos-facso/correlacional">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>