<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Milen Alarcón">
<meta name="author" content="Carla Canales">
<meta name="author" content="Constanza Jiménez">
<meta name="author" content="Camila Navarro">
<meta name="author" content="Belén Padilla">
<meta name="author" content="Martina Robledo">

<title>Trabajo final: Análisis sobre las percepciones de desigualdad en Chile</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Trabajo_final_estadistica_g10_quarto_files/libs/clipboard/clipboard.min.js"></script>
<script src="Trabajo_final_estadistica_g10_quarto_files/libs/quarto-html/quarto.js"></script>
<script src="Trabajo_final_estadistica_g10_quarto_files/libs/quarto-html/popper.min.js"></script>
<script src="Trabajo_final_estadistica_g10_quarto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Trabajo_final_estadistica_g10_quarto_files/libs/quarto-html/anchor.min.js"></script>
<link href="Trabajo_final_estadistica_g10_quarto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Trabajo_final_estadistica_g10_quarto_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Trabajo_final_estadistica_g10_quarto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Trabajo_final_estadistica_g10_quarto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Trabajo_final_estadistica_g10_quarto_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="Trabajo_final_estadistica_g10_quarto_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="Trabajo_final_estadistica_g10_quarto_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="Trabajo_final_estadistica_g10_quarto_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="Trabajo_final_estadistica_g10_quarto_files/libs/tabwid-1.1.3/tabwid.js"></script>

<style>
  body {
    background-color: #fff5f8; /* Un rosado suave */
  }
</style>


<link rel="stylesheet" href="C://Users//camil//OneDrive//Escritorio//r//estilos.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul class="collapse">
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">1</span> Introducción</a></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">2</span> Metodología</a>
  <ul class="collapse">
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos"><span class="header-section-number">2.1</span> Datos</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">2.2</span> Variables</a></li>
  <li><a href="#métodos" id="toc-métodos" class="nav-link" data-scroll-target="#métodos"><span class="header-section-number">2.3</span> Métodos</a></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis"><span class="header-section-number">3</span> Análisis</a>
  <ul class="collapse">
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo"><span class="header-section-number">3.1</span> Análisis descriptivo</a></li>
  <li><a href="#análisis-estadístico-bivariado" id="toc-análisis-estadístico-bivariado" class="nav-link" data-scroll-target="#análisis-estadístico-bivariado"><span class="header-section-number">3.2</span> Análisis estadístico bivariado</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Trabajo final: Análisis sobre las percepciones de desigualdad en Chile</h1>
<p class="subtitle lead">Estadística Correlacional 2024, Carrera de Sociología - Universidad de Chile</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores/as</div>
    <div class="quarto-title-meta-contents">
             <p>Milen Alarcón </p>
             <p>Carla Canales </p>
             <p>Constanza Jiménez </p>
             <p>Camila Navarro </p>
             <p>Belén Padilla </p>
             <p>Martina Robledo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">1 de diciembre de 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Resumen</div>
    <p>En la presente investigación se busca explorar la percepción de desigualdad en Chile considerando los niveles de ingreso, poder y la autopercepción de clase social, analizándolo además con una perspectiva de género. En base a esto se proponen tres hipótesis, las cuales son: “Las mujeres perciben que están en una clase social distinta a los hombres”, siendo esta la hipótesis principal, “Las mujeres perciben distinta desigualdad de ingreso que los hombres” y “Las mujeres perciben distinta desigualdad de poder que los hombres”. Para buscar la evidencia que permita dar a conocer lo planteado en estas hipótesis, se analizaron los datos de la encuesta PNUD-DES 2016, la cual cuenta con una muestra representativa de 2.613 casos de hombres y mujeres mayores de 18 años en distintas regiones del país.</p>
    <p>Para esto se utilizaron distintas técnicas de estadística y análisis descriptivos y bivariados, que dieron como resultado hallazgos que indican que no hay suficiente evidencia para afirmar que existen diferencias significativas entre hombres y mujeres sobre la percepción de desigualdad de ingresos y poder, al igual que las mujeres se perciban en clases sociales más bajas que el género contrario, lo que podría significar, que ambos géneros tienen percepciones similares en cuanto a la desigualdad de ingresos y poder. Sin embargo, sí existen hallazgos significativos sobre la primera hipótesis, pudiendo comprobarse que las mujeres tienden a ubicarse en una clase social diferentes a la de los hombres, lo que se puede entender como un reflejo del contraste entre géneros y su autopercepción de clase social.</p>
  </div>
</div>


</header>


<section id="introducción" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducción</h1>
<p>Durante el año 2016, el paradigma político social se vió caracterizado por un marcado debate en torno a la desigualdad, un tópico que ha sido constantemente centro de la discusión a nivel continental. Particularmente, abocandonos al caso chileno, la desigualdad hasta el día de hoy continúa siendo uno de los desafíos más importantes para asegurar la cohesión social y el desarrollo de una sociedad sostenible. Por su parte, el principal aspecto que releva el ámbito de la desigualdad como tema a tratar en la presente investigación es que “Chile es el segundo país más desigual de la OCDE (índice de Gini antes y después de impuestos y transferencias.” (Mieres, 2020, p.92). Por lo tanto, decir que Chile es desigual es una obviedad, ya que esto ha sido parte de su fisonomía histórica.&nbsp;</p>
<p>En este contexto, analizar las percepciones de desigualdad resulta crucial, para comprender cómo esta realidad estructural afecta la manera en que las personas perciben la desigualdad en ingresos y poder. Los principales antecedentes e investigaciones anteriores en Chile, no responden a un análisis de género en las percepciones de desigualdad entre hombres y mujeres, sin embargo, desde un marco general los hallazgos “(…) señalan que la percepción de desigualdad posee variaciones relevantes en la población, las que serían afectadas por una serie de determinantes contextuales e individuales.” (Castillo, et al.&nbsp;2012, p.100)&nbsp; Lo cual también se ve reflejado en estudios que presentan hipotesis que señalan que “… se percibirá una sociedad más igualitaria, cuanto más alta es la autoubicación de las personas en la estructura social”&nbsp; (Evans et al.,1992, p.&nbsp;468, citado por Rodriguez, 2014, p.98)</p>
<p>Desde la presente investigación se analizará la percepción de desigualdad, la cual se entiende como la forma en que los individuos interpretan y valoran disparidades sociales, económicas y políticas dentro de la sociedad. A su vez, la desigualdad como concepto se fragmenta, en especificidades cubriendo dimensiones sujetas a diferentes contextos, como lo son los ingresos y el poder. Según la conceptualización derivada de Fraser (2008) la desigualdad de poder se refiere a la distribución desigual de la capacidad de controlar, influir o acceder a recursos que afectan a otros. Por otro lado, la desigualdad de ingresos según el PNUD (2017) refiere a la disparidad en la distribución de los ingresos entre los diferentes miembros de una sociedad.</p>
<p>Estos conceptos resultan claves porque no solo reflejan las dinámicas multifacéticas que configuran las desigualdades, sino también la manera en que estas son percibidas e influidas por factores como el género y la clase social autopercibida, elementos que condicionan la interacción de los individuos con su entorno social.</p>
<p>La investigación tiene como objetivo principal analizar las percepciones de desigualdad de poder e ingresos en Chile, específicamente en relación con el género y la clase social autopercibida. Este análisis se desarrollará bajo tres hipótesis: En primer lugar, las mujeres perciben que están en una clase social distinta a la de los hombres; En segundo lugar, las mujeres perciben distinta desigualdad de ingresos que los hombres; Y por último las mujeres perciben distinta desigualdad de poder que los hombres.</p>
</section>
<section id="metodología" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Metodología</h1>
<section id="datos" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="datos"><span class="header-section-number">2.1</span> Datos</h2>
<p>La base de datos a utilizar corresponde al PNUD-DES, resultado de la aplicación de la Encuesta Desigualdades Económicas y Sociales (PNUD-DES) 2016, esta fue desarrollada en el marco de un estudio interdisciplinario enfocado en estudiar desigualdades socioeconómicas en Chile como iniciativa del PNUD entre los años 2016 y 2017. La encuesta realizada en el 2016, contó con un universo de mujeres y hombres de 18 años o más, estos pertenecientes a diversos niveles socioeconómicos y habitaban tanto zonas urbanas como rurales de las 15 regiones del país, excluyendo zonas de difícil acceso. El tamaño de la muestra alcanzado fue de 2.613 casos.</p>
<p>La base de datos que contiene sólo las variables por mencionar a continuación, lleva por nombre DES_2016_REC. La elección de estas variables responde al objetivo inicial de poder demostrar cuantitativamente, o no, que en su generalidad, las mujeres de Chile se perciben a sí mismas distintas en relación a la clase social y además, perciben una desigualdad de ingresos y poder distinta respecto al sexo masculino. Las hipótesis responden a la misma fórmula:</p>
<p>Hₐ : X̄clase social₁ - X̄clase social₂ ≠ 0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Hₐ : X̄p.&nbsp;desigualdad₂ - X̄p.&nbsp;desigualdad₁ ≠ 0</p>
<p>H₀ : X̄clase social₁ - X̄clase social₂ = 0 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; H₀ : X̄p.&nbsp;desigualdad₂ - X̄p.&nbsp;desigualdad₁ = 0</p>
<p>Hₐ : X̄i. desigualdad₂ - X̄i. desigualdad₁ ≠ 0</p>
<p>H₀ : X̄i. desigualdad ₁ - X̄i. desigualdad₂ = 0</p>
</section>
<section id="variables" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="variables"><span class="header-section-number">2.2</span> Variables</h2>
<p>La variable sexo, busca registrar el sexo de las personas que respondieron la encuesta. Esta se presentaba en la encuesta como P7- Sexo del/la entrevistado/a y contaba con los valores 1) Hombre y 2) Mujer. Por lo tanto, la variable sexo corresponde a una de caracter dicotómica y nominal. Por otro lado, sexo se recodifico con la intencion de que quedara con los valores 0 y 1, los necesarios para el cálculo de punto biserial. Esta variable lleva el nombre de sexo_rec.</p>
<p>La variable p9_2, responde a la pregunta P9B- ¿Cuán desigual cree que es Chile? Ingresos. Esta pregunta busca medir cómo los entrevistados opinan respecto a que tan igualitaria es la distribución de ingresos en Chile, lo que puede traducirse de alguna manera, en que tan igualitaria es la sociedad chilena en lo que económicamente respecta. Para esto, se le presenta al/la entrevistado/a una escala de valores que va del 1 al 10, donde 1 es Muy igual y 10 es Muy desigual. Respecto a esto último, la variable p9_2, corresponde a una de carácter continua y ordinal. Esta variable fue recodificada, lo que significó un cambio en el orden, donde 1 corresponde a Muy desigual y 10 Muy igual. Esta decisión metodológica respondió a la necesidad de que las categorías y el valor otorgado vayan de menos a más según corresponda. Luego de estas transformaciones, la variable pasó a llamarse per_des_ing.</p>
<p>La variable p9_3, responde a la pregunta P9D- ¿Cuán desigual cree que es Chile? Poder. Esta pregunta busca medir cómo los entrevistados opinan respecto a que tan igualitaria es la distribución de poder en Chile. Para esto, se le presenta al/la entrevistado/a una escala de valores que va del 1 al 10, donde 1 es Muy igual y 10 es Muy desigual. Respecto a esto último, la variable p9_3, al igual que la variable anterior corresponde a una de carácter continua y ordinal que fue recodificada. El nuevo orden significó que 1 corresponda a Muy desigual y 10 a Muy igual, esta decisión metodológica respondió nuevamente a la necesidad de que las categorías y el valor otorgado vayan de menos a más según corresponda. Luego de estas transformaciones, la variable pasó a llamarse per_des_p.</p>
<p>Finalmente, la variable p_ 14, corresponde a la pregunta P14- ¿En qué clase social ubicaría a la gente como usted?, la que busca conocer la autoidentificación de cada entrevistada/o respecto a su clase social. Para esto, se le presenta al entrevistado una serie de respuestas, 1) Clase alta, 2) Clase media alta, 3) Clase media, 4) Clase media baja, 5) Clase baja. Finalmente, la última variable utilizada corresponde a una categórica y ordinal, puesto que se ordena en jerarquías. Esta variable cambió de sentido respondiendo a la necesidad de que la categoría y el valor otorgado vayan de menos a más según corresponda, transformando 1) Clase baja, 2) Clase media baja, 3) Clase media, 4) Clase media alta y 5) Clase alta. Luego de esta transformación, la variable pasó a llamarse autoper_c_soc.</p>
<p>Respecto a los valores perdidos, se identifican textualmente en el Manual metodológico y de uso, estos corresponden a los valores 8, 9, 88 y 99, entre otros, estos se recodificaron a NA y prontamente, todos fueron eliminados.</p>
</section>
<section id="métodos" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="métodos"><span class="header-section-number">2.3</span> Métodos</h2>
<p>Finalmente, se utilizó principalmente para la hipótesis #1 la tabla de contingencia, el cálculo de Chi cuadrado, el cálculo de Phi y test de proporciones, esto debido a que las variables son de carácter categóricas. Por otro lado, para el cálculo de las hipótesis #2 y #3 se recodifico la variable sexo a 0 y 1 para hombre y mujer respectivamente con el objetivo de hacer posible la correlacion de punto biserial. Esta variable, pasó a llamarse sexo_rec, además, se utilizó la prueba hipotesis t y el test de proporciones para llevar a cabo el estudio de las hipótesis.</p>
</section>
</section>
<section id="análisis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análisis</h1>
<section id="análisis-descriptivo" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="análisis-descriptivo"><span class="header-section-number">3.1</span> Análisis descriptivo</h2>
<p>En la siguiente tabla se exponen los principales estadísticos descriptivos de cada variable</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(summary_table, <span class="at">caption =</span> <span class="st">"Resumen descriptivo de todas las variables"</span>) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumen descriptivo de todas las variables</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">sexo</th>
<th style="text-align: left;">per_des_ing</th>
<th style="text-align: left;">per_des_p</th>
<th style="text-align: left;">autoper_c_soc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Min. :1.000</td>
<td style="text-align: left;">Min. : 1.000</td>
<td style="text-align: left;">Min. : 1.000</td>
<td style="text-align: left;">Min. :1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">1st Qu.:1.000</td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.: 1.000</td>
<td style="text-align: left;">1st Qu.:2.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Median :2.000</td>
<td style="text-align: left;">Median : 2.000</td>
<td style="text-align: left;">Median : 2.000</td>
<td style="text-align: left;">Median :3.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Mean :1.614</td>
<td style="text-align: left;">Mean : 2.477</td>
<td style="text-align: left;">Mean : 2.714</td>
<td style="text-align: left;">Mean :2.546</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3rd Qu.:2.000</td>
<td style="text-align: left;">3rd Qu.: 3.000</td>
<td style="text-align: left;">3rd Qu.: 4.000</td>
<td style="text-align: left;">3rd Qu.:3.000</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Max. :2.000</td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :10.000</td>
<td style="text-align: left;">Max. :5.000</td>
</tr>
</tbody>
</table>
<p>Resumen descriptivo de todas las variables</p>
</div>
</div>
<p>Se muestra que la medida de tendencia central de la variable “sexo” es <em>1.614</em>, esto indica que el promedio de la muestra tiene una ligera mayoría de mujeres, ya que el valor número 2 representa a las mujeres. Y la mediana es 2, lo que confirma que más del 50% de los encuestados son mujeres, reafirmando una tendencia clara en la composición de la muestra.</p>
<p>En la variable “percepción de desigualdad de ingresos” la media es <em>2.477</em>, esto indica que los encuestados tienden a percibir una alta desigualdad en los ingresos. La mediana es 2, demostrando que la mayoría de las respuestas se aglomera en los niveles más bajos de la escala, lo que refuerza la percepción significativa de una desigualdad de ingresos.</p>
<p>La media para la variable “percepción de desigualdad de poder” es <em>2.714</em>, es ligeramente superior a la “percepción de desigualdad de ingresos”, pero aún se encuentra dentro del rango de valores bajos. Esto da a entender que los encuestados perciben una desigualdad de poder demostrativa. La mediana es 2, lo que significa que más del 50% de los encuestados consideran que la desigualdad de poder es alta.</p>
<p>En la variable de “autopercepción de clase social” la media es <em>2.546</em>, esto indica que los encuestados tienden a ubicarse en promedio en una clase social media-baja. La mediana es 3, esto quiere decir que más de la mitad de los encuestados se consideran en la clase media. Esto evidencia cierta diversificación en las respuestas, aunque tiene una inclinación hacía las categorías más bajas de la escala.</p>
<p><strong>Desviación estándar para todas las variables numéricas</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Resumen descriptivo de todas las variables
</caption>
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
per_des_ing
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
per_des_p
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
autoper_c_soc
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
Min. :1.000
</td>
<td style="text-align:center;">
Min. : 1.000
</td>
<td style="text-align:center;">
Min. : 1.000
</td>
<td style="text-align:center;">
Min. :1.000
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
1st Qu.:1.000
</td>
<td style="text-align:center;">
1st Qu.: 1.000
</td>
<td style="text-align:center;">
1st Qu.: 1.000
</td>
<td style="text-align:center;">
1st Qu.:2.000
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
Median :2.000
</td>
<td style="text-align:center;">
Median : 2.000
</td>
<td style="text-align:center;">
Median : 2.000
</td>
<td style="text-align:center;">
Median :3.000
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
Mean :1.614
</td>
<td style="text-align:center;">
Mean : 2.477
</td>
<td style="text-align:center;">
Mean : 2.714
</td>
<td style="text-align:center;">
Mean :2.546
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
3rd Qu.:2.000
</td>
<td style="text-align:center;">
3rd Qu.: 3.000
</td>
<td style="text-align:center;">
3rd Qu.: 4.000
</td>
<td style="text-align:center;">
3rd Qu.:3.000
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
Max. :2.000
</td>
<td style="text-align:center;">
Max. :10.000
</td>
<td style="text-align:center;">
Max. :10.000
</td>
<td style="text-align:center;">
Max. :5.000
</td>
</tr>
</tbody>
</table>
</div>
<p>Desviación estándar para todas las variables numéricas</p>
</div>
</div>
<p>El valor de <em>0.487</em> en la desviación estándar sugiere que la distribución entre géneros es bastante equilibrada, con un poco más de mujeres que hombres. En el caso de la media de la percepción de desigualdad de ingresos está en <em>1.86</em>, lo cual indica que, en promedio, la percepción es baja. Esto sugiere que los encuestados no perciben una alta desigualdad en los ingresos. En la percepción de desigualdad de poder, se puede observar que ocurre algo parecido, ya que la media es baja (<em>1.94</em>), por lo que perciben una menor desigualdad de poder. Y en la autopercepción de clase el valor obtenido es de <em>1.06</em>, demostrando que los encuestados se perciben en una clase social muy baja.</p>
<p><strong>Tablas de frecuencia por variable</strong></p>
<ol type="1">
<li><strong>Sexo</strong></li>
</ol>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>ver código</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear la tabla de frecuencias</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>tabla_sexo <span class="ot">&lt;-</span> <span class="fu">table</span>(DES_2016_REC<span class="sc">$</span>sexo) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span> <span class="co"># Convertir a data frame para mayor flexibilidad</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Sexo =</span> Var1, <span class="at">Frecuencia =</span> Freq) <span class="sc">%&gt;%</span> <span class="co"># Renombrar columnas</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"Distribución de la variable Sexo"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">"c"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">format =</span> <span class="st">"html"</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="st">"center"</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width =</span> <span class="st">"100%"</span>, <span class="at">height =</span> <span class="st">"300px"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la tabla</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>tabla_sexo</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Distribución de la variable Sexo
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
999
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1590
</td>
</tr>
</tbody>
</table>
</div>
<p>Distribución de la variable Sexo</p>
</div>
</div>
<p>Se puede apreciar una distribución desigual entre la muestra de mujeres que corresponde a <em>1590</em> observaciones en comparación de los hombres que hay <em>999</em> observaciones.</p>
<ol start="2" type="1">
<li><strong>Percepción de desigualdad en ingresos</strong></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Distribución de la variable Percepción de Desigualdad de Ingresos
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Percepción_Desigualdad
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1228
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
318
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
408
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
256
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
153
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
136
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
43
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
21
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
9
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
17
</td>
</tr>
</tbody>
</table>
</div>
<p>Distribución de la variable Percepción de Desigualdad de Ingresos</p>
</div>
</div>
<p>La escala de las respuestas va de 1 (Muy Desigual) a 10 (Muy Igual). Se puede observar que la mayor cantidad de respuestas se concentran en los valores más bajos de la escala y conforme aumentan los valores hacia 10, las frecuencias disminuyen, teniendo <em>17</em> respuestas en el valor más alto. Esto da a entender que la mayoría de los encuestados perciben gran desigualdad en los ingresos, ya que las respuestas tienen una tendencia a los valores más bajos de la escala.</p>
<ol start="3" type="1">
<li><strong>Percepción de desigualdad de poder</strong></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Distribución de la variable Percepción de Desigualdad de Poder
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Percepción_Desigualdad_Poder
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1063
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
341
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
431
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
277
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
190
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
173
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
68
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
19
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
21
</td>
</tr>
</tbody>
</table>
</div>
<p>Distribución de la variable Percepción de Desigualdad de Poder</p>
</div>
</div>
<p>La escala varía de 1 (Muy Desigual) a 10 (Muy Igual). Se aprecia nuevamente una tendencia de respuestas en los valores más bajos de la escala, y que en los valores más altos la frecuencia va disminuyendo. Debido a esto, se entiende que los encuestados perciben una gran desigualdad de poder.</p>
<ol start="4" type="1">
<li><strong>Autopercepción de clase social</strong></li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Distribución de la variable Autopercepción de Clase Social (excluyendo valores no válidos)
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Autopercepción_Clase_Social
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
464
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
803
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
885
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
318
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
119
</td>
</tr>
</tbody>
</table>
</div>
<p>Distribución de la variable Autopercepción de Clase Social</p>
</div>
</div>
<p>La escala está categorizada en 1 como clase social baja y 5 como clase social alta. La mayoría de los encuestados se identifican con categorías intermedias, especialmente con 3 (Media) con un <em>885</em> respuestas. También hay números considerables en la 2 (Media Baja) con <em>803</em> respuestas y la 1 (Baja) con <em>464</em> respuestas. Mientras que por otro lado, las categorías más altas 4 (Media Alta) y 5 (Alta) tienen frecuencias más bajas. Estas observaciones representan que los encuestados se consideran mayoritariamente de clase media o media baja y que pocas personas se consideran en las clases más altas.</p>
<p><strong>Histograma para variable continua</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Trabajo_final_estadistica_g10_quarto_files/figure-html/fig_7-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de percepción de desigualdad de ingresos</figcaption>
</figure>
</div>
</div>
</div>
<p>Este gráfico demuestra que los encuestados perciben mayoritariamente que los ingresos en la sociedad son muy desiguales. La mayor concentración de respuestas se encuentra en los valores más bajos de la escala (entre 1 y 2), lo que indica que la mayoría de las personas considera que existe una desigualdad significativa en la distribución de los ingresos. A medida que los valores se acercan al extremo de “muy igual” (a 10), las frecuencias disminuyen de manera considerable, lo que evidencia que son pocas las personas que perciben una distribución equitativa.</p>
<p><strong>Histograma para variable categórica</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Trabajo_final_estadistica_g10_quarto_files/figure-html/fig_8-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de la variable Autopercepción de Clase Social</figcaption>
</figure>
</div>
</div>
</div>
<p>Este gráfico demuestra cómo los encuestados se perciben dentro de una escala de clase social, donde 1 corresponde a clase baja, 2 a clase media baja, 3 a clase media, 4 a clase media alta y 5 a clase alta. La mayoría de los encuestados se sitúa en las categorías de clase media (3) y media baja (2), lo que refleja una autopercepción predominante en posiciones intermedias dentro de la jerarquía social. Por otro lado, una menor proporción de personas se identifica con los extremos de la escala, siendo especialmente bajas las frecuencias en las categorías de clase media alta (4) y clase alta (5). Esto indica que pocos encuestados perciben tener acceso a los recursos o privilegios asociados a estas posiciones sociales superiores. En contraste, la percepción de pertenencia a la clase baja (1) tiene una frecuencia moderada, mostrando que una porción significativa de la población aún se siente situada en posiciones de menor ventaja social y económica.</p>
<p><strong>Tabla de sexo y Percepción de desigualdad de ingresos</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Relación entre Sexo y Percepción de Desigualdad de Ingresos
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Percepción_Desigualdad_Ingresos
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
479
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
749
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
111
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
207
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
166
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
242
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
103
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
153
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
52
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
101
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
50
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
86
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
18
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
14
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
11
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
6
</td>
</tr>
</tbody>
</table>
</div>
<p>Relación entre Sexo y Percepción de Desigualdad de Ingresos</p>
</div>
</div>
<p>En cuanto a la percepción de desigualdad de ingresos, tanto hombres como mujeres consideran que esta es predominantemente alta. La mayoría de los hombres <em>(479)</em> y mujeres <em>(749)</em> perciben que Chile en cuanto a ingresos es “muy desigual” (valor 1). A medida que aumenta la percepción de igualdad (valores más altos), las respuestas disminuyen notablemente para ambos géneros, alcanzando mínimos en el valor 10 (“muy igual”), donde solo <em>11</em> hombres y <em>6</em> mujeres consideran que los ingresos son completamente iguales. Sin embargo, se observa que las mujeres tienen una representación ligeramente mayor en las categorías intermedias (valores 3 y 4), lo que sugiere que podrían percibir la desigualdad de una manera más matizada en comparación con los hombres. Aun así, la tendencia general es que ambos géneros identifican una desigualdad significativa en los ingresos, con una proporción mayor en las categorías más desiguales.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Trabajo_final_estadistica_g10_quarto_files/figure-html/fig_10-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Distribución de la Percepción de desigualdad de ingresos según sexo</figcaption>
</figure>
</div>
</div>
</div>
<p>El gráfico refleja la percepción de desigualdad en los ingresos. Al igual que con el poder, tanto hombres como mujeres consideran que los ingresos están distribuidos de manera desigual, con una mediana en valores bajos. En este caso, la mediana de las mujeres es algo más baja que la de los hombres, lo que sugiere que las mujeres perciben una mayor desigualdad en los ingresos. más baja que la de los hombres, lo que da a entender que las mujeres perciben una mayor desigualdad en los ingresos. La dispersión de las respuestas es similar en ambos sexos, pero las mujeres presentan una mayor amplitud en su rango de percepciones, lo que indica respuestas más diversas. Los bigotes se extienden desde valores muy bajos (1, “muy desigual”) hasta valores más altos (10, “muy igual”), y también hay valores atípicos en ambos grupos, siendo más notables en las respuestas de las mujeres.</p>
<p><strong>Tabla de sexo y percepción de desigualdad de poder</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Relación entre Sexo y Percepción de Desigualdad de Poder
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Percepción_Desigualdad_Poder
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
418
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
645
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
135
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
206
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
164
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
267
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
112
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
165
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
63
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
127
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
65
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
108
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
24
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
44
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
16
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
13
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
8
</td>
</tr>
</tbody>
</table>
</div>
<p>Relación entre Sexo y Percepción de Desigualdad de Poder</p>
</div>
</div>
<p>En la tabla se muestra que en cuanto a la percepción de desigualdad de poder, el patrón es similar al observado en ingresos. La mayoría de los hombres <em>(418)</em> y mujeres <em>(645)</em> perciben que el poder está distribuido de manera “muy desigual” (valor 1). Las respuestas disminuyen progresivamente en las categorías intermedias y bajas, con muy pocas personas percibiendo que el poder es “muy igual” (valor 10), siendo esta percepción ligeramente mayor en hombres <em>(13)</em> que en mujeres <em>(8)</em>. A diferencia de los ingresos, las mujeres tienen una representación más significativa en los valores intermedios (por ejemplo, en los valores 3, 4 y 5), lo que podría indicar una percepción menos polarizada o más detallada de la desigualdad en esta dimensión. Sin embargo, la tendencia general de ambos géneros sigue siendo que consideran la desigualdad de poder como un problema predominante, especialmente en las categorías más desiguales.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Trabajo_final_estadistica_g10_quarto_files/figure-html/fig_12-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Relación entre Sexo y Percepción de Desigualdad de Poder</figcaption>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra cómo hombres y mujeres perciben la desigualdad de poder. Ambos sexos tienden a evaluar la distribución del poder como predominantemente desigual, con la mediana de las respuestas ubicada en valores bajos. Sin embargo, las mujeres tienen una mediana ligeramente mayor que los hombres, lo que indica que perciben una desigualdad de poder un poco más pronunciada. En cuanto a la dispersión, la amplitud de las cajas (rango intercuartílico) es similar para ambos sexos, lo que refleja una variabilidad comparable en las percepciones. Los bigotes muestran que las respuestas abarcan desde valores cercanos a “muy desigual” (1) hasta percepciones más igualitarias (10). Además, se identifican valores atípicos en ambos sexos, representando percepciones significativamente diferentes de la tendencia general.</p>
<p><strong>Tabla de sexo y autopercepción de clase social</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Relación entre Sexo y Autopercepción de Clase Social
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Autopercepción_Clase_Social
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Frecuencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
153
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
311
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
268
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
535
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
361
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
524
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
156
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
162
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
61
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
58
</td>
</tr>
</tbody>
</table>
</div>
<p>Relación entre Sexo y Autopercepción de Clase Social</p>
</div>
</div>
<p>En cuanto a la autopercepción de clase social, tanto hombres como mujeres se concentran principalmente en las categorías de clase “Media” y “Media Baja”. En el caso de los hombres, la mayoría se identifica en la clase “Media” <em>(361)</em>, seguida por la clase “Media Baja” <em>(268)</em>. En menor medida, algunos se perciben en la categoría “Media Alta” <em>(156)</em> y “Alta” <em>(61)</em>, mientras que una proporción más reducida se sitúa en la clase “Baja” <em>(153)</em>. Por su parte, las mujeres también se concentran en las categorías “Media” <em>(524)</em> y “Media Baja” <em>(535)</em>, aunque en mayores números que los hombres. Sin embargo, una proporción significativa de mujeres se considera en la clase “Baja” <em>(311)</em>, superando ampliamente a los hombres en esta percepción. En las categorías superiores, las cifras son similares para ambos géneros: en “Media Alta” las mujeres representan 162 y los hombres 156, mientras que en la clase “Alta” hay 58 mujeres frente a 61 hombres. En general, las mujeres tienen una mayor representación en las categorías más bajas, como la clase “Baja” y “Media Baja”, lo que podría reflejar una percepción más desfavorable de su situación socioeconómica en comparación con los hombres. Por el contrario, los hombres tienden a estar ligeramente más representados en las categorías superiores, especialmente en la clase “Alta”. Esto sugiere posibles diferencias de percepción relacionadas con sexo y estatus social.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Trabajo_final_estadistica_g10_quarto_files/figure-html/fig_14-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Relación entre Sexo y Autopercepción de Clase Social</figcaption>
</figure>
</div>
</div>
</div>
<p>El gráfico muestra la autopercepción de clase social según el sexo, en una escala de 1 a 5, donde 1 representa clase baja y 5 clase alta. Tanto hombres como mujeres tienen una mediana de 3 (clase media), con una distribución similar y variabilidad comparable. Los valores atípicos reflejan percepciones extremas, pero en general, la mayoría de las respuestas se concentran entre la clase media-baja (2) y la media-alta (4).</p>
<p><strong>Cálculo de promedios de IC por sexo para cada variable</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:400px; overflow-x: scroll; width:100%; ">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Medias e Intervalos de Confianza por Sexo
</caption>
<thead>
<tr>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Sexo
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Media Autopercepción Clase Social
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
IC Inferior Clase Social
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
IC Superior Clase Social
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Media Percepción Desigualdad Ingresos
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
IC Inferior Ingresos
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
IC Superior Ingresos
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
Media Percepción Desigualdad Poder
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
IC Inferior Poder
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
IC Superior Poder
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2.70
</td>
<td style="text-align:center;">
2.64
</td>
<td style="text-align:center;">
2.77
</td>
<td style="text-align:center;">
2.48
</td>
<td style="text-align:center;">
2.37
</td>
<td style="text-align:center;">
2.60
</td>
<td style="text-align:center;">
2.68
</td>
<td style="text-align:center;">
2.55
</td>
<td style="text-align:center;">
2.80
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2.45
</td>
<td style="text-align:center;">
2.40
</td>
<td style="text-align:center;">
2.50
</td>
<td style="text-align:center;">
2.47
</td>
<td style="text-align:center;">
2.38
</td>
<td style="text-align:center;">
2.56
</td>
<td style="text-align:center;">
2.74
</td>
<td style="text-align:center;">
2.64
</td>
<td style="text-align:center;">
2.83
</td>
</tr>
</tbody>
</table>
</div>
<p>Medias e Intervalos de Confianza por Sexo</p>
</div>
</div>
<p>La media de la autopercepción de la clase social muestra para los hombres es de <em>2.70</em>, con un IC del 95% (2.64; 2.77). Esto demuestra que los hombres tienden a percibirse ligeramente más cercanos a la clase media. Eso sí, el intervalo es estrecho, lo que sugiere una baja variabilidad en las respuestas de los hombres. Por otra parte, la media de las mujeres es <em>2.45</em>, con un IC del 95% (2.40;2.50). Esto muestra que las mujeres tienden a percibirse un poco más cercanas a la clase media baja en comparación a los hombres. Y, al igual que a los hombres, el intervalo de confianza es estrecho, lo que indica una consistencia en sus respuestas.</p>
</section>
<section id="análisis-estadístico-bivariado" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="análisis-estadístico-bivariado"><span class="header-section-number">3.2</span> Análisis estadístico bivariado</h2>
<p><em>Hipótesis 1: Las mujeres perciben que están en una clase social distinta a los hombres.</em></p>
<p><em>Hipótesis nula 1: Las mujeres y hombres se perciben en la misma clase social.</em></p>
<p><strong>Tabla de contingencia</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive table" style="margin-left: auto; margin-right: auto; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Sexo del entrevistado
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:center;">
Clase social
</th>
<th style="text-align:center;">
Hombre (%)
</th>
<th style="text-align:center;">
Mujer (%)
</th>
<th style="text-align:center;">
Total (%)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Clase alta
</td>
<td style="text-align:center;">
154 (15.2%)
</td>
<td style="text-align:center;">
314 (19.6%)
</td>
<td style="text-align:center;">
468 (17.9%)
</td>
</tr>
<tr>
<td style="text-align:center;">
Clase media alta
</td>
<td style="text-align:center;">
271 (26.8%)
</td>
<td style="text-align:center;">
536 (33.5%)
</td>
<td style="text-align:center;">
807 (30.9%)
</td>
</tr>
<tr>
<td style="text-align:center;">
Clase media
</td>
<td style="text-align:center;">
364 (36%)
</td>
<td style="text-align:center;">
526 (32.9%)
</td>
<td style="text-align:center;">
890 (34.1%)
</td>
</tr>
<tr>
<td style="text-align:center;">
Clase media baja
</td>
<td style="text-align:center;">
157 (15.5%)
</td>
<td style="text-align:center;">
163 (10.2%)
</td>
<td style="text-align:center;">
320 (12.2%)
</td>
</tr>
<tr>
<td style="text-align:center;">
Clase baja
</td>
<td style="text-align:center;">
61 (6%)
</td>
<td style="text-align:center;">
58 (3.6%)
</td>
<td style="text-align:center;">
119 (4.6%)
</td>
</tr>
<tr>
<td style="text-align:center;">
NS (no leer)
</td>
<td style="text-align:center;">
5 (0.5%)
</td>
<td style="text-align:center;">
4 (0.2%)
</td>
<td style="text-align:center;">
9 (0.3%)
</td>
</tr>
<tr>
<td style="text-align:center;">
Total
</td>
<td style="text-align:center;">
1012 (100%)
</td>
<td style="text-align:center;">
1601 (100%)
</td>
<td style="text-align:center;">
2613 (100%)
</td>
</tr>
</tbody>
</table>
<p>Tabla de contingencia</p>
</div>
</div>
<p><strong>Chi cuadrado</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Prueba de Chi-cuadrado entre sexo y autopercepción de clase social
</caption>
<thead>
<tr>
<th style="text-align:right;">
X2
</th>
<th style="text-align:left;">
p-value
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:left;">
Método
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
39.96
</td>
<td style="text-align:left;">
&lt; 0.001***
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;width: 8cm; ">
Pearson’s Chi-squared test
</td>
</tr>
</tbody>
</table>
<p>Chi cuadrado</p>
</div>
</div>
<p><strong>Phi</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>X-squared 
0.1242407 </code></pre>
</div>
</div>
<p><strong>Prueba de proporciones</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Resultados de la Prueba de Proporciones
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Grupo
</th>
<th style="text-align:center;">
Proporción.Estimada
</th>
<th style="text-align:center;">
Valor.p
</th>
<th style="text-align:center;">
Intervalo.de.Confianza.Inferior
</th>
<th style="text-align:center;">
Intervalo.de.Confianza.Superior
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
prop 1
</td>
<td style="text-align:center;">
Grupo 1 (Hombres)
</td>
<td style="text-align:center;">
0.153
</td>
<td style="text-align:center;">
0.00718
</td>
<td style="text-align:center;">
-0.073
</td>
<td style="text-align:center;">
-0.012
</td>
</tr>
<tr>
<td style="text-align:left;">
prop 2
</td>
<td style="text-align:center;">
Grupo 2 (Mujeres)
</td>
<td style="text-align:center;">
0.196
</td>
<td style="text-align:center;">
<ul>
<li></li></ul></td>
<td style="text-align:center;">
-0.073
</td>
<td style="text-align:center;">
-0.012
</td>
</tr>
</tbody>
</table>

<p>Tabla de Contingencia y Prueba de Proporciones entre Sexo y Clase Social</p>
<p>:::</p>
<p>:::</p>
<p>En la primera hipótesis planteada, se puede rechazar la hipótesis nula, ya que se observa que las mujeres si se posicionan en una clase social distinta a la de los hombres. La tabla de contingencia muestra la distribución de entrevistados según su sexo y su autopercepción de clase social. En términos generales, los hombres suelen autopercibirse como parte de la clase media con un <em>36%</em> o en la clase media alta con un <em>26.8%</em>. Las mujeres por su lado también suelen autopercibirse en la clase media alta con un <em>33.5%</em> y en la clase media con un <em>32.9%</em>. La prueba de chi cuadrado evalúa que si existe una relación significativa entre el sexo y la autopercepción de clase social. Al obtener como resultado que <em>χ2=39.96, p-value&lt;0.001</em> se puede decir que si existe una asociación estadísticamente significativa entre el sexo y la clase social. El Phi coeficiente arroja un valor de <em>0.1242407</em>, lo cuál quiere decir que si bien el efecto es pequeño, sigue siendo significativo estadísticamente, por lo que hay una relación débil entre las variables sexo y autopercepción de clase social. Según la prueba de proporciones, el valor p obtenido es de <em>0.007178</em>, lo cual es menor al nivel de significancia establecido de 0.05, lo que permite rechazar la hipótesis nula. Además, el intervalo de confianza del 95% <em>(-0.0729, -0.0119)</em> no incluye el valor 0, lo que refuerza la existencia de una diferencia estadísticamente significativa entre las proporciones de ambos grupos. Por lo tanto, los resultados respaldan la hipótesis alternativa, indicando que las mujeres y los hombres tienen percepciones distintas respecto a su clase social.</p>
<p><em>Hipótesis 2: Las mujeres perciben distinta desigualdad de ingresos que los hombres.</em></p>
<p><em>Hipótesis nula 2: Las mujeres y los hombres perciben la misma desigualdad de ingresos.</em></p>
<p><strong>Correlación Punto Biserial</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=2589 valid N=2589 mean=0.61 sd=0.49

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    0 |  999 | 38.59 |   38.59 |  38.59
    1 | 1590 | 61.41 |   61.41 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.477018</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  DES_2016_REC$sexo_rec and DES_2016_REC$per_des_ing
t = -0.13993, df = 2587, p-value = 0.8887
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.04126963  0.03577557
sample estimates:
         cor 
-0.002751116 </code></pre>
</div>
</div>
<p><strong>Prueba de hipótesis estadística Prueba T</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Resultados de la Prueba t de Percepción de Desigualdad de Ingresos por Sexo
</caption>
<thead>
<tr>
<th style="text-align:center;">
estimate
</th>
<th style="text-align:center;">
estimate1
</th>
<th style="text-align:center;">
estimate2
</th>
<th style="text-align:center;">
statistic
</th>
<th style="text-align:center;">
p.value
</th>
<th style="text-align:center;">
parameter
</th>
<th style="text-align:center;">
conf.low
</th>
<th style="text-align:center;">
conf.high
</th>
<th style="text-align:center;">
method
</th>
<th style="text-align:center;">
alternative
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
0.011
</td>
<td style="text-align:center;">
2.483
</td>
<td style="text-align:center;">
2.473
</td>
<td style="text-align:center;">
0.139
</td>
<td style="text-align:center;">
0.445
</td>
<td style="text-align:center;">
2072.259
</td>
<td style="text-align:center;">
-0.114
</td>
<td style="text-align:center;">
Inf
</td>
<td style="text-align:center;">
Welch Two Sample t-test
</td>
<td style="text-align:center;">
greater
</td>
</tr>
</tbody>
</table>
<p>Prueba t de Percepción de Desigualdad de ingresos por sexo</p>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Trabajo_final_estadistica_g10_quarto_files/figure-html/fig_20-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Prueba t de Percepción de Desigualdad de ingresos por sexo</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Test de proporciones</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>   
      1   2   3   4   5   6   7   8   9  10
  0 479 111 166 103  52  50  18   7   2  11
  1 749 207 242 153 101  86  25  14   7   6</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(exitos_hombres, exitos_mujeres) out of c(total_hombres, total_mujeres)
X-squared = 0.065236, df = 1, p-value = 0.7984
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.03429546  0.04619516
sample estimates:
   prop 1    prop 2 
0.4770916 0.4711418 </code></pre>
</div>
</div>
<p>En base a los resultados obtenidos, no se encontró evidencia estadísticamente significativa para rechazar la hipótesis nula de que hombres y mujeres perciben de la misma manera la desigualdad de ingresos. El análisis de la correlación punto biserial arrojó un coeficiente de correlación de <em>-0.00275</em> que es extremadamente bajo, indicando una relación prácticamente inexistente entre la variable de sexo y la percepción de desigualdad de ingresos. Por su parte, el p-valor obtenido de <em>0.8887</em> es mucho mayor al umbral típico de 0.05, lo que significa que no hay evidencia estadística de una relación entre las variables. El intervalo de confianza de <em>(-0.04126963 ; 0.03577557)</em> incluye el valor 0, reforzando que no hay una asociación significativa. La prueba de hipótesis <em>t</em> arroja el valor de <em>0.13897</em>, lo que sugiere una diferencia muy pequeña entre las medias de los dos grupos. En cuanto al p valor de <em>0.4447</em>, al ser un valor mucho mayor al umbral típico de 0.05 se puede decir que no hay suficiente evidencia para rechazar la hipótesis nula. Además el intervalo de confianza incluye valores negativos <em>(-0.1141; inf)</em> lo que refuerza que no hay evidencia para rechazar la hipótesis nula. En este sentido, también la diferencia entre las medias es <em>0.0105</em>, lo cuál es insignificante en términos prácticos. En la prueba de proporciones, el p-valor fue de <em>0.7984</em>, lo que indica que no hay evidencia estadísticamente significativa de una diferencia entre las proporciones de los grupos. El intervalo de confianza incluye el valor 0 al ser <em>(-0.0343; 0.0462)</em>, reforzando que no hay evidencia significativa entre las proporciones. Por lo tanto, los resultados indican que no hay evidencia significativa para rechazar la hipótesis nula de que hombres y mujeres perciben la misma desigualdad de ingresos.</p>
<p><em>Hipótesis 3: Las mujeres perciben distinta desigualdad de poder que los hombres.</em></p>
<p><em>Hipótesis nula: Las mujeres y los hombres perciben la misma desigualdad de poder.</em></p>
<p><strong>Correlación Punto Biserial</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>x &lt;numeric&gt; 
# total N=2589 valid N=2589 mean=0.61 sd=0.49

Value |    N | Raw % | Valid % | Cum. %
---------------------------------------
    0 |  999 | 38.59 |   38.59 |  38.59
    1 | 1590 | 61.41 |   61.41 | 100.00
 &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.713789</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  DES_2016_REC$sexo_rec and DES_2016_REC$per_des_p
t = 0.79058, df = 2587, p-value = 0.4293
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.02299512  0.05403208
sample estimates:
       cor 
0.01554154 </code></pre>
</div>
</div>
<p><strong>Prueba de hipótesis estadística Prueba T</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  DES_2016_REC$per_des_p by DES_2016_REC$sexo_rec
t = -0.7888, df = 2104.7, p-value = 0.7848
alternative hypothesis: true difference in means between group 0 and group 1 is greater than 0
95 percent confidence interval:
 -0.1915289        Inf
sample estimates:
mean in group 0 mean in group 1 
       2.675676        2.737736 </code></pre>
</div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-68df2b12{table-layout:auto;}.cl-688b966e{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-688b9682{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-688b968c{font-family:'Times New Roman';font-size:7.2pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.6pt;}.cl-68aec56c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-68aec580{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-68b102aa{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-68b102c8{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-68b102d2{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-68df2b12"><thead><tr style="overflow-wrap:break-word;"><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b966e">Method</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b966e">Alternative</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b966e">Mean 1</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b966e">Mean 2</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b9682">M</span><span class="cl-688b968c">1</span><span class="cl-688b966e"> - </span><span class="cl-688b9682">M</span><span class="cl-688b968c">2</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b9682">t</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b9682">df</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b9682">p</span></p></th><th class="cl-68b102aa"><p class="cl-68aec56c"><span class="cl-688b966e">95% CI</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-68b102c8"><p class="cl-68aec580"><span class="cl-688b966e">Welch Two Sample t-test</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">greater</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">2.68</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">2.74</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">-0.06</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">-0.79</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">2,104.68</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">.785</span></p></td><td class="cl-68b102d2"><p class="cl-68aec56c"><span class="cl-688b966e">[-0.19, Inf]</span></p></td></tr></tbody></table></div>
<p>Prueba t de Percepción de desigualdad de poder por sexo</p>
</div>
</div>
<p><strong>Test de proporciones</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions with continuity correction

data:  c(exitos_hombres, exitos_mujeres) out of c(total_hombres, total_mujeres)
X-squared = 0.065236, df = 1, p-value = 0.7984
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.03429546  0.04619516
sample estimates:
   prop 1    prop 2 
0.4770916 0.4711418 </code></pre>
</div>
</div>
<p>Los resultados obtenidos en función de la tercera hipótesis no son lo suficientemente significativos estadísticamente para rechazar la hipótesis nula, por lo que no hay evidencia para decir que hombres y mujeres perciben la desigualdad de poder de diferente manera. En el análisis de la correlación punto biserial el valor obtenido del coeficiente de correlación es de <em>0.01554154</em>, demostrando una significancia y correlación demasiado baja como para confirmar una relación entre las variables. El p-valor obtenido es de <em>0.4293</em>, lo que es significativamente mayor al del nivel de significancia (0.05) por lo que se reafirma que no se puede rechazar la H0. En cuanto a la prueba t, con un valor <em>t</em> de <em>-0,79</em> y en función de un valor crítico de 1.96 permite con un nivel de confianza del 95% rechazar nuestra hipótesis inicial, es decir, no hay evidencia suficiente para afirmar que hombres y mujeres perciben de forma diferente la desigualdad de poder. Aquí, el p-valor obtenido fue de <em>0.7848</em>, nuevamente muy superior al nivel de significancia establecido en 0.05. Por otro lado, las proporciones estimadas de hombres y mujeres fueron muy similares (<em>0.477 y 0.471</em>, respectivamente) y el intervalo de confianza del 95% (<em>-0.0343;0.0462</em>) incluye el cero, lo que refuerza la conclusión de que no existen diferencias significativas entre hombres y mujeres respecto a la percepción de desigualdad de poder, por lo que la H0 no se puede rechazar. En este bivariado, el p-valor obtenido fue de <em>0.7984</em>, también significativamente mayor al establecido, otro antecedente que impide rechazar la H0. Por lo tanto, los resultados indican que no hay evidencia significativa para rechazar la hipótesis nula de que hombres y mujeres perciben la misma desigualdad de poder.</p>
<section id="conclusiones" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusiones</h1>
<p>A lo largo de esta investigación y por medio de las distintas técnicas utilizadas para entender la problemática a tratar, se puede concluir que las mujeres perciben estar en una clase social distinta a los hombres, hallazgo que valida la primera hipótesis propuesta. Esto sugiere que el género ocupa un papel relevante en cómo las personas se perciben y perciben al otro en las estructuras de clases sociales. Este hallazgo podría reflejar cómo las mujeres internalizan dinámicas socioculturales que perpetúan su percepción de pertenencia a clases sociales más bajas. Esto podría estar vinculado a una estratificación simbólica basada en el género, donde la valoración del trabajo femenino, las desigualdades salariales y los estigmas asociados al rol de la mujer generan autopercepciones que contrastan con las de los hombres, quienes tienden a identificarse en posiciones más altas de la jerarquía&nbsp;social. Por otro lado, se rechazaron las hipótesis 2 y 3, las cuales sugerían que las mujeres perciben la desigualdad de ingreso y de poder de manera diferente a los hombres, lo que indica que si bien hay un consenso sobre la existencia de un alto nivel de desigualdad de ingresos y poder en Chile, este hecho no incide en una interpretación con perspectiva de género. Todo esto permite concluir que para futuros análisis es recomendable que se exploren los fenómenos a lo largo de un determinado tiempo para analizar así ciertos aspectos ligados a la temporalidad de los sucesos, sobre todo si la base es analizar percepciones, ya que puede resultar sumamente relevante profundizar el aspecto basado en el contexto para lograr obtener un enfoque más representativo y amplio que permita precisar mejor las dinámicas ligadas a la desigualdad en Chile y por lo tanto, las percepciones de esta en&nbsp;sus&nbsp;ciudadanos.</p>
</section>
<section id="bibliografía" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Bibliografía</h1>
<p>Castillo, J., Miranda, D., &amp; Carrasco, D. (2012). Percepción de desigualdad económica en Chile: Medición, diferencias y determinantes. Psykhe, 21(1), 99-114. https://www.scielo.cl/pdf/psykhe/v21n1/art07.pdf</p>
<p>Fraser, N. (2008). Escalas de justicia. Herber Editorial.</p>
<p>Mieres, M. (2020). La dinámica de la desigualdad en Chile: Una mirada regional. Revista de Análisis Económico, 35(2), 91-133. https://www.scielo.cl/scielo.php?pid=S0718-88702020000200091&amp;script=sci_arttext</p>
<p>Programa de las Naciones Unidas para el Desarrollo. (2017). Desigualdades: Orígenes, cambios y desafíos de la brecha social en Chile. Uqbar Editores. https://www.estudiospnud.cl/wp-content/uploads/2020/04/DESIGUALES_reimp-libro-completo.pdf</p>
<p>Rodríguez, S. (2014). Percepciones de desigualdad socioeconómica: Un estudio exploratorio para el caso argentino. Revista de Ciencias Sociales, 27(34), 93-118. http://www.scielo.edu.uy/scielo.php?script=sci_arttext&amp;pid=S0797-55382014000100006&amp;lng=es&amp;tlng=es</p>
</section>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>