name: Render Specific Quarto Markdown to HTML

on:
  push:
    paths:
      - path/to/yourfile.qmd  # Trigger only when this file changes
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render HTML
        run: |
          quarto render path/to/yourfile.qmd --to html

      - name: Deploy HTML to GitHub Pages
        run: |
          quarto publish gh-pages
