name: Render QMD to HTML

on:
  push:
    paths:
      - '**/*.qmd'
  pull_request:
    paths:
      - '**/*.qmd'

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
        sudo dpkg -i quarto-1.3.340-linux-amd64.deb

    - name: Render all QMD files
      run: |
        quarto render
