name: Render Modified QMD to HTML

on:
  push:
    paths:
      - '**/*.qmd'
  pull_request:
    paths:
      - '**/*.qmd'

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Set up Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
        sudo dpkg -i quarto-1.3.340-linux-amd64.deb
    
    - name: Disable Jekyll
      run: echo "" > .nojekyll

    - name: Render modified QMD files
      run: |
        git diff --name-only HEAD^ HEAD | grep '.qmd$' | xargs -I {} quarto render {}

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
