name: Render Modified QMD to HTML

on:
  push:
    paths:
      - '**/*.qmd'
  pull_request:
    paths:
      - '**/*.qmd'

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Reset repository state
      run: |
        git reset --hard
        git clean -fdx
    
    - name: Set up Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
        sudo dpkg -i quarto-1.3.340-linux-amd64.deb
    
    - name: Render modified QMD files
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '.qmd$')
        if [ -z "$CHANGED_FILES" ]; then
          echo "No QMD files changed."
        else
          echo "$CHANGED_FILES" | xargs -I {} quarto render {}
        fi
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
