name: Render and Deploy Quarto to GitHub Pages

on:
  push:
    paths:
      - '**/*.qmd'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: set up r
      uses: r-lib/actions/setup-r@v2 # from https://github.com/r-lib/actions
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        mkdir -p ~/.R/library
        R -e 'install.packages(c("rmarkdown", "knitr"), lib="~/R/library", repos="http://cran.rstudio.com/")'

    - name: Set up Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.340/quarto-1.3.340-linux-amd64.deb
        sudo dpkg -i quarto-1.3.340-linux-amd64.deb

    - name: Render all QMD files
      env:
        R_LIBS_USER: ~/R/library
      run: quarto render --to html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

    - name: Create .nojekyll file
      run: echo "" > docs/.nojekyll
